// flow-typed signature: 79215d35987d6d9ca72d3424f095a929
// flow-typed version: <<STUB>>/@fortawesome/free-regular-svg-icons_v^5.7.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/free-regular-svg-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/free-regular-svg-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/free-regular-svg-icons/faAddressBook' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faAddressCard' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faAngry' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleDown' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleLeft' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleRight' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleUp' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faBell' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faBellSlash' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faBookmark' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faBuilding' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCalendar' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCalendarAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCalendarCheck' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCalendarMinus' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCalendarPlus' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCalendarTimes' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCaretSquareDown' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCaretSquareLeft' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCaretSquareRight' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCaretSquareUp' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faChartBar' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCheckCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCheckSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faClipboard' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faClock' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faClone' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faClosedCaptioning' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faComment' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCommentAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCommentDots' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faComments' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCompass' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCopy' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCopyright' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faCreditCard' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faDizzy' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faDotCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faEdit' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faEnvelope' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faEnvelopeOpen' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faEye' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faEyeSlash' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFile' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileArchive' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileAudio' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileCode' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileExcel' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileImage' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFilePdf' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFilePowerpoint' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileVideo' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFileWord' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFlag' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFlushed' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFolder' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFolderOpen' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFontAwesomeLogoFull' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFrown' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFrownOpen' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faFutbol' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGem' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrimace' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrin' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinBeam' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinBeamSweat' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinHearts' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinSquint' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinSquintTears' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinStars' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinTears' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinTongue' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinTongueSquint' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinTongueWink' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faGrinWink' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandLizard' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandPaper' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandPeace' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandPointDown' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandPointer' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandPointLeft' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandPointRight' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandPointUp' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandRock' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandScissors' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandshake' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHandSpock' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHdd' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHeart' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHospital' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faHourglass' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faIdBadge' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faIdCard' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faImage' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faImages' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faKeyboard' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faKiss' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faKissBeam' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faKissWinkHeart' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faLaugh' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faLaughBeam' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faLaughSquint' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faLaughWink' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faLemon' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faLifeRing' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faLightbulb' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faListAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faMap' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faMeh' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faMehBlank' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faMehRollingEyes' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faMinusSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faMoneyBillAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faMoon' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faNewspaper' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faObjectGroup' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faObjectUngroup' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faPaperPlane' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faPauseCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faPlayCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faPlusSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faQuestionCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faRegistered' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSadCry' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSadTear' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSave' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faShareSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSmile' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSmileBeam' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSmileWink' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSnowflake' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faStar' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faStarHalf' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faStickyNote' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faStopCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSun' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faSurprise' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faThumbsDown' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faThumbsUp' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faTimesCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faTired' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faTrashAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faUser' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faUserCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faWindowClose' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faWindowMaximize' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faWindowMinimize' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/faWindowRestore' {
  declare module.exports: any;
}

declare module '@fortawesome/free-regular-svg-icons/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/free-regular-svg-icons/faAddressBook.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faAddressBook'>;
}
declare module '@fortawesome/free-regular-svg-icons/faAddressCard.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faAddressCard'>;
}
declare module '@fortawesome/free-regular-svg-icons/faAngry.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faAngry'>;
}
declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleDown.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faArrowAltCircleDown'>;
}
declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleLeft.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faArrowAltCircleLeft'>;
}
declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleRight.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faArrowAltCircleRight'>;
}
declare module '@fortawesome/free-regular-svg-icons/faArrowAltCircleUp.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faArrowAltCircleUp'>;
}
declare module '@fortawesome/free-regular-svg-icons/faBell.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faBell'>;
}
declare module '@fortawesome/free-regular-svg-icons/faBellSlash.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faBellSlash'>;
}
declare module '@fortawesome/free-regular-svg-icons/faBookmark.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faBookmark'>;
}
declare module '@fortawesome/free-regular-svg-icons/faBuilding.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faBuilding'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCalendar.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCalendar'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCalendarAlt.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCalendarAlt'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCalendarCheck.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCalendarCheck'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCalendarMinus.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCalendarMinus'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCalendarPlus.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCalendarPlus'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCalendarTimes.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCalendarTimes'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCaretSquareDown.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCaretSquareDown'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCaretSquareLeft.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCaretSquareLeft'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCaretSquareRight.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCaretSquareRight'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCaretSquareUp.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCaretSquareUp'>;
}
declare module '@fortawesome/free-regular-svg-icons/faChartBar.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faChartBar'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCheckCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCheckCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCheckSquare.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCheckSquare'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faClipboard.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faClipboard'>;
}
declare module '@fortawesome/free-regular-svg-icons/faClock.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faClock'>;
}
declare module '@fortawesome/free-regular-svg-icons/faClone.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faClone'>;
}
declare module '@fortawesome/free-regular-svg-icons/faClosedCaptioning.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faClosedCaptioning'>;
}
declare module '@fortawesome/free-regular-svg-icons/faComment.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faComment'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCommentAlt.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCommentAlt'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCommentDots.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCommentDots'>;
}
declare module '@fortawesome/free-regular-svg-icons/faComments.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faComments'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCompass.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCompass'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCopy.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCopy'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCopyright.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCopyright'>;
}
declare module '@fortawesome/free-regular-svg-icons/faCreditCard.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faCreditCard'>;
}
declare module '@fortawesome/free-regular-svg-icons/faDizzy.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faDizzy'>;
}
declare module '@fortawesome/free-regular-svg-icons/faDotCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faDotCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faEdit.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faEdit'>;
}
declare module '@fortawesome/free-regular-svg-icons/faEnvelope.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faEnvelope'>;
}
declare module '@fortawesome/free-regular-svg-icons/faEnvelopeOpen.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faEnvelopeOpen'>;
}
declare module '@fortawesome/free-regular-svg-icons/faEye.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faEye'>;
}
declare module '@fortawesome/free-regular-svg-icons/faEyeSlash.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faEyeSlash'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFile.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFile'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileAlt.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileAlt'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileArchive.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileArchive'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileAudio.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileAudio'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileCode.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileCode'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileExcel.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileExcel'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileImage.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileImage'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFilePdf.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFilePdf'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFilePowerpoint.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFilePowerpoint'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileVideo.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileVideo'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFileWord.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFileWord'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFlag.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFlag'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFlushed.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFlushed'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFolder.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFolder'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFolderOpen.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFolderOpen'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFontAwesomeLogoFull.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFontAwesomeLogoFull'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFrown.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFrown'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFrownOpen.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFrownOpen'>;
}
declare module '@fortawesome/free-regular-svg-icons/faFutbol.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faFutbol'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGem.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGem'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrimace.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrimace'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrin.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrin'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinAlt.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinAlt'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinBeam.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinBeam'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinBeamSweat.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinBeamSweat'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinHearts.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinHearts'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinSquint.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinSquint'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinSquintTears.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinSquintTears'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinStars.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinStars'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinTears.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinTears'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinTongue.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinTongue'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinTongueSquint.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinTongueSquint'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinTongueWink.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinTongueWink'>;
}
declare module '@fortawesome/free-regular-svg-icons/faGrinWink.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faGrinWink'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandLizard.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandLizard'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandPaper.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandPaper'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandPeace.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandPeace'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandPointDown.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandPointDown'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandPointer.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandPointer'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandPointLeft.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandPointLeft'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandPointRight.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandPointRight'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandPointUp.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandPointUp'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandRock.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandRock'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandScissors.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandScissors'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandshake.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandshake'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHandSpock.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHandSpock'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHdd.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHdd'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHeart.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHeart'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHospital.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHospital'>;
}
declare module '@fortawesome/free-regular-svg-icons/faHourglass.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faHourglass'>;
}
declare module '@fortawesome/free-regular-svg-icons/faIdBadge.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faIdBadge'>;
}
declare module '@fortawesome/free-regular-svg-icons/faIdCard.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faIdCard'>;
}
declare module '@fortawesome/free-regular-svg-icons/faImage.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faImage'>;
}
declare module '@fortawesome/free-regular-svg-icons/faImages.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faImages'>;
}
declare module '@fortawesome/free-regular-svg-icons/faKeyboard.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faKeyboard'>;
}
declare module '@fortawesome/free-regular-svg-icons/faKiss.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faKiss'>;
}
declare module '@fortawesome/free-regular-svg-icons/faKissBeam.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faKissBeam'>;
}
declare module '@fortawesome/free-regular-svg-icons/faKissWinkHeart.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faKissWinkHeart'>;
}
declare module '@fortawesome/free-regular-svg-icons/faLaugh.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faLaugh'>;
}
declare module '@fortawesome/free-regular-svg-icons/faLaughBeam.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faLaughBeam'>;
}
declare module '@fortawesome/free-regular-svg-icons/faLaughSquint.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faLaughSquint'>;
}
declare module '@fortawesome/free-regular-svg-icons/faLaughWink.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faLaughWink'>;
}
declare module '@fortawesome/free-regular-svg-icons/faLemon.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faLemon'>;
}
declare module '@fortawesome/free-regular-svg-icons/faLifeRing.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faLifeRing'>;
}
declare module '@fortawesome/free-regular-svg-icons/faLightbulb.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faLightbulb'>;
}
declare module '@fortawesome/free-regular-svg-icons/faListAlt.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faListAlt'>;
}
declare module '@fortawesome/free-regular-svg-icons/faMap.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faMap'>;
}
declare module '@fortawesome/free-regular-svg-icons/faMeh.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faMeh'>;
}
declare module '@fortawesome/free-regular-svg-icons/faMehBlank.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faMehBlank'>;
}
declare module '@fortawesome/free-regular-svg-icons/faMehRollingEyes.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faMehRollingEyes'>;
}
declare module '@fortawesome/free-regular-svg-icons/faMinusSquare.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faMinusSquare'>;
}
declare module '@fortawesome/free-regular-svg-icons/faMoneyBillAlt.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faMoneyBillAlt'>;
}
declare module '@fortawesome/free-regular-svg-icons/faMoon.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faMoon'>;
}
declare module '@fortawesome/free-regular-svg-icons/faNewspaper.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faNewspaper'>;
}
declare module '@fortawesome/free-regular-svg-icons/faObjectGroup.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faObjectGroup'>;
}
declare module '@fortawesome/free-regular-svg-icons/faObjectUngroup.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faObjectUngroup'>;
}
declare module '@fortawesome/free-regular-svg-icons/faPaperPlane.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faPaperPlane'>;
}
declare module '@fortawesome/free-regular-svg-icons/faPauseCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faPauseCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faPlayCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faPlayCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faPlusSquare.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faPlusSquare'>;
}
declare module '@fortawesome/free-regular-svg-icons/faQuestionCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faQuestionCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faRegistered.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faRegistered'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSadCry.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSadCry'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSadTear.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSadTear'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSave.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSave'>;
}
declare module '@fortawesome/free-regular-svg-icons/faShareSquare.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faShareSquare'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSmile.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSmile'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSmileBeam.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSmileBeam'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSmileWink.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSmileWink'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSnowflake.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSnowflake'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSquare.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSquare'>;
}
declare module '@fortawesome/free-regular-svg-icons/faStar.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faStar'>;
}
declare module '@fortawesome/free-regular-svg-icons/faStarHalf.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faStarHalf'>;
}
declare module '@fortawesome/free-regular-svg-icons/faStickyNote.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faStickyNote'>;
}
declare module '@fortawesome/free-regular-svg-icons/faStopCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faStopCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSun.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSun'>;
}
declare module '@fortawesome/free-regular-svg-icons/faSurprise.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faSurprise'>;
}
declare module '@fortawesome/free-regular-svg-icons/faThumbsDown.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faThumbsDown'>;
}
declare module '@fortawesome/free-regular-svg-icons/faThumbsUp.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faThumbsUp'>;
}
declare module '@fortawesome/free-regular-svg-icons/faTimesCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faTimesCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faTired.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faTired'>;
}
declare module '@fortawesome/free-regular-svg-icons/faTrashAlt.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faTrashAlt'>;
}
declare module '@fortawesome/free-regular-svg-icons/faUser.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faUser'>;
}
declare module '@fortawesome/free-regular-svg-icons/faUserCircle.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faUserCircle'>;
}
declare module '@fortawesome/free-regular-svg-icons/faWindowClose.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faWindowClose'>;
}
declare module '@fortawesome/free-regular-svg-icons/faWindowMaximize.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faWindowMaximize'>;
}
declare module '@fortawesome/free-regular-svg-icons/faWindowMinimize.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faWindowMinimize'>;
}
declare module '@fortawesome/free-regular-svg-icons/faWindowRestore.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/faWindowRestore'>;
}
declare module '@fortawesome/free-regular-svg-icons/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons/index.es'>;
}
declare module '@fortawesome/free-regular-svg-icons/index' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons'>;
}
declare module '@fortawesome/free-regular-svg-icons/index.js' {
  declare module.exports: $Exports<'@fortawesome/free-regular-svg-icons'>;
}
