changelog:
  exclude:
    labels:
      - exclude-changelog
  categories:
    - title: Features, fixes, enhancements 🎉
      labels:
        - '*'
      exclude:
        labels:
          - not-testable
          - maintenance
          - web
          - native
    - title: '[web] Features, fixes, enhancements 🎉'
      labels:
        - web
      exclude:
        labels:
          - not-testable
          - maintenance
          - native
    - title: '[native] Features, fixes, enhancements 🎉'
      labels:
        - native
      exclude:
        labels:
          - not-testable
          - maintenance
          - web
    - title: Maintenance 🛠
      labels:
        - not-testable
        - maintenance
