source 'https://rubygems.org'

# Needed for CirleCI macos images
# https://github.com/fastlane/fastlane/issues/21794#issuecomment-2021331335
gem 'rb-readline'

gem 'fastlane', '>= 2.220.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'

# Require the version fixing CVE-2026-54904, CVE-2026-54905 and CVE-2026-54906.
# Versions >= 1.3.5 no longer depend on logger, which activesupport >= 7.1 brings itself.
gem 'concurrent-ruby', '>= 1.3.7'

# >= 1.5.0 fixes CVE-2026-54171. Exclude 1.7.0, which needs ruby >= 3.3 while the CI images ship ruby 3.2.
gem 'excon', '>= 1.5.0', '< 1.7.0'

# Add missing gems in ruby 3.4 until fastlane includes them
# https://github.com/fastlane/fastlane/issues/29183#issuecomment-2567093826
gem 'abbrev'
gem 'mutex_m'
gem 'ostruct'

# Add missing gem
# https://github.com/ckruse/CFPropertyList/issues/74
gem 'nkf'
