source "https://rubygems.org"

# Needed for CirleCI macos images
# https://github.com/fastlane/fastlane/issues/21794#issuecomment-2021331335
gem "rb-readline"

gem "fastlane", ">= 2.220.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'