require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Integreat' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Since Map Libre 5.12.0 is not working yet, we stick to 5.11.0
  $RNMBGL_Use_SPM = {
    url: "https://github.com/maplibre/maplibre-gl-native-distribution",
    requirement: {
      kind: "exactVersion",
      version: "5.11.0"
    },
    product_name: "Mapbox"
  }

  pre_install do |installer|
    # Required for Mapbox
    $RNMBGL.pre_install(installer)
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.96.1' })
  end

  post_install do |installer|
    if !ENV['CI']
      flipper_post_install(installer)
    end

    # Required for Mapbox
    $RNMBGL.post_install(installer)
  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
end
