compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  react-spring-bottom-sheet@3.4.1:
    dependencies:
      react-dom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: 'https://raw.githubusercontent.com/sarahsporck/yarn-plugin-licenses-json/v0.13.0/bundles/%40yarnpkg/plugin-licenses.js'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpIgnorePatterns:
  - ./native/**

yarnPath: .yarn/releases/yarn-3.6.3.cjs

supportedArchitectures: 
  os: 
    - current
    - linux

preferInteractive: true