approvedGitRepositories:
  - '**'

catalog:
  app-toolbelt: 'github:digitalfabrik/app-toolbelt#semver:1.1.0'

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.0.cjs
