description: Runs the lint task and stores junit output
parameters:
  directory:
    type: string
steps:
  - run:
      name: Linting check
      command: yarn workspace << parameters.directory >> run lint:ci
  - run:
      name: Prettier check
      command: yarn workspace << parameters.directory >> prettier --check .
  - store_test_results:
      path: << parameters.directory >>/reports/lint
