description: Restores and saves the node_modules directories of the monorepo.
steps:
  - restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - 6-yarn-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "native/package.json" }}-{{ checksum "web/package.json" }}
  - run:
      name: Install Dependencies
      command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
  - save_cache:
      name: Save Yarn Package Cache
      key: 6-yarn-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "native/package.json" }}-{{ checksum "web/package.json" }}
      paths:
        - ~/.cache/yarn
        - node_modules
        - native/node_modules
        - web/node_modules
