description: Restores and saves the node_modules directories of the monorepo.
steps:
  - restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - 8-yarn-2-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "native/package.json" }}-{{ checksum "web/package.json" }}
  - run:
      name: Install Dependencies
      command: yarn install --immutable
  - save_cache:
      name: Save Yarn Package Cache
      key: 8-yarn-2-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "native/package.json" }}-{{ checksum "web/package.json" }}
      paths:
        - .yarn/cache