description: Restores and saves the node_modules directories of the monorepo.
steps:
  - restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - 9-yarn-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "native/package.json" }}-{{ checksum "web/package.json" }}
        - 9-yarn-{{ arch }}-
  - run:
      name: Yarn
      command: yarn --immutable
  - save_cache:
      name: Save Yarn Package Cache
      key: 9-yarn-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ checksum "native/package.json" }}-{{ checksum "web/package.json" }}
      paths:
        - .yarn/cache
