description: Restores and saves the node_modules directories of the tools package.
steps:
  - restore_cache:
      name: Restore Yarn Tools Package Cache
      keys:
        - 2-yarn-{{ arch }}-{{ checksum "tools/yarn.lock" }}-{{ checksum "tools/package.json" }}
  - run:
      name: Yarn tools
      command: yarn install --immutable
      working_directory: tools
  - save_cache:
      name: Save Yarn Tools Package Cache
      key: 2-yarn-{{ arch }}-{{ checksum "tools/yarn.lock" }}-{{ checksum "tools/package.json" }}
      paths:
        - tools/.yarn/cache
        - tools/node_modules
