// flow-typed signature: 1b4dd8dd3443c9e908a80f97e9009ea4
// flow-typed version: <<STUB>>/detect-browser_v^3.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'detect-browser/index' {
  declare module.exports: $Exports<'detect-browser'>;
}
declare module 'detect-browser/index.js' {
  declare module.exports: $Exports<'detect-browser'>;
}
