// flow-typed signature: 7717d30e457dac3a49a685bebe3bf240
// flow-typed version: <<STUB>>/eslint-plugin-prefer-object-spread_v^1.2.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-prefer-object-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-prefer-object-spread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-prefer-object-spread/dist/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-prefer-object-spread/dist/rules/prefer-object-spread' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-prefer-object-spread/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-prefer-object-spread/dist/index'>;
}
declare module 'eslint-plugin-prefer-object-spread/dist/rules/prefer-object-spread.js' {
  declare module.exports: $Exports<'eslint-plugin-prefer-object-spread/dist/rules/prefer-object-spread'>;
}
