// flow-typed signature: bdfb7b831189fbc3c20bf76c23698dba
// flow-typed version: <<STUB>>/fnv-plus_v^1.2.12/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fnv-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fnv-plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fnv-plus/test/fnv-plus' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fnv-plus/index' {
  declare module.exports: $Exports<'fnv-plus'>;
}
declare module 'fnv-plus/index.js' {
  declare module.exports: $Exports<'fnv-plus'>;
}
declare module 'fnv-plus/test/fnv-plus.js' {
  declare module.exports: $Exports<'fnv-plus/test/fnv-plus'>;
}
