// flow-typed signature: 6192b76f460f4d11fbf52e91689353ac
// flow-typed version: <<STUB>>/generate-package-json-webpack-plugin_v^1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generate-package-json-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generate-package-json-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'generate-package-json-webpack-plugin/index' {
  declare module.exports: $Exports<'generate-package-json-webpack-plugin'>;
}
declare module 'generate-package-json-webpack-plugin/index.js' {
  declare module.exports: $Exports<'generate-package-json-webpack-plugin'>;
}
