// flow-typed signature: 59793d1a0bcb2834c9e4a1fc8198344b
// flow-typed version: <<STUB>>/git-repo-version_v^1.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-repo-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-repo-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-repo-version/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-repo-version/index' {
  declare module.exports: $Exports<'git-repo-version'>;
}
declare module 'git-repo-version/index.js' {
  declare module.exports: $Exports<'git-repo-version'>;
}
declare module 'git-repo-version/test/index.js' {
  declare module.exports: $Exports<'git-repo-version/test/index'>;
}
