// flow-typed signature: e415db5d8762ee8155bbe815c78d6c43
// flow-typed version: <<STUB>>/hashids_v^2.2.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hashids'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hashids' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hashids/cjs' {
  declare module.exports: any;
}

declare module 'hashids/dist/hashids' {
  declare module.exports: any;
}

declare module 'hashids/dist/hashids.min' {
  declare module.exports: any;
}

declare module 'hashids/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hashids/cjs/index' {
  declare module.exports: $Exports<'hashids/cjs'>;
}
declare module 'hashids/cjs/index.js' {
  declare module.exports: $Exports<'hashids/cjs'>;
}
declare module 'hashids/dist/hashids.js' {
  declare module.exports: $Exports<'hashids/dist/hashids'>;
}
declare module 'hashids/dist/hashids.min.js' {
  declare module.exports: $Exports<'hashids/dist/hashids.min'>;
}
declare module 'hashids/esm/index' {
  declare module.exports: $Exports<'hashids/esm'>;
}
declare module 'hashids/esm/index.js' {
  declare module.exports: $Exports<'hashids/esm'>;
}
