// flow-typed signature: 96d3610f70d326b344ead060743105fc
// flow-typed version: <<STUB>>/hashids_v^1.2.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hashids'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hashids' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hashids/dist/hashids-esm' {
  declare module.exports: any;
}

declare module 'hashids/dist/hashids' {
  declare module.exports: any;
}

declare module 'hashids/dist/hashids.min' {
  declare module.exports: any;
}

declare module 'hashids/dist/index' {
  declare module.exports: any;
}

declare module 'hashids/lib/hashids' {
  declare module.exports: any;
}

declare module 'hashids/tests-mjs/importing' {
  declare module.exports: any;
}

declare module 'hashids/tests/bad-input' {
  declare module.exports: any;
}

declare module 'hashids/tests/custom-alphabet' {
  declare module.exports: any;
}

declare module 'hashids/tests/custom-params-hex' {
  declare module.exports: any;
}

declare module 'hashids/tests/custom-params' {
  declare module.exports: any;
}

declare module 'hashids/tests/custom-salt' {
  declare module.exports: any;
}

declare module 'hashids/tests/default-params-hex' {
  declare module.exports: any;
}

declare module 'hashids/tests/default-params' {
  declare module.exports: any;
}

declare module 'hashids/tests/encode-types' {
  declare module.exports: any;
}

declare module 'hashids/tests/min-length' {
  declare module.exports: any;
}

declare module 'hashids/tests/requiring' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hashids/dist/hashids-esm.js' {
  declare module.exports: $Exports<'hashids/dist/hashids-esm'>;
}
declare module 'hashids/dist/hashids.js' {
  declare module.exports: $Exports<'hashids/dist/hashids'>;
}
declare module 'hashids/dist/hashids.min.js' {
  declare module.exports: $Exports<'hashids/dist/hashids.min'>;
}
declare module 'hashids/dist/index.js' {
  declare module.exports: $Exports<'hashids/dist/index'>;
}
declare module 'hashids/lib/hashids.js' {
  declare module.exports: $Exports<'hashids/lib/hashids'>;
}
declare module 'hashids/tests-mjs/importing.js' {
  declare module.exports: $Exports<'hashids/tests-mjs/importing'>;
}
declare module 'hashids/tests/bad-input.js' {
  declare module.exports: $Exports<'hashids/tests/bad-input'>;
}
declare module 'hashids/tests/custom-alphabet.js' {
  declare module.exports: $Exports<'hashids/tests/custom-alphabet'>;
}
declare module 'hashids/tests/custom-params-hex.js' {
  declare module.exports: $Exports<'hashids/tests/custom-params-hex'>;
}
declare module 'hashids/tests/custom-params.js' {
  declare module.exports: $Exports<'hashids/tests/custom-params'>;
}
declare module 'hashids/tests/custom-salt.js' {
  declare module.exports: $Exports<'hashids/tests/custom-salt'>;
}
declare module 'hashids/tests/default-params-hex.js' {
  declare module.exports: $Exports<'hashids/tests/default-params-hex'>;
}
declare module 'hashids/tests/default-params.js' {
  declare module.exports: $Exports<'hashids/tests/default-params'>;
}
declare module 'hashids/tests/encode-types.js' {
  declare module.exports: $Exports<'hashids/tests/encode-types'>;
}
declare module 'hashids/tests/min-length.js' {
  declare module.exports: $Exports<'hashids/tests/min-length'>;
}
declare module 'hashids/tests/requiring.js' {
  declare module.exports: $Exports<'hashids/tests/requiring'>;
}
