// flow-typed signature: 943b9987f640dc0cf2c76389056ce360
// flow-typed version: <<STUB>>/htmlparser2_v^4.0.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmlparser2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmlparser2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'htmlparser2/lib/CollectingHandler' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/FeedHandler' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/MultiplexHandler' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/Parser' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/Tokenizer' {
  declare module.exports: any;
}

declare module 'htmlparser2/lib/WritableStream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'htmlparser2/lib/CollectingHandler.js' {
  declare module.exports: $Exports<'htmlparser2/lib/CollectingHandler'>;
}
declare module 'htmlparser2/lib/FeedHandler.js' {
  declare module.exports: $Exports<'htmlparser2/lib/FeedHandler'>;
}
declare module 'htmlparser2/lib/index' {
  declare module.exports: $Exports<'htmlparser2/lib'>;
}
declare module 'htmlparser2/lib/index.js' {
  declare module.exports: $Exports<'htmlparser2/lib'>;
}
declare module 'htmlparser2/lib/MultiplexHandler.js' {
  declare module.exports: $Exports<'htmlparser2/lib/MultiplexHandler'>;
}
declare module 'htmlparser2/lib/Parser.js' {
  declare module.exports: $Exports<'htmlparser2/lib/Parser'>;
}
declare module 'htmlparser2/lib/Tokenizer.js' {
  declare module.exports: $Exports<'htmlparser2/lib/Tokenizer'>;
}
declare module 'htmlparser2/lib/WritableStream.js' {
  declare module.exports: $Exports<'htmlparser2/lib/WritableStream'>;
}
