// flow-typed signature: 5ccbc6df7a6b2a4723e77bd59f6019bf
// flow-typed version: <<STUB>>/img-loader_v^3.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'img-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'img-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'img-loader/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'img-loader/__tests__/run-webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'img-loader/__tests__/index.spec.js' {
  declare module.exports: $Exports<'img-loader/__tests__/index.spec'>;
}
declare module 'img-loader/__tests__/run-webpack.js' {
  declare module.exports: $Exports<'img-loader/__tests__/run-webpack'>;
}
declare module 'img-loader/index' {
  declare module.exports: $Exports<'img-loader'>;
}
declare module 'img-loader/index.js' {
  declare module.exports: $Exports<'img-loader'>;
}
