// flow-typed signature: e4489a81cd862161aca8b8efced79501
// flow-typed version: <<STUB>>/js-md5_v^0.7.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-md5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-md5/build/md5.min' {
  declare module.exports: any;
}

declare module 'js-md5/src/md5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-md5/build/md5.min.js' {
  declare module.exports: $Exports<'js-md5/build/md5.min'>;
}
declare module 'js-md5/src/md5.js' {
  declare module.exports: $Exports<'js-md5/src/md5'>;
}
