// flow-typed signature: 6af6fdb6dbee974e022e11b16ea5bb07
// flow-typed version: <<STUB>>/normalize.css_v^8.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
