// flow-typed signature: 81c72d217a542cc78a08167ec319d240
// flow-typed version: <<STUB>>/pleeease-filters_v^4.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pleeease-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pleeease-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pleeease-filters/index' {
  declare module.exports: $Exports<'pleeease-filters'>;
}
declare module 'pleeease-filters/index.js' {
  declare module.exports: $Exports<'pleeease-filters'>;
}
