// flow-typed signature: c52a606e642479b58ad7176a9954a88c
// flow-typed version: <<STUB>>/postcss-syntax_v^0.31.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-syntax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-syntax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-syntax/document' {
  declare module.exports: any;
}

declare module 'postcss-syntax/get-lang' {
  declare module.exports: any;
}

declare module 'postcss-syntax/get-syntax' {
  declare module.exports: any;
}

declare module 'postcss-syntax/load-syntax' {
  declare module.exports: any;
}

declare module 'postcss-syntax/normal-opts' {
  declare module.exports: any;
}

declare module 'postcss-syntax/parse-style' {
  declare module.exports: any;
}

declare module 'postcss-syntax/parse' {
  declare module.exports: any;
}

declare module 'postcss-syntax/parser' {
  declare module.exports: any;
}

declare module 'postcss-syntax/patch-postcss' {
  declare module.exports: any;
}

declare module 'postcss-syntax/processor' {
  declare module.exports: any;
}

declare module 'postcss-syntax/stringify' {
  declare module.exports: any;
}

declare module 'postcss-syntax/syntax' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-syntax/document.js' {
  declare module.exports: $Exports<'postcss-syntax/document'>;
}
declare module 'postcss-syntax/get-lang.js' {
  declare module.exports: $Exports<'postcss-syntax/get-lang'>;
}
declare module 'postcss-syntax/get-syntax.js' {
  declare module.exports: $Exports<'postcss-syntax/get-syntax'>;
}
declare module 'postcss-syntax/index' {
  declare module.exports: $Exports<'postcss-syntax'>;
}
declare module 'postcss-syntax/index.js' {
  declare module.exports: $Exports<'postcss-syntax'>;
}
declare module 'postcss-syntax/load-syntax.js' {
  declare module.exports: $Exports<'postcss-syntax/load-syntax'>;
}
declare module 'postcss-syntax/normal-opts.js' {
  declare module.exports: $Exports<'postcss-syntax/normal-opts'>;
}
declare module 'postcss-syntax/parse-style.js' {
  declare module.exports: $Exports<'postcss-syntax/parse-style'>;
}
declare module 'postcss-syntax/parse.js' {
  declare module.exports: $Exports<'postcss-syntax/parse'>;
}
declare module 'postcss-syntax/parser.js' {
  declare module.exports: $Exports<'postcss-syntax/parser'>;
}
declare module 'postcss-syntax/patch-postcss.js' {
  declare module.exports: $Exports<'postcss-syntax/patch-postcss'>;
}
declare module 'postcss-syntax/processor.js' {
  declare module.exports: $Exports<'postcss-syntax/processor'>;
}
declare module 'postcss-syntax/stringify.js' {
  declare module.exports: $Exports<'postcss-syntax/stringify'>;
}
declare module 'postcss-syntax/syntax.js' {
  declare module.exports: $Exports<'postcss-syntax/syntax'>;
}
