// flow-typed signature: a7113d0e132c0d102524fc37a8efb03a
// flow-typed version: <<STUB>>/react-native-permissions_v2.0.9/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-permissions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-permissions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-permissions/lib/commonjs/constants' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/constants' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/types' {
  declare module.exports: any;
}

declare module 'react-native-permissions/mock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-permissions/lib/commonjs/constants.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/constants'>;
}
declare module 'react-native-permissions/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs'>;
}
declare module 'react-native-permissions/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs'>;
}
declare module 'react-native-permissions/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/types'>;
}
declare module 'react-native-permissions/lib/module/constants.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/constants'>;
}
declare module 'react-native-permissions/lib/module/index' {
  declare module.exports: $Exports<'react-native-permissions/lib/module'>;
}
declare module 'react-native-permissions/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module'>;
}
declare module 'react-native-permissions/lib/module/types.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/types'>;
}
declare module 'react-native-permissions/mock.js' {
  declare module.exports: $Exports<'react-native-permissions/mock'>;
}
