// flow-typed signature: 79ce179880d51aee363025225a918358
// flow-typed version: <<STUB>>/react-native-svg-asset-plugin_v^0.3.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg-asset-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg-asset-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg-asset-plugin/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg-asset-plugin/lib/index' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib'>;
}
declare module 'react-native-svg-asset-plugin/lib/index.js' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib'>;
}
