// flow-typed signature: f5af850672e80bcd33b0349c4786f706
// flow-typed version: <<STUB>>/react-i18next_v^9.0.5/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-i18next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-i18next/dist/amd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/amd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/useSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/useTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/withSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/hooks/withTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/Interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/NamespacesConsumer' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/withNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/useSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/useTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/withSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/hooks/withTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/Interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/NamespacesConsumer' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/withNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/hooks' {
  declare module.exports: any;
}

declare module 'react-i18next/icu.macro' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/rollup.config' {
  declare module.exports: any;
}

declare module 'react-i18next/src/context' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/context' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/index' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/useSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/useTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/withSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/src/hooks/withTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/src/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/src/index' {
  declare module.exports: any;
}

declare module 'react-i18next/src/Interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/src/NamespacesConsumer' {
  declare module.exports: any;
}

declare module 'react-i18next/src/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/src/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/src/withNamespaces' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-i18next/dist/amd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next'>;
}
declare module 'react-i18next/dist/amd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next.min'>;
}
declare module 'react-i18next/dist/commonjs/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/context'>;
}
declare module 'react-i18next/dist/commonjs/hooks/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/context'>;
}
declare module 'react-i18next/dist/commonjs/hooks/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/index'>;
}
declare module 'react-i18next/dist/commonjs/hooks/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/Trans'>;
}
declare module 'react-i18next/dist/commonjs/hooks/useSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/useSSR'>;
}
declare module 'react-i18next/dist/commonjs/hooks/useTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/useTranslation'>;
}
declare module 'react-i18next/dist/commonjs/hooks/utils.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/utils'>;
}
declare module 'react-i18next/dist/commonjs/hooks/withSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/withSSR'>;
}
declare module 'react-i18next/dist/commonjs/hooks/withTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/hooks/withTranslation'>;
}
declare module 'react-i18next/dist/commonjs/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/I18nextProvider'>;
}
declare module 'react-i18next/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/index'>;
}
declare module 'react-i18next/dist/commonjs/Interpolate.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/Interpolate'>;
}
declare module 'react-i18next/dist/commonjs/NamespacesConsumer.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/NamespacesConsumer'>;
}
declare module 'react-i18next/dist/commonjs/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/Trans'>;
}
declare module 'react-i18next/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/utils'>;
}
declare module 'react-i18next/dist/commonjs/withNamespaces.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/withNamespaces'>;
}
declare module 'react-i18next/dist/es/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/context'>;
}
declare module 'react-i18next/dist/es/hooks/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/context'>;
}
declare module 'react-i18next/dist/es/hooks/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/index'>;
}
declare module 'react-i18next/dist/es/hooks/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/Trans'>;
}
declare module 'react-i18next/dist/es/hooks/useSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/useSSR'>;
}
declare module 'react-i18next/dist/es/hooks/useTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/useTranslation'>;
}
declare module 'react-i18next/dist/es/hooks/utils.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/utils'>;
}
declare module 'react-i18next/dist/es/hooks/withSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/withSSR'>;
}
declare module 'react-i18next/dist/es/hooks/withTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/hooks/withTranslation'>;
}
declare module 'react-i18next/dist/es/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/I18nextProvider'>;
}
declare module 'react-i18next/dist/es/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/index'>;
}
declare module 'react-i18next/dist/es/Interpolate.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/Interpolate'>;
}
declare module 'react-i18next/dist/es/NamespacesConsumer.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/NamespacesConsumer'>;
}
declare module 'react-i18next/dist/es/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/Trans'>;
}
declare module 'react-i18next/dist/es/utils.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/utils'>;
}
declare module 'react-i18next/dist/es/withNamespaces.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/withNamespaces'>;
}
declare module 'react-i18next/dist/umd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next'>;
}
declare module 'react-i18next/dist/umd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next.min'>;
}
declare module 'react-i18next/hooks.js' {
  declare module.exports: $Exports<'react-i18next/hooks'>;
}
declare module 'react-i18next/icu.macro.js' {
  declare module.exports: $Exports<'react-i18next/icu.macro'>;
}
declare module 'react-i18next/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next'>;
}
declare module 'react-i18next/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next.min'>;
}
declare module 'react-i18next/rollup.config.js' {
  declare module.exports: $Exports<'react-i18next/rollup.config'>;
}
declare module 'react-i18next/src/context.js' {
  declare module.exports: $Exports<'react-i18next/src/context'>;
}
declare module 'react-i18next/src/hooks/context.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/context'>;
}
declare module 'react-i18next/src/hooks/index.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/index'>;
}
declare module 'react-i18next/src/hooks/Trans.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/Trans'>;
}
declare module 'react-i18next/src/hooks/useSSR.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/useSSR'>;
}
declare module 'react-i18next/src/hooks/useTranslation.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/useTranslation'>;
}
declare module 'react-i18next/src/hooks/utils.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/utils'>;
}
declare module 'react-i18next/src/hooks/withSSR.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/withSSR'>;
}
declare module 'react-i18next/src/hooks/withTranslation.js' {
  declare module.exports: $Exports<'react-i18next/src/hooks/withTranslation'>;
}
declare module 'react-i18next/src/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/src/I18nextProvider'>;
}
declare module 'react-i18next/src/index.js' {
  declare module.exports: $Exports<'react-i18next/src/index'>;
}
declare module 'react-i18next/src/Interpolate.js' {
  declare module.exports: $Exports<'react-i18next/src/Interpolate'>;
}
declare module 'react-i18next/src/NamespacesConsumer.js' {
  declare module.exports: $Exports<'react-i18next/src/NamespacesConsumer'>;
}
declare module 'react-i18next/src/Trans.js' {
  declare module.exports: $Exports<'react-i18next/src/Trans'>;
}
declare module 'react-i18next/src/utils.js' {
  declare module.exports: $Exports<'react-i18next/src/utils'>;
}
declare module 'react-i18next/src/withNamespaces.js' {
  declare module.exports: $Exports<'react-i18next/src/withNamespaces'>;
}
