// flow-typed signature: bde3421e8cbb668fc49f4462639f6b87
// flow-typed version: <<STUB>>/react-spinkit_v^3.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinkit/dist/index' {
  declare module.exports: any;
}

declare module 'react-spinkit/dist/spinners' {
  declare module.exports: any;
}

declare module 'react-spinkit/examples/bundle' {
  declare module.exports: any;
}

declare module 'react-spinkit/src/index' {
  declare module.exports: any;
}

declare module 'react-spinkit/src/spinners' {
  declare module.exports: any;
}

declare module 'react-spinkit/test/index.test' {
  declare module.exports: any;
}

declare module 'react-spinkit/www/html' {
  declare module.exports: any;
}

declare module 'react-spinkit/www/pages/_template' {
  declare module.exports: any;
}

declare module 'react-spinkit/www/pages/index' {
  declare module.exports: any;
}

declare module 'react-spinkit/www/public/bundle' {
  declare module.exports: any;
}

declare module 'react-spinkit/www/utils/typography' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinkit/dist/index.js' {
  declare module.exports: $Exports<'react-spinkit/dist/index'>;
}
declare module 'react-spinkit/dist/spinners.js' {
  declare module.exports: $Exports<'react-spinkit/dist/spinners'>;
}
declare module 'react-spinkit/examples/bundle.js' {
  declare module.exports: $Exports<'react-spinkit/examples/bundle'>;
}
declare module 'react-spinkit/src/index.jsx' {
  declare module.exports: $Exports<'react-spinkit/src/index'>;
}
declare module 'react-spinkit/src/spinners.js' {
  declare module.exports: $Exports<'react-spinkit/src/spinners'>;
}
declare module 'react-spinkit/test/index.test.jsx' {
  declare module.exports: $Exports<'react-spinkit/test/index.test'>;
}
declare module 'react-spinkit/www/html.js' {
  declare module.exports: $Exports<'react-spinkit/www/html'>;
}
declare module 'react-spinkit/www/pages/_template.jsx' {
  declare module.exports: $Exports<'react-spinkit/www/pages/_template'>;
}
declare module 'react-spinkit/www/pages/index.js' {
  declare module.exports: $Exports<'react-spinkit/www/pages/index'>;
}
declare module 'react-spinkit/www/public/bundle.js' {
  declare module.exports: $Exports<'react-spinkit/www/public/bundle'>;
}
declare module 'react-spinkit/www/utils/typography.js' {
  declare module.exports: $Exports<'react-spinkit/www/utils/typography'>;
}
