// flow-typed signature: 4ed8e720ae38263d9d5ef062f1ad046f
// flow-typed version: <<STUB>>/react-navigation-header-buttons_v^2.1.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-header-buttons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-header-buttons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-header-buttons/src/HeaderButton' {
  declare module.exports: any;
}

declare module 'react-navigation-header-buttons/src/HeaderButtons' {
  declare module.exports: any;
}

declare module 'react-navigation-header-buttons/src/OverflowButton' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-header-buttons/index' {
  declare module.exports: $Exports<'react-navigation-header-buttons'>;
}
declare module 'react-navigation-header-buttons/index.js' {
  declare module.exports: $Exports<'react-navigation-header-buttons'>;
}
declare module 'react-navigation-header-buttons/src/HeaderButton.js' {
  declare module.exports: $Exports<'react-navigation-header-buttons/src/HeaderButton'>;
}
declare module 'react-navigation-header-buttons/src/HeaderButtons.js' {
  declare module.exports: $Exports<'react-navigation-header-buttons/src/HeaderButtons'>;
}
declare module 'react-navigation-header-buttons/src/OverflowButton.js' {
  declare module.exports: $Exports<'react-navigation-header-buttons/src/OverflowButton'>;
}
