// flow-typed signature: 7fa7aa71acb2e2a992d9d5b556f2b9db
// flow-typed version: <<STUB>>/react-native-webview_v^8.0.6/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-webview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-webview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-webview/lib/WebView.android' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView.ios' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView.styles' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebViewShared' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebViewTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-webview/index' {
  declare module.exports: $Exports<'react-native-webview'>;
}
declare module 'react-native-webview/index.js' {
  declare module.exports: $Exports<'react-native-webview'>;
}
declare module 'react-native-webview/lib/WebView.android.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.android'>;
}
declare module 'react-native-webview/lib/WebView.ios.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.ios'>;
}
declare module 'react-native-webview/lib/WebView.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView'>;
}
declare module 'react-native-webview/lib/WebView.styles.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.styles'>;
}
declare module 'react-native-webview/lib/WebViewShared.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebViewShared'>;
}
declare module 'react-native-webview/lib/WebViewTypes.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebViewTypes'>;
}
