// flow-typed signature: 2e90ba7c8b77f0e88dabfef6fa50857f
// flow-typed version: <<STUB>>/react-dropdown_v^1.5.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropdown/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropdown/dist/index.js' {
  declare module.exports: $Exports<'react-dropdown/dist/index'>;
}
