// flow-typed signature: f695923fe839f09a71164191be1f7cac
// flow-typed version: <<STUB>>/react-native-offline_v^4.3.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-offline/src/components/NetworkConnectivity' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/components/NetworkConsumer' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/components/NetworkContext' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/components/NetworkProvider' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/components/ReduxNetworkProvider' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/index' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/redux/actionCreators' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/redux/actionTypes' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/redux/createNetworkMiddleware' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/redux/reducer' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/redux/sagas' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/types' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/utils/checkConnectivityInterval' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/utils/checkInternetAccess' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/utils/checkInternetConnection' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/utils/constants' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/utils/getSimilarActionInQueue' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/utils/makeHttpRequest' {
  declare module.exports: any;
}

declare module 'react-native-offline/src/utils/wait' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-offline/src/components/NetworkConnectivity.js' {
  declare module.exports: $Exports<'react-native-offline/src/components/NetworkConnectivity'>;
}
declare module 'react-native-offline/src/components/NetworkConsumer.js' {
  declare module.exports: $Exports<'react-native-offline/src/components/NetworkConsumer'>;
}
declare module 'react-native-offline/src/components/NetworkContext.js' {
  declare module.exports: $Exports<'react-native-offline/src/components/NetworkContext'>;
}
declare module 'react-native-offline/src/components/NetworkProvider.js' {
  declare module.exports: $Exports<'react-native-offline/src/components/NetworkProvider'>;
}
declare module 'react-native-offline/src/components/ReduxNetworkProvider.js' {
  declare module.exports: $Exports<'react-native-offline/src/components/ReduxNetworkProvider'>;
}
declare module 'react-native-offline/src/index.js' {
  declare module.exports: $Exports<'react-native-offline/src/index'>;
}
declare module 'react-native-offline/src/redux/actionCreators.js' {
  declare module.exports: $Exports<'react-native-offline/src/redux/actionCreators'>;
}
declare module 'react-native-offline/src/redux/actionTypes.js' {
  declare module.exports: $Exports<'react-native-offline/src/redux/actionTypes'>;
}
declare module 'react-native-offline/src/redux/createNetworkMiddleware.js' {
  declare module.exports: $Exports<'react-native-offline/src/redux/createNetworkMiddleware'>;
}
declare module 'react-native-offline/src/redux/reducer.js' {
  declare module.exports: $Exports<'react-native-offline/src/redux/reducer'>;
}
declare module 'react-native-offline/src/redux/sagas.js' {
  declare module.exports: $Exports<'react-native-offline/src/redux/sagas'>;
}
declare module 'react-native-offline/src/types.js' {
  declare module.exports: $Exports<'react-native-offline/src/types'>;
}
declare module 'react-native-offline/src/utils/checkConnectivityInterval.js' {
  declare module.exports: $Exports<'react-native-offline/src/utils/checkConnectivityInterval'>;
}
declare module 'react-native-offline/src/utils/checkInternetAccess.js' {
  declare module.exports: $Exports<'react-native-offline/src/utils/checkInternetAccess'>;
}
declare module 'react-native-offline/src/utils/checkInternetConnection.js' {
  declare module.exports: $Exports<'react-native-offline/src/utils/checkInternetConnection'>;
}
declare module 'react-native-offline/src/utils/constants.js' {
  declare module.exports: $Exports<'react-native-offline/src/utils/constants'>;
}
declare module 'react-native-offline/src/utils/getSimilarActionInQueue.js' {
  declare module.exports: $Exports<'react-native-offline/src/utils/getSimilarActionInQueue'>;
}
declare module 'react-native-offline/src/utils/makeHttpRequest.js' {
  declare module.exports: $Exports<'react-native-offline/src/utils/makeHttpRequest'>;
}
declare module 'react-native-offline/src/utils/wait.js' {
  declare module.exports: $Exports<'react-native-offline/src/utils/wait'>;
}
