// flow-typed signature: a177d1e861a3b8cc0dafb6b92b377f54
// flow-typed version: <<STUB>>/react-styled-flexboxgrid_v^2.4.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-styled-flexboxgrid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-styled-flexboxgrid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-styled-flexboxgrid/dist/styled-flexboxgrid.es' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/dist/styled-flexboxgrid' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/dist/styled-flexboxgrid.min' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/karma.conf' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/components/Col' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/components/Col.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/components/Grid' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/components/Grid.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/components/Row' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/components/Row.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/config' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/config.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/index' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/components/Col' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/components/Col.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/components/Grid' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/components/Grid.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/components/Row' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/components/Row.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/config' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/config.test' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/index' {
  declare module.exports: any;
}

declare module 'react-styled-flexboxgrid/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-styled-flexboxgrid/dist/styled-flexboxgrid.es.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/dist/styled-flexboxgrid.es'>;
}
declare module 'react-styled-flexboxgrid/dist/styled-flexboxgrid.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/dist/styled-flexboxgrid'>;
}
declare module 'react-styled-flexboxgrid/dist/styled-flexboxgrid.min.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/dist/styled-flexboxgrid.min'>;
}
declare module 'react-styled-flexboxgrid/karma.conf.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/karma.conf'>;
}
declare module 'react-styled-flexboxgrid/lib/components/Col.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/components/Col'>;
}
declare module 'react-styled-flexboxgrid/lib/components/Col.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/components/Col.test'>;
}
declare module 'react-styled-flexboxgrid/lib/components/Grid.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/components/Grid'>;
}
declare module 'react-styled-flexboxgrid/lib/components/Grid.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/components/Grid.test'>;
}
declare module 'react-styled-flexboxgrid/lib/components/Row.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/components/Row'>;
}
declare module 'react-styled-flexboxgrid/lib/components/Row.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/components/Row.test'>;
}
declare module 'react-styled-flexboxgrid/lib/config.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/config'>;
}
declare module 'react-styled-flexboxgrid/lib/config.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/config.test'>;
}
declare module 'react-styled-flexboxgrid/lib/index.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/index'>;
}
declare module 'react-styled-flexboxgrid/lib/index.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/lib/index.test'>;
}
declare module 'react-styled-flexboxgrid/src/components/Col.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/components/Col'>;
}
declare module 'react-styled-flexboxgrid/src/components/Col.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/components/Col.test'>;
}
declare module 'react-styled-flexboxgrid/src/components/Grid.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/components/Grid'>;
}
declare module 'react-styled-flexboxgrid/src/components/Grid.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/components/Grid.test'>;
}
declare module 'react-styled-flexboxgrid/src/components/Row.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/components/Row'>;
}
declare module 'react-styled-flexboxgrid/src/components/Row.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/components/Row.test'>;
}
declare module 'react-styled-flexboxgrid/src/config.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/config'>;
}
declare module 'react-styled-flexboxgrid/src/config.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/config.test'>;
}
declare module 'react-styled-flexboxgrid/src/index.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/index'>;
}
declare module 'react-styled-flexboxgrid/src/index.test.js' {
  declare module.exports: $Exports<'react-styled-flexboxgrid/src/index.test'>;
}
