// flow-typed signature: bb232e5e80c084c2bd767812d595599f
// flow-typed version: <<STUB>>/react-native-git-upgrade_v^0.2.7/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-git-upgrade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-git-upgrade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-git-upgrade/checks' {
  declare module.exports: any;
}

declare module 'react-native-git-upgrade/cli' {
  declare module.exports: any;
}

declare module 'react-native-git-upgrade/cliEntry' {
  declare module.exports: any;
}

declare module 'react-native-git-upgrade/yarn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-git-upgrade/checks.js' {
  declare module.exports: $Exports<'react-native-git-upgrade/checks'>;
}
declare module 'react-native-git-upgrade/cli.js' {
  declare module.exports: $Exports<'react-native-git-upgrade/cli'>;
}
declare module 'react-native-git-upgrade/cliEntry.js' {
  declare module.exports: $Exports<'react-native-git-upgrade/cliEntry'>;
}
declare module 'react-native-git-upgrade/index' {
  declare module.exports: $Exports<'react-native-git-upgrade'>;
}
declare module 'react-native-git-upgrade/index.js' {
  declare module.exports: $Exports<'react-native-git-upgrade'>;
}
declare module 'react-native-git-upgrade/yarn.js' {
  declare module.exports: $Exports<'react-native-git-upgrade/yarn'>;
}
