// flow-typed signature: a37e97e52a395c7c12b771c0f7ecbb9e
// flow-typed version: <<STUB>>/react-highlighter_v^0.4.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-highlighter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-highlighter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-highlighter/dist/ReactHighlighter-v0.4.0' {
  declare module.exports: any;
}

declare module 'react-highlighter/dist/ReactHighlighter-v0.4.0.min' {
  declare module.exports: any;
}

declare module 'react-highlighter/lib/highlighter' {
  declare module.exports: any;
}

declare module 'react-highlighter/lib/regExpPropType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-highlighter/dist/ReactHighlighter-v0.4.0.js' {
  declare module.exports: $Exports<'react-highlighter/dist/ReactHighlighter-v0.4.0'>;
}
declare module 'react-highlighter/dist/ReactHighlighter-v0.4.0.min.js' {
  declare module.exports: $Exports<'react-highlighter/dist/ReactHighlighter-v0.4.0.min'>;
}
declare module 'react-highlighter/lib/highlighter.js' {
  declare module.exports: $Exports<'react-highlighter/lib/highlighter'>;
}
declare module 'react-highlighter/lib/regExpPropType.js' {
  declare module.exports: $Exports<'react-highlighter/lib/regExpPropType'>;
}
