// flow-typed signature: 311133eede21328c57d8046d153fa95c
// flow-typed version: <<STUB>>/react-native-view-pdf_v^0.8.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-view-pdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-view-pdf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-view-pdf/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-view-pdf/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-view-pdf/lib/RNPDFView' {
  declare module.exports: any;
}

declare module 'react-native-view-pdf/src/index' {
  declare module.exports: any;
}

declare module 'react-native-view-pdf/src/RNPDFView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-view-pdf/babel.config.js' {
  declare module.exports: $Exports<'react-native-view-pdf/babel.config'>;
}
declare module 'react-native-view-pdf/lib/index.js' {
  declare module.exports: $Exports<'react-native-view-pdf/lib/index'>;
}
declare module 'react-native-view-pdf/lib/RNPDFView.js' {
  declare module.exports: $Exports<'react-native-view-pdf/lib/RNPDFView'>;
}
declare module 'react-native-view-pdf/src/index.js' {
  declare module.exports: $Exports<'react-native-view-pdf/src/index'>;
}
declare module 'react-native-view-pdf/src/RNPDFView.js' {
  declare module.exports: $Exports<'react-native-view-pdf/src/RNPDFView'>;
}
