// flow-typed signature: d5c8ff9f4c6b1f54563b1cc5cc4e60e8
// flow-typed version: <<STUB>>/redux-responsive_v^4.3.8/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-responsive/index.min' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/actions/creators/calculateResponsiveState' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/actions/creators/calculateResponsiveState.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/actions/creators/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/actions/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/actions/types/CALCULATE_RESPONSIVE_STATE' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/actions/types/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/react/components/stylesheet' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/react/components/stylesheet.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/react/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/createEnhancer' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/createEnhancer.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/createReducer' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/createReducer.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/getBreakpoints' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/getBreakpoints.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/handlers' {
  declare module.exports: any;
}

declare module 'redux-responsive/lib/util/handlers.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/react' {
  declare module.exports: any;
}

declare module 'redux-responsive/react.min' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/actions/creators/calculateResponsiveState' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/actions/creators/calculateResponsiveState.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/actions/creators/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/actions/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/actions/types/CALCULATE_RESPONSIVE_STATE' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/actions/types/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/react/components/stylesheet' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/react/components/stylesheet.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/react/index' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/createEnhancer' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/createEnhancer.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/createReducer' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/createReducer.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/getBreakpoints' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/getBreakpoints.test' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/handlers' {
  declare module.exports: any;
}

declare module 'redux-responsive/src/util/handlers.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-responsive/index' {
  declare module.exports: $Exports<'redux-responsive'>;
}
declare module 'redux-responsive/index.js' {
  declare module.exports: $Exports<'redux-responsive'>;
}
declare module 'redux-responsive/index.min.js' {
  declare module.exports: $Exports<'redux-responsive/index.min'>;
}
declare module 'redux-responsive/lib/actions/creators/calculateResponsiveState.js' {
  declare module.exports: $Exports<'redux-responsive/lib/actions/creators/calculateResponsiveState'>;
}
declare module 'redux-responsive/lib/actions/creators/calculateResponsiveState.test.js' {
  declare module.exports: $Exports<'redux-responsive/lib/actions/creators/calculateResponsiveState.test'>;
}
declare module 'redux-responsive/lib/actions/creators/index.js' {
  declare module.exports: $Exports<'redux-responsive/lib/actions/creators/index'>;
}
declare module 'redux-responsive/lib/actions/index.js' {
  declare module.exports: $Exports<'redux-responsive/lib/actions/index'>;
}
declare module 'redux-responsive/lib/actions/types/CALCULATE_RESPONSIVE_STATE.js' {
  declare module.exports: $Exports<'redux-responsive/lib/actions/types/CALCULATE_RESPONSIVE_STATE'>;
}
declare module 'redux-responsive/lib/actions/types/index.js' {
  declare module.exports: $Exports<'redux-responsive/lib/actions/types/index'>;
}
declare module 'redux-responsive/lib/index.js' {
  declare module.exports: $Exports<'redux-responsive/lib/index'>;
}
declare module 'redux-responsive/lib/react/components/stylesheet.js' {
  declare module.exports: $Exports<'redux-responsive/lib/react/components/stylesheet'>;
}
declare module 'redux-responsive/lib/react/components/stylesheet.test.js' {
  declare module.exports: $Exports<'redux-responsive/lib/react/components/stylesheet.test'>;
}
declare module 'redux-responsive/lib/react/index.js' {
  declare module.exports: $Exports<'redux-responsive/lib/react/index'>;
}
declare module 'redux-responsive/lib/util/createEnhancer.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/createEnhancer'>;
}
declare module 'redux-responsive/lib/util/createEnhancer.test.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/createEnhancer.test'>;
}
declare module 'redux-responsive/lib/util/createReducer.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/createReducer'>;
}
declare module 'redux-responsive/lib/util/createReducer.test.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/createReducer.test'>;
}
declare module 'redux-responsive/lib/util/getBreakpoints.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/getBreakpoints'>;
}
declare module 'redux-responsive/lib/util/getBreakpoints.test.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/getBreakpoints.test'>;
}
declare module 'redux-responsive/lib/util/handlers.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/handlers'>;
}
declare module 'redux-responsive/lib/util/handlers.test.js' {
  declare module.exports: $Exports<'redux-responsive/lib/util/handlers.test'>;
}
declare module 'redux-responsive/react.js' {
  declare module.exports: $Exports<'redux-responsive/react'>;
}
declare module 'redux-responsive/react.min.js' {
  declare module.exports: $Exports<'redux-responsive/react.min'>;
}
declare module 'redux-responsive/src/actions/creators/calculateResponsiveState.js' {
  declare module.exports: $Exports<'redux-responsive/src/actions/creators/calculateResponsiveState'>;
}
declare module 'redux-responsive/src/actions/creators/calculateResponsiveState.test.js' {
  declare module.exports: $Exports<'redux-responsive/src/actions/creators/calculateResponsiveState.test'>;
}
declare module 'redux-responsive/src/actions/creators/index.js' {
  declare module.exports: $Exports<'redux-responsive/src/actions/creators/index'>;
}
declare module 'redux-responsive/src/actions/index.js' {
  declare module.exports: $Exports<'redux-responsive/src/actions/index'>;
}
declare module 'redux-responsive/src/actions/types/CALCULATE_RESPONSIVE_STATE.js' {
  declare module.exports: $Exports<'redux-responsive/src/actions/types/CALCULATE_RESPONSIVE_STATE'>;
}
declare module 'redux-responsive/src/actions/types/index.js' {
  declare module.exports: $Exports<'redux-responsive/src/actions/types/index'>;
}
declare module 'redux-responsive/src/index.js' {
  declare module.exports: $Exports<'redux-responsive/src/index'>;
}
declare module 'redux-responsive/src/react/components/stylesheet.js' {
  declare module.exports: $Exports<'redux-responsive/src/react/components/stylesheet'>;
}
declare module 'redux-responsive/src/react/components/stylesheet.test.js' {
  declare module.exports: $Exports<'redux-responsive/src/react/components/stylesheet.test'>;
}
declare module 'redux-responsive/src/react/index.js' {
  declare module.exports: $Exports<'redux-responsive/src/react/index'>;
}
declare module 'redux-responsive/src/util/createEnhancer.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/createEnhancer'>;
}
declare module 'redux-responsive/src/util/createEnhancer.test.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/createEnhancer.test'>;
}
declare module 'redux-responsive/src/util/createReducer.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/createReducer'>;
}
declare module 'redux-responsive/src/util/createReducer.test.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/createReducer.test'>;
}
declare module 'redux-responsive/src/util/getBreakpoints.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/getBreakpoints'>;
}
declare module 'redux-responsive/src/util/getBreakpoints.test.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/getBreakpoints.test'>;
}
declare module 'redux-responsive/src/util/handlers.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/handlers'>;
}
declare module 'redux-responsive/src/util/handlers.test.js' {
  declare module.exports: $Exports<'redux-responsive/src/util/handlers.test'>;
}
