// flow-typed signature: 2be108732897b5e24fa2638956278802
// flow-typed version: <<STUB>>/sanitize-html-react_v^1.13.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize-html-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize-html-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sanitize-html-react/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sanitize-html-react/index' {
  declare module.exports: $Exports<'sanitize-html-react'>;
}
declare module 'sanitize-html-react/index.js' {
  declare module.exports: $Exports<'sanitize-html-react'>;
}
declare module 'sanitize-html-react/test/test.js' {
  declare module.exports: $Exports<'sanitize-html-react/test/test'>;
}
