// flow-typed signature: 0d757b06f4b978c237269e88cc508a61
// flow-typed version: <<STUB>>/@react-native-firebase/messaging_v11.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-firebase/messaging'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-firebase/messaging' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-firebase/messaging/lib' {
  declare module.exports: any;
}

declare module '@react-native-firebase/messaging/lib/remoteMessageOptions' {
  declare module.exports: any;
}

declare module '@react-native-firebase/messaging/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-firebase/messaging/lib/index' {
  declare module.exports: $Exports<'@react-native-firebase/messaging/lib'>;
}
declare module '@react-native-firebase/messaging/lib/index.js' {
  declare module.exports: $Exports<'@react-native-firebase/messaging/lib'>;
}
declare module '@react-native-firebase/messaging/lib/remoteMessageOptions.js' {
  declare module.exports: $Exports<'@react-native-firebase/messaging/lib/remoteMessageOptions'>;
}
declare module '@react-native-firebase/messaging/lib/version.js' {
  declare module.exports: $Exports<'@react-native-firebase/messaging/lib/version'>;
}
