require_relative "util"

# The following parameters have to be passed:
# path: The path of the artifact (apk or ipa) to upload (relative to home dir)
# [Optional] automate: Set this to true to upload to browserstack automate for e2e tests instead of browserstack live
desc "Upload the app to browserstack"
lane :browserstack_upload do |options|
  ensure_env_vars(env_vars: ["BROWSERSTACK_USERNAME", "BROWSERSTACK_ACCESS_KEY"])

  path = options[:path]
  automate = options[:e2e_tests]

  assert_parameters([path])

  if automate
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "#{ENV['HOME']}/#{path}"
    )
  else
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "#{ENV['HOME']}/#{path}"
    )
  end
end

# The following parameters have to be passed:
# path: The path of the artifact (apk or ipa) to upload (relative to home dir)
# platform: 'android' or 'ios'
desc "Upload the app to browserstack and run e2e tests"
lane :e2e_tests do |options|
  path = options[:path]
  platform = options[:platform]

  assert_parameters([path, platform])

  browserstack_upload(path: path, automate: true)

  ENV["E2E_CONFIG"] = platform
  ENV["E2E_BROWSERSTACK_USER"] = ENV["BROWSERSTACK_USERNAME"]
  ENV["E2E_BROWSERSTACK_KEY"] = ENV["BROWSERSTACK_ACCESS_KEY"]
  ENV["E2E_BROWSERSTACK_APP"] = lane_context[SharedValues::BROWSERSTACK_APP_ID]

  `yarn test:e2e`
end
