import {
  CATEGORIES_PAGE_ROUTE, DISCLAIMER_PAGE_ROUTE, EVENTS_PAGE_ROUTE, EXTRAS_PAGE_ROUTE, LANDING_PAGE_ROUTE,
  MAIN_DISCLAIMER_PAGE_ROUTE, PDF_FETCHER_PAGE_ROUTE, SEARCH_PAGE_ROUTE
} from '../common/constants'

const createRouteConfig = () => {
  return [
    LANDING_PAGE_ROUTE,
    SEARCH_PAGE_ROUTE,
    DISCLAIMER_PAGE_ROUTE,
    EVENTS_PAGE_ROUTE,
    PDF_FETCHER_PAGE_ROUTE,
    EXTRAS_PAGE_ROUTE,
    CATEGORIES_PAGE_ROUTE,
    MAIN_DISCLAIMER_PAGE_ROUTE
  ]
}

export default createRouteConfig
