// flow-typed signature: e3de3fbc2fd2b297dca0208806b020dc
// flow-typed version: <<STUB>>/@react-native-community/progress-view_v1.2.4/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/progress-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/progress-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/progress-view/js/__tests__/ProgressViewIOS.ios.test' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-view/js' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-view/js/ProgressView.android' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-view/js/ProgressView.ios' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-view/js/ProgressView.macos' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-view/js/ProgressView.windows' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-view/js/RNCProgressViewNativeComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/progress-view/js/__tests__/ProgressViewIOS.ios.test.js' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js/__tests__/ProgressViewIOS.ios.test'>;
}
declare module '@react-native-community/progress-view/js/index' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js'>;
}
declare module '@react-native-community/progress-view/js/index.js' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js'>;
}
declare module '@react-native-community/progress-view/js/ProgressView.android.js' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js/ProgressView.android'>;
}
declare module '@react-native-community/progress-view/js/ProgressView.ios.js' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js/ProgressView.ios'>;
}
declare module '@react-native-community/progress-view/js/ProgressView.macos.js' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js/ProgressView.macos'>;
}
declare module '@react-native-community/progress-view/js/ProgressView.windows.js' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js/ProgressView.windows'>;
}
declare module '@react-native-community/progress-view/js/RNCProgressViewNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-community/progress-view/js/RNCProgressViewNativeComponent'>;
}
