// flow-typed signature: 77b8592eb7b0ea9cb900e3939be788c6
// flow-typed version: <<STUB>>/@react-native-community/progress-bar-android_v1.0.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/progress-bar-android'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/progress-bar-android' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/progress-bar-android/js/__tests__/RNCProgressBarAndroid.android.test' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-bar-android/js/RNCProgressBarAndroid.android' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-bar-android/js/RNCProgressBarAndroid.ios' {
  declare module.exports: any;
}

declare module '@react-native-community/progress-bar-android/js/RNCProgressBarAndroidNativeComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/progress-bar-android/index' {
  declare module.exports: $Exports<'@react-native-community/progress-bar-android'>;
}
declare module '@react-native-community/progress-bar-android/index.js' {
  declare module.exports: $Exports<'@react-native-community/progress-bar-android'>;
}
declare module '@react-native-community/progress-bar-android/js/__tests__/RNCProgressBarAndroid.android.test.js' {
  declare module.exports: $Exports<'@react-native-community/progress-bar-android/js/__tests__/RNCProgressBarAndroid.android.test'>;
}
declare module '@react-native-community/progress-bar-android/js/RNCProgressBarAndroid.android.js' {
  declare module.exports: $Exports<'@react-native-community/progress-bar-android/js/RNCProgressBarAndroid.android'>;
}
declare module '@react-native-community/progress-bar-android/js/RNCProgressBarAndroid.ios.js' {
  declare module.exports: $Exports<'@react-native-community/progress-bar-android/js/RNCProgressBarAndroid.ios'>;
}
declare module '@react-native-community/progress-bar-android/js/RNCProgressBarAndroidNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-community/progress-bar-android/js/RNCProgressBarAndroidNativeComponent'>;
}
