// flow-typed signature: 193d25a8bf735d942958fc4ab5e64630
// flow-typed version: <<STUB>>/@integreat-app/eslint-config-react_v^0.2.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@integreat-app/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@integreat-app/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@integreat-app/eslint-config-react/index' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-react'>;
}
declare module '@integreat-app/eslint-config-react/index.js' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-react'>;
}
