// flow-typed signature: fd960afb4075f3563d1fce183d6b31ed
// flow-typed version: <<STUB>>/@integreat-app/eslint-config-jest_v^0.2.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@integreat-app/eslint-config-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@integreat-app/eslint-config-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@integreat-app/eslint-config-jest/index' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-jest'>;
}
declare module '@integreat-app/eslint-config-jest/index.js' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-jest'>;
}
