// flow-typed signature: 998a37de3226672797f76cd8b5222073
// flow-typed version: <<STUB>>/@integreat-app/eslint-config-react_v^0.3.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@integreat-app/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@integreat-app/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@integreat-app/eslint-config-react/index' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-react'>;
}
declare module '@integreat-app/eslint-config-react/index.js' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-react'>;
}
