// flow-typed signature: 745678d42f659318cc396278553812ba
// flow-typed version: <<STUB>>/@integreat-app/eslint-config-flow_v^0.3.2/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@integreat-app/eslint-config-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@integreat-app/eslint-config-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@integreat-app/eslint-config-flow/index' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-flow'>;
}
declare module '@integreat-app/eslint-config-flow/index.js' {
  declare module.exports: $Exports<'@integreat-app/eslint-config-flow'>;
}
