when:
  and:
    - equal: [3231-design-system-web, << pipeline.git.branch >>]
    - not: << pipeline.parameters.api_triggered >>
jobs:
  - bump_version:
      prepare_delivery: false
  - build_web:
      build_config_name: integreat-test-cms
      requires:
        - bump_version
  - deliver_web:
      delivery: future
      requires:
        - build_web
