unless:
  equal: [main, << pipeline.git.branch >>]
jobs:
  - bump_version:
      prepare_delivery: true
      context:
        - deliverino
  - notify_release:
      production_delivery: false
      context:
        - deliverino
      requires:
        - bump_version
