when:
  or:
    - and:
        - << pipeline.parameters.api_triggered >>
        - equal: [<< pipeline.parameters.workflow_type >>, e2e_tests]
    - and:
        - equal: [main, << pipeline.git.branch >>]
        - not: << pipeline.parameters.api_triggered >>
jobs:
  - bump_version:
      prepare_delivery: false
      context:
        - mattermost
  - build_web:
      name: build_ig_test_cms_web
      build_config_name: integreat-test-cms
      requires:
        - bump_version
      context:
        - mattermost
  - e2e_web:
      context:
        - mattermost

  - build_android:
      name: build_e2e_android
      build_config_name: integreat-e2e
      requires:
        - bump_version
      context:
        - credentials-repo
        - credentials-integreat
        - mattermost
  - e2e_android:
      context:
        - browserstack
        - mattermost
      requires:
        - build_e2e_android

  - build_ios:
      name: build_e2e_ios
      build_config_name: integreat-e2e
      requires:
        - bump_version
      context:
        - tuerantuer-apple
        - fastlane-match
        - mattermost
  - e2e_ios:
      context:
        - browserstack
        - mattermost
      requires:
        - build_e2e_ios
