unless:
    - << pipeline.parameters.api_triggered >>
jobs:
  - native_prepare_build
  - native_build_android:
      build_for_delivery: false
      requires:
        - native_prepare_build
  - native_build_ios:
      build_for_delivery: false
      requires:
        - native_prepare_build
  - native_e2e:
      requires:
        - native_build_ios
        - native_build_android
