when:
  and:
    - << pipeline.parameters.api_triggered >>
    - equal: [ native, << pipeline.parameters.project >> ]
jobs:
  - native_prepare_build
  - native_build_android:
      build_for_delivery: true
      requires:
        - native_prepare_build
  - native_build_ios:
      build_for_delivery: true
      requires:
        - native_prepare_build
  - native_e2e:
      requires:
        - native_build_ios
        - native_build_android
  - native_prepare_delivery:
      production_delivery: << pipeline.parameters.production_delivery >>
      requires: # Prepare delivery (including bump version) should only depend on build_ and not delivery_. Sometimes upload to the stores fails only for iOS or Android. Then we still should bump the version.
        - native_e2e
  - native_deliver_android:
      production_delivery: << pipeline.parameters.production_delivery >>
      requires:
        - native_prepare_delivery
  - native_deliver_ios:
      production_delivery: << pipeline.parameters.production_delivery >>
      requires:
        - native_prepare_delivery
