when:
  and:
    - << pipeline.parameters.api_triggered >>
    - equal: [<< pipeline.parameters.workflow_type >>, native_browserstack]
jobs:
  - bump_version:
      context:
        - mattermost
      prepare_delivery: false

  - build_android:
      name: build_ig_test_cms_android
      build_config_name: integreat-test-cms
      context:
        - mattermost
        - credentials-repo
        - credentials-integreat
      requires:
        - bump_version
  - upload_browserstack:
      name: upload_ig_test_cms_android_browserstack
      file_name: integreat-test-cms.apk
      context:
        - mattermost
        - browserstack
      requires:
        - build_ig_test_cms_android

  - build_ios:
      name: build_ig_test_cms_ios
      build_config_name: integreat-test-cms
      context:
        - mattermost
        - tuerantuer-apple
        - fastlane-match
      requires:
        - bump_version
  - upload_browserstack:
      name: upload_ig_test_cms_ios_browserstack
      file_name: integreat-test-cms.ipa
      context:
        - mattermost
        - browserstack
      requires:
        - build_ig_test_cms_ios
