triggers:
  - schedule:
      cron: "0 5 1,15 * *" # For sanity checks for this syntax: https://crontab.guru/
      filters:
        branches:
          only:
            - main
jobs:
  - web_build
  - web_prepare_delivery:
      production_delivery: true
      requires:
        - web_build
  - await_approval:
      type: approval
      requires:
        - web_prepare_delivery
  - web_deliver:
      production_delivery: true
      requires:
        - await_approval

  - native_prepare_build
  - native_build_android:
      build_for_delivery: true
      requires:
        - native_prepare_build
  - native_build_ios:
      build_for_delivery: true
      requires:
        - native_prepare_build
  - native_e2e:
      requires:
        - native_build_ios
        - native_build_android
  - native_prepare_delivery:
      production_delivery: true
      requires: # Bump version should only depend on build_ and not delivery_. Sometimes upload to the stores fails only for iOS or Android. Then we should still bump the version.
        - native_e2e
  - await_production_approval:
      type: approval
      requires:
        - native_prepare_delivery
  - native_deliver_android:
      production_delivery: true
      requires:
        - await_production_approval
  - native_deliver_ios:
      production_delivery: true
      requires:
        - await_production_approval
