triggers:
  - schedule:
      cron: "0 5 1,15 * *" # For sanity checks for this syntax: https://crontab.guru/
      filters:
        branches:
          only:
            - main
jobs:
  - bump_version:
      context:
        - slack-app
        - deliverino
        - jira
      delivery: production

  - check_web:
      context:
        - slack-app
      requires:
        - bump_version
  - build_production_web:
      context:
        - slack-app
      requires:
        - bump_version
  - deliver_web:
      context:
        - slack-app
      production_delivery: true
      requires:
        - check_web
        - build_production_web
  - notify_web:
      context:
        - slack-app
        - deliverino
      requires:
        - deliver_web

  - check_native:
      context:
        - slack-app
      requires:
        - bump_version

  - build_e2e_android:
      context:
        - slack-app
        - tuerantuer-google-play
        - tuerantuer-android
      requires:
        - bump_version
  - e2e_android:
      context:
        - slack-app
        - browserstack
      requires:
        - build_e2e_android
  - build_production_android:
      context:
        - slack-app
        - tuerantuer-google-play
        - tuerantuer-android
      requires:
        - bump_version
  - deliver_android:
      context:
        - slack-app
        - sentry
        - browserstack
        - tuerantuer-google-play
        - tuerantuer-android
      production_delivery: true
      requires:
        - check_native
        - e2e_android
        - build_production_android
  - notify_android:
      context:
        - slack-app
        - deliverino
      production_delivery: true
      requires:
        - deliver_android

  - build_e2e_ios:
      context:
        - slack-app
        - tuerantuer-apple
        - tuerantuer-ios
      requires:
        - bump_version
  - e2e_ios:
      context:
        - slack-app
        - browserstack
      requires:
        - build_e2e_ios
  - build_production_ios:
      context:
        - slack-app
        - tuerantuer-apple
        - tuerantuer-ios
      requires:
        - bump_version
  - deliver_ios:
      context:
        - slack-app
        - sentry
        - browserstack
        - tuerantuer-apple
        - tuerantuer-ios
      production_delivery: true
      requires:
        - check_native
        - e2e_ios
        - build_production_ios
  - notify_ios:
      context:
        - slack-app
        - deliverino
      production_delivery: true
      requires:
        - deliver_ios

  - move_release_notes:
      context:
        - slack-app
        - deliverino
      requires:
        - notify_web
        - notify_android
        - notify_ios
