triggers:
  - schedule:
      cron: "0 5 1,15 * *" # For sanity checks for this syntax: https://crontab.guru/
      filters:
        branches:
          only:
            - main
jobs:
  - web_build
  - web_prepare_production_delivery:
      requires:
        - web_build
  - await_approval:
      type: approval
      requires:
        - web_prepare_production_delivery
  - web_deliver:
      production_delivery: true
      requires:
        - await_approval