unless:
    - << pipeline.parameters.api_triggered >>
jobs:
  - web_build
  - web_deliver:
      filters:
        branches:
          only:
            - main
      production_delivery: false
      requires:
        - web_build