when:
  and:
    - not: << pipeline.parameters.api_triggered >>
    - equal: [ web, << pipeline.parameters.project >> ]
jobs:
  - web_build
  - web_deliver:
      filters:
        branches:
          only:
            - main
      production_delivery: false
      requires:
        - web_build