when:
  and:
    - << pipeline.parameters.api_triggered >>
    - equal: [<< pipeline.parameters.workflow_type >>, web_beta_delivery]
jobs:
  - bump_version:
      prepare_delivery: true
      platform: web
      context:
        - deliverino
  - check
  - e2e_web:
      requires:
        - bump_version
  - build_web:
      matrix:
        parameters:
          build_config_name: [integreat, malte, aschaffenburg, obdach]
      requires:
        - bump_version
  - deliver_web:
      delivery: beta
      context:
        - sentry
      requires:
        - check
        - e2e_web
        - build_web
  - notify_release:
      production_delivery: false
      platform: web
      context:
        - deliverino
      requires:
        - deliver_web
