when:
  and:
    - << pipeline.parameters.api_triggered >>
    - not: << pipeline.parameters.production_delivery >>
    - equal: [ web, << pipeline.parameters.project >> ]
jobs:
  - web_build
  - web_deliver:
      production_delivery: false
      requires:
        - web_build
