version: 2.1

orbs:
  slack: circleci/slack@3.4.2

parameters:
  api_triggered:
    type: boolean
    description: Whether the pipeline was triggered through the CircleCi API (https://circleci.com/docs/api/v2/?shell#trigger-a-new-pipeline).
    default: false
  production_delivery:
    type: boolean
    description: Whether to deliver to production or not (beta channel and testflight).
    default: false

workflows:
  version: 2
  commit:
    unless: << pipeline.parameters.api_triggered >>
    jobs:
      - prepare_build
      - build_android:
          build_for_delivery: false
          requires:
            - prepare_build
      - build_ios:
          build_for_delivery: false
          requires:
            - prepare_build
      - e2e:
          requires:
            - build_ios
            - build_android

  api_triggered_delivery:
    when: << pipeline.parameters.api_triggered >>
    jobs:
      - prepare_build
      - build_android:
          build_for_delivery: true
          requires:
            - prepare_build
      - build_ios:
          build_for_delivery: true
          requires:
            - prepare_build
      - e2e:
          requires:
            - build_ios
            - build_android
      - prepare_delivery:
          production_delivery: << pipeline.parameters.production_delivery >>
          requires: # Prepare delivery (including bump version) should only depend on build_ and not delivery_. Sometimes upload to the stores fails only for iOS or Android. Then we still should bump the version.
            - e2e
      - deliver_android:
          production_delivery: << pipeline.parameters.production_delivery >>
          requires:
            - prepare_delivery
      - deliver_ios:
          production_delivery: << pipeline.parameters.production_delivery >>
          requires:
            - prepare_delivery

  bi_weekly_development_delivery:
    triggers:
      - schedule:
          cron: "0 3 8,22 * *" # For sanity checks for this syntax: https://crontab.guru/
          filters:
            branches:
              only:
                - develop
    jobs:
      - prepare_build
      - build_android:
          build_for_delivery: true
          requires:
            - prepare_build
      - build_ios:
          build_for_delivery: true
          requires:
            - prepare_build
      - e2e:
          requires:
            - build_ios
            - build_android
      - prepare_delivery:
          production_delivery: << pipeline.parameters.production_delivery >>
          requires: # Bump version should only depend on build_ and not delivery_. Sometimes upload to the stores fails only for iOS or Android. Then we still should bump the version.
            - e2e
      - deliver_android:
          production_delivery: false
          requires:
            - prepare_delivery
      - deliver_ios:
          production_delivery: false
          requires:
            - prepare_delivery

  bi_weekly_production_delivery:
    triggers:
      - schedule:
          cron: "0 3 1,15 * *" # For sanity checks for this syntax: https://crontab.guru/
          filters:
            branches:
              only:
                - develop
    jobs:
      - prepare_build
      - build_android:
          build_for_delivery: true
          requires:
            - prepare_build
      - build_ios:
          build_for_delivery: true
          requires:
            - prepare_build
      - e2e:
          requires:
            - build_ios
            - build_android
      - prepare_delivery:
          production_delivery: << pipeline.parameters.production_delivery >>
          requires: # Bump version should only depend on build_ and not delivery_. Sometimes upload to the stores fails only for iOS or Android. Then we should still bump the version.
            - e2e
      - await_production_approval:
          type: approval
          requires:
            - prepare_delivery
      - deliver_android:
          production_delivery: true
          requires:
            - await_production_approval
      - deliver_ios:
          production_delivery: true
          requires:
            - await_production_approval
