version: 2.1

orbs:
  slack: circleci/slack@3.4.2

parameters:
  api_triggered:
    type: boolean
    description: Whether the pipeline was triggered through the CircleCi API (https://circleci.com/docs/api/v2/?shell#trigger-a-new-pipeline).
    default: false
  production_delivery:
    type: boolean
    description: Whether to deliver to production (integreat.app and malteapp.de) or not (webnext.integreat-app.de and webnext.malteapp.de).
    default: false

workflows:
  version: 2
  commit: # Builds every commit. Delivers to webnext.integreat.app and webnext.malteapp.de on develop.
    unless: << pipeline.parameters.api_triggered >>
    jobs:
      - build
      - deliver:
          filters:
            branches:
              only:
                - develop
          production_delivery: false
          requires:
            - build

  api_triggered_production_delivery: # Workflow for manual delivery to integreat.app and malteapp.de which also bumps the version, moves the release notes, ...
    when:
      and:
        - << pipeline.parameters.api_triggered >>
        - << pipeline.parameters.production_delivery >>
    jobs:
      - build
      - prepare_production_delivery:
          requires:
            - build
      - deliver:
          production_delivery: true
          requires:
            - prepare_production_delivery

  api_triggered_development_delivery: # Workflow for manual delivery to webnext.integreat.app and webnext.malteapp.de
    when:
      and:
        - << pipeline.parameters.api_triggered >>
        - not: << pipeline.parameters.production_delivery >>
    jobs:
      - build
      - deliver:
          production_delivery: false
          requires:
            - build

  bi_weekly_prduction_delivery:
    triggers:
      - schedule:
          cron: "0 5 1,15 * *" # For sanity checks for this syntax: https://crontab.guru/
          filters:
            branches:
              only:
                - develop
    jobs:
      - build
      - prepare_production_delivery:
          requires:
            - build
      - await_approval:
          type: approval
          requires:
            - prepare_production_delivery
      - deliver:
          production_delivery: true
          requires:
            - await_approval
