export { faSearch } from '@fortawesome/free-solid-svg-icons/faSearch'
export { faFrown } from '@fortawesome/free-regular-svg-icons/faFrown'
export { faSmile } from '@fortawesome/free-regular-svg-icons/faSmile'
export { faTimes } from '@fortawesome/free-solid-svg-icons/faTimes'
export { faAngleDown } from '@fortawesome/free-solid-svg-icons/faAngleDown'
export { faAngleUp } from '@fortawesome/free-solid-svg-icons/faAngleUp'
export { faArrowLeft } from '@fortawesome/free-solid-svg-icons/faArrowLeft'
export { faChevronLeft } from '@fortawesome/free-solid-svg-icons/faChevronLeft'
