macos:
  xcode: 11.7.0
resource_class: large
environment:
  FL_OUTPUT_DIR: output
  FASTLANE_SKIP_UPDATE_CHECK: true
  TOTAL_CPUS: 4 # For mac with resource_class medium, used in metro.config.ci.js. # TODO change
shell: /bin/bash --login -o pipefail
steps:
  - add_ssh_keys: # Needed for credentials repo
      fingerprints:
        - "61:d8:94:00:53:5f:3b:19:fd:88:6b:fa:cd:ca:df:5d"
  - checkout
  - attach_workspace:
      at: .
  - restore_environment_variables
  - restore_yarn_cache
  - restore_ruby_cache:
      directory: native/ios
  - restore_cache:
      name: Restore CocoaPods Cache
      keys:
        - 2-pods-{{ arch }}-{{ checksum "native/ios/Podfile.lock" }}
        - 2-pods-{{ arch }}-
  - run:
      name: "[CP] Install CocoaPods"
      command: bundle exec pod install --deployment
      working_directory: native/ios
  - save_cache:
      name: Save CocoaPods Cache
      key: 2-pods-{{ arch }}-{{ checksum "native/ios/Podfile.lock" }}
      paths:
        - ~/Library/Caches/CocoaPods/
  - run:
      name: "[FL] integreat-e2e build"
      command: bundle exec fastlane build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE} build_config_name:integreat-e2e
      working_directory: native/ios
  - store_artifacts:
      path: native/ios/output/gym/
  - persist_to_workspace:
      root: native/ios/output/gym
      paths:
        - integreat-e2e.ipa
  - notify_failed
