docker:
  - image: circleci/android:api-29-node
resource_class: medium
environment:
  TOTAL_CPUS: 2 # For resource_class medium, used in metro.config.ci.js.
  FASTLANE_SKIP_UPDATE_CHECK: true
shell: /bin/bash -eo pipefail
steps:
  - add_ssh_keys: # Needed for credentials repo
      fingerprints:
        - "61:d8:94:00:53:5f:3b:19:fd:88:6b:fa:cd:ca:df:5d"
  - checkout
  - attach_workspace:
      at: .
  - restore_environment_variables
  - restore_cache:
      keys:
        - 2-gems-{{ arch }}-{{ checksum "native/android/Gemfile.lock" }}
        - 2-gems-{{ arch }}-
  - run:
      command: bundle config set path 'vendor/bundle'
      working_directory: native/android
  - run:
      command: bundle check || bundle install
      working_directory: native/android
  - save_cache:
      key: 2-gems-{{ arch }}-{{ checksum "native/android/Gemfile.lock" }}
      paths:
        - native/android/vendor/bundle
  - restore_gradle_cache
  - restore_yarn_cache
  - run:
      name: "[FL] Prepare Android Keystore"
      command: bundle exec fastlane keystore
      working_directory: native/android
  - run:
      name: "[FL] integreat-e2e build"
      command: ./gradlew clean && bundle exec fastlane build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE} build_config_name:integreat-e2e
      working_directory: native/android
  - run:
      name: Rename apk
      command: mv app/build/outputs/apk/release/app-release.apk integreat-e2e.apk
      working_directory: native/android
  - store_artifacts:
      path: native/android/integreat-e2e.apk
  - persist_to_workspace:
      root: native/android
      paths:
        - integreat-e2e.apk
  - notify_failed
