docker:
  - image: circleci/node:12.16.3
resource_class: small
environment:
  TOTAL_CPUS: 1 # For resource_class small
  TZ: "Europe/Berlin" # Should be removed in IGAPP-39
shell: /bin/bash -eo pipefail
steps:
  - skip_job
  - checkout
  - check_config
  - restore_yarn_cache
  - lint:
      directory: web
  - lint:
      directory: api-client
  - run:
      name: Check flow
      command: yarn workspace web flow:check-now --max-workers ${TOTAL_CPUS}
  - unit_test:
      directory: web
  - unit_test:
      directory: api-client
  - unit_test:
      directory: translations     
  - notify
