docker:
  - image: circleci/android:api-28-node
resource_class: small
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - attach_workspace:
      at: .
  - restore_environment_variables
  - restore_cache:
      keys:
        - 2-gems-{{ arch }}-{{ checksum "Gemfile.lock" }}
        - 2-gems-{{ arch }}-
  - run:
      command: bundle check || bundle install --path vendor/bundle
  - save_cache:
      key: 2-gems-{{ arch }}-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  - restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - 3-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
  - run:
      name: Install Dependencies
      command: yarn install --frozen-lockfile
  - save_cache:
      name: Save Yarn Package Cache
      key: 3-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
        - node_modules
  - run:
      name: "[FL] Android E2E Tests on Browserstack"
      command: bundle exec fastlane android browserstack_e2e_tests app_name:integreat-test-cms
  - run:
      name: "[FL] iOS E2E Tests on Browserstack"
      command: bundle exec fastlane ios browserstack_e2e_tests app_name:integreat-test-cms
