docker:
  - image: circleci/node:12.16.3
resource_class: small
environment:
  TOTAL_CPUS: 1 # For resource_class small
shell: /bin/bash -eo pipefail
steps:
  - checkout
  - check_config
  - restore_cache:
      name: Restore Yarn Package Cache
      keys: # Integer Prefix used for manually invalidating caches by incrementing.
        - 3-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
        - 3-yarn-{{ arch }}-
  - run:
      name: Install Dependencies
      command: yarn install --frozen-lockfile
  - save_cache:
      name: Save Yarn Package Cache
      key: 3-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
        - node_modules
  - run:
      name: Linting check
      command: yarn run lint
  - run:
      name: Flow-type check
      command: yarn run flow:check-now --max-workers ${TOTAL_CPUS}
  - run:
      name: Unit tests
      command: yarn run test --maxWorkers ${TOTAL_CPUS}
  - run:
      name: Calculate next version name
      command: echo "export NEW_VERSION_NAME=$(tools/next-version calc | jq .versionName)" >> environment_variables
  - run:
      name: Calculate next version code
      command: echo "export NEW_VERSION_CODE=$(tools/next-version calc | jq .versionCode)" >> environment_variables
  - persist_to_workspace:
      root: ./
      paths:
        - environment_variables
