docker:
  - image: circleci/node:12.16.3
resource_class: small
environment:
  TOTAL_CPUS: 1 # For resource_class small
  TZ: "Europe/Berlin" # Should be removed in WEBAPP-463
shell: /bin/bash -eo pipefail
steps:
  - run:
      name: "Show current CPU count"
      command: echo "CPU count is ${TOTAL_CPUS}"
  - checkout
  - check_config
  - restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - 2-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
        - 2-yarn-{{ arch }}-
  - run:
      name: Install Dependencies
      command: yarn install --frozen-lockfile
  - save_cache:
      name: Save Yarn Package Cache
      key: 2-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
        - node_modules
  - run:
      name: Check linting
      command: yarn workspace web lint
  - run:
      name: Check flow
      command: yarn workspace web flow:check-now --max-workers ${TOTAL_CPUS}
  - run:
      name: Unit tests
      command: yarn workspace web test --ci --maxWorkers ${TOTAL_CPUS}
  - run:
      name: Test coverage # Results are not used right now. Run it anyway to (possibly) discover more problems.
      command: yarn workspace web test:coverage --ci --maxWorkers ${TOTAL_CPUS}
  - run:
      name: Calculate next version
      command: echo "export NEW_VERSION_NAME=$(tools/next-version calc | jq .versionName)" >> environment_variables
  - run:
      name: Development integreat-test-cms build
      command: yarn workspace web build:integreat-test-cms --env.commit_sha=${CIRCLE_SHA1}
  - run:
      name: Production integreat build
      command: yarn workspace web build:integreat
  - run:
      name: Production malte build
      command: yarn workspace web build:malte
  - run:
      name: Check build
      command: yarn workspace web check:build
  - store_artifacts:
      path: dist
  - persist_to_workspace:
      root: ./
      paths:
        - dist
        - node_modules
        - environment_variables
  - notify_failed
