// flow-typed signature: 40b6b3d8236a6e8f6f9d77e0b0f908fa
// flow-typed version: <<STUB>>/@react-native-community/netinfo_v^5.3.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/netinfo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/netinfo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/netinfo/jest/netinfo-mock' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/internetReachability' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/nativeInterface' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/privateTypes' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/state' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/commonjs/internal/types' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/internetReachability' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/nativeInterface' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/privateTypes' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/state' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/lib/module/internal/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/netinfo/jest/netinfo-mock.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/jest/netinfo-mock'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/index' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/internetReachability.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/internetReachability'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/nativeInterface'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/privateTypes.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/privateTypes'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/state.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/state'>;
}
declare module '@react-native-community/netinfo/lib/commonjs/internal/types.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/commonjs/internal/types'>;
}
declare module '@react-native-community/netinfo/lib/module/index' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module'>;
}
declare module '@react-native-community/netinfo/lib/module/index.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/internetReachability.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/internetReachability'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/nativeInterface.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/nativeInterface'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/privateTypes.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/privateTypes'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/state.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/state'>;
}
declare module '@react-native-community/netinfo/lib/module/internal/types.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/lib/module/internal/types'>;
}
