#!/usr/bin/env node

const loadBuildConfig = require('../../build-configs').default
const { program } = require('commander')
const fs = require('fs')
const flat = require('flat')
const decamelize = require('decamelize')

const loadBuildConfigAsXCConfig = buildConfigName => {
  const buildConfig = loadBuildConfig(buildConfigName)
  const xcconfigOptions = flat(buildConfig, {
    delimiter: '_',
    transformKey: key => decamelize(key).toUpperCase()
  })
  const prefixed = Object.keys(xcconfigOptions).map(key => `BUILD_CONFIG_${key} = ${xcconfigOptions[key]}`)
  prefixed.push(`BUILD_CONFIG_NAME = ${buildConfigName}`)
  return prefixed.join('\n')
}

program
  .command('write-xcconfig <build_config_name>')
  .requiredOption('--directory <directory>', 'the directory to put the created xcconfig file in')
  .description('create and write a new .xcconfig from the iosBuildOptions of the specified build config')
  .action((buildConfigName, cmdObj) => {
    try {
      const xcconfig = loadBuildConfigAsXCConfig(buildConfigName)
      fs.writeFileSync(`${cmdObj.directory}/buildConfig.tmp.xcconfig`, xcconfig)
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  })

program
  .command('to-xcconfig <build_config_name>')
  .description('outputs the specified build config as XConfig')
  .action(buildConfigName => {
    try {
      const xcconfig = loadBuildConfigAsXCConfig(buildConfigName)
      console.log(xcconfig)
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  })

program
  .command('to-json <build_config_name>')
  .description('outputs the specified build config as JSON')
  .action(async buildConfigName => {
    const buildConfig = loadBuildConfig(buildConfigName)
    console.log(JSON.stringify(buildConfig))
  })

program.parse(process.argv)
