#!/usr/bin/env node

// https://github.com/babel/babel/issues/8309#issuecomment-439161848
// Modules in node_modules are ignored and not transpiled per default.
// Explicitly not ignore the build-configs npm module here since it has to be compiled as monorepo package.
require('@babel/register')({
  ignore: [/node_modules\/(?!build-configs)/]
})

const { program } = require('commander')
const fs = require('fs')
const flat = require('flat')
const decamelize = require('decamelize')
const loadBuildConfig = require('build-configs').default
const isString = require('lodash').isString

const loadBuildConfigAsXCConfig = (buildConfigName, platform) => {
  const buildConfig = loadBuildConfig(buildConfigName, platform)
  const xcconfigOptions = flat(buildConfig, {
    delimiter: '_',
    transformKey: key => decamelize(key).toUpperCase()
  })
  const prefixed = Object.keys(xcconfigOptions).map(key => {
    const value = xcconfigOptions[key]
    const escaped = isString(value) ? value.replace(/\n/g, '\\n') : value
    return `BUILD_CONFIG_${key} = ${escaped}`
  })
  prefixed.push(`BUILD_CONFIG_NAME = ${buildConfigName}`)
  return prefixed.join('\n')
}

program
  .command('write-xcconfig <build_config_name> <platform>')
  .requiredOption('--directory <directory>', 'the directory to put the created xcconfig file in')
  .description('create and write a new .xcconfig from the iosBuildOptions of the specified build config')
  .action((buildConfigName, platform, cmdObj) => {
    try {
      const xcconfig = loadBuildConfigAsXCConfig(buildConfigName, platform)
      fs.writeFileSync(`${cmdObj.directory}/buildConfig.tmp.xcconfig`, xcconfig)
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  })

program
  .command('to-xcconfig <build_config_name> <platform>')
  .description('outputs the specified build config as XConfig')
  .action((buildConfigName, platform) => {
    try {
      const xcconfig = loadBuildConfigAsXCConfig(buildConfigName, platform)
      console.log(xcconfig)
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  })

program
  .command('to-json <build_config_name> <platform>')
  .description('outputs the specified build config as JSON')
  .action((buildConfigName, platform) => {
    const buildConfig = loadBuildConfig(buildConfigName, platform)
    console.log(JSON.stringify(buildConfig))
  })

program.parse(process.argv)
