#!/usr/bin/env node

const fs = require('fs')
const { program } = require('commander')

const setupNativeTranslations = (appName, { translationsFile, destination }) => {
  const { native: nativeTranslations } = JSON.parse(fs.readFileSync(translationsFile))
  const languageCodes = Object.keys(nativeTranslations)
  console.warn('Creating InfoPlist.strings for the languages ', languageCodes)

  languageCodes.forEach(language => {
    const translations = nativeTranslations[language]
    const keys = Object.keys(translations)

    const content = keys.map((key) => {
      const regex = /{{appName}}/gi
      const value = translations[key].replace(regex, appName)
      return `${key} = "${value}";`
    }).join('\n')

    const path = `${destination}/${language}.lproj/`
    fs.mkdirSync(path, { recursive: true })
    fs.writeFileSync(`${path}InfoPlist.strings`, content)
  })

  console.warn('InfoPlist.strings successfully created.')
}

program
  .command('setup <appName>')
  .requiredOption('--translations <translations>', 'the path to the translations.json file')
  .requiredOption('--destination <destination>', 'the path to put the string resources to')
  .description('setup native translations for ios')
  .action((appName, program) => {
    try {
      setupNativeTranslations(appName, { translationsFile: program.translations, destination: program.destination })
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  })

program.parse(process.argv)
