# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Integreat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'IntegreatTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

