# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# https://github.com/ivpusic/react-native-image-crop-picker/issues/680#issuecomment-398636839
install! 'cocoapods',
         :deterministic_uuids => false

target 'Integreat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Flexbox Layout Manager Used By React Native
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',

  ]

  # Pods for Integreat
  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  # PDF
  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  # fast-image
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  # web view
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  # rn-fetch-blob
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  # react-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'IntegreatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # https://github.com/react-native-community/react-native-svg/issues/621#issuecomment-371639854
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end

