# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Integreat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Flexbox Layout Manager Used By React Native
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

  # Pods for Integreat
  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  # PDF
  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  # fast-image
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'  
  # web view
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  # rn-fetch-blob
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  # react-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'IntegreatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

