#!/usr/bin/env node

const { execSync } = require('child_process')
const { program } = require('commander')

program
  .command('packager <build_config_name>')
  .description('start metro packager')
  .action(buildConfigName => {
    const buildConfig = execSync(`yarn workspace --silent build-configs --silent manage to-bash ${buildConfigName} common`)
      .toString()
      .replaceAll('\n', ' ')
    execSync(`cross-env ${buildConfig} react-native start --reset-cache`, { stdio: 'inherit' })
  })

program
  .option('--production', 'whether a production (release) build should be made')
  .command('android <build_config_name>')
  .description('create android build')
  .action(buildConfigName => {
    const productionFlag = program.opts().production ? '--variant=release' : ''

    const jsonBuildConfig = execSync(`yarn workspace --silent build-configs --silent manage to-json ${buildConfigName} android`)
    const applicationId = JSON.parse(jsonBuildConfig).applicationId

    const buildConfig = execSync(`yarn workspace --silent build-configs --silent manage to-bash ${buildConfigName} android`)
      .toString()
      .replaceAll('\n', ' ')
    const command = `react-native run-android --no-packager --appId ${applicationId} ${productionFlag}`
    console.log('$ cross-env <BUILD_CONFIG>', command)
    execSync(`cross-env ${buildConfig} ${command}`, { stdio: 'inherit' })
  })

program.parse(process.argv)
