// flow-typed signature: e1333a237805d677ccba40539951947d
// flow-typed version: <<STUB>>/@react-native-picker/picker_v^1.9.11/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-picker/picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-picker/picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-picker/picker/babel.config' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/jest.setup' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/AndroidDialogPickerNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/AndroidDropdownPickerNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/Picker' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/Picker.web' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerAndroid.android' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerAndroid' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerAndroid.web' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerIOS.ios' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerIOS' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerIOS.web' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerItem' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerMacOS' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerMacOS.macos' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerMacOS.web' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerWindows' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerWindows.web' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/PickerWindows.windows' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/js/RNCPickerNativeComponent' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/metro.config.macos' {
  declare module.exports: any;
}

declare module '@react-native-picker/picker/react-native.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-picker/picker/babel.config.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/babel.config'>;
}
declare module '@react-native-picker/picker/index' {
  declare module.exports: $Exports<'@react-native-picker/picker'>;
}
declare module '@react-native-picker/picker/index.js' {
  declare module.exports: $Exports<'@react-native-picker/picker'>;
}
declare module '@react-native-picker/picker/jest.setup.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/jest.setup'>;
}
declare module '@react-native-picker/picker/js/AndroidDialogPickerNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/AndroidDialogPickerNativeComponent'>;
}
declare module '@react-native-picker/picker/js/AndroidDropdownPickerNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/AndroidDropdownPickerNativeComponent'>;
}
declare module '@react-native-picker/picker/js/index' {
  declare module.exports: $Exports<'@react-native-picker/picker/js'>;
}
declare module '@react-native-picker/picker/js/index.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js'>;
}
declare module '@react-native-picker/picker/js/Picker.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/Picker'>;
}
declare module '@react-native-picker/picker/js/Picker.web.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/Picker.web'>;
}
declare module '@react-native-picker/picker/js/PickerAndroid.android.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerAndroid.android'>;
}
declare module '@react-native-picker/picker/js/PickerAndroid.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerAndroid'>;
}
declare module '@react-native-picker/picker/js/PickerAndroid.web.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerAndroid.web'>;
}
declare module '@react-native-picker/picker/js/PickerIOS.ios.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerIOS.ios'>;
}
declare module '@react-native-picker/picker/js/PickerIOS.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerIOS'>;
}
declare module '@react-native-picker/picker/js/PickerIOS.web.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerIOS.web'>;
}
declare module '@react-native-picker/picker/js/PickerItem.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerItem'>;
}
declare module '@react-native-picker/picker/js/PickerMacOS.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerMacOS'>;
}
declare module '@react-native-picker/picker/js/PickerMacOS.macos.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerMacOS.macos'>;
}
declare module '@react-native-picker/picker/js/PickerMacOS.web.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerMacOS.web'>;
}
declare module '@react-native-picker/picker/js/PickerWindows.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerWindows'>;
}
declare module '@react-native-picker/picker/js/PickerWindows.web.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerWindows.web'>;
}
declare module '@react-native-picker/picker/js/PickerWindows.windows.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/PickerWindows.windows'>;
}
declare module '@react-native-picker/picker/js/RNCPickerNativeComponent.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/js/RNCPickerNativeComponent'>;
}
declare module '@react-native-picker/picker/metro.config.macos.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/metro.config.macos'>;
}
declare module '@react-native-picker/picker/react-native.config.js' {
  declare module.exports: $Exports<'@react-native-picker/picker/react-native.config'>;
}
