nmHoistingLimits: dependencies
nodeLinker: node-modules

compressionLevel: 0
enableGlobalCache: false
yarnPath: ../.yarn/releases/yarn-3.6.3.cjs

plugins:
  - path: ../native/.yarn/plugins/root-commands.js
  - path: ../.yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

preferInteractive: true
