// flow-typed signature: d7369264f018fdf6b47ee885fc439148
// flow-typed version: <<STUB>>/@testing-library/react-native_v^5.0.3/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/react-native/cleanup-after-each' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/act-compat' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/cleanup-async' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/config' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/events' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/get-node-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/get-queries-for-element' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/helpers' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/matches' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/pretty-print' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/all-utils' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/display-value' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/hint-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/label-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/placeholder-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/role' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/test-id' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/queries/title' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/query-helpers' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/to-json' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/wait-for-element-to-be-removed' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/wait-for-element' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/lib/wait' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/preset/configure' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/preset/mock-component' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/preset/mock-modules' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/preset/mock-native-methods' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/preset/serializer' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dist/preset/setup' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/jest-preset' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/pure' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/react-native/cleanup-after-each.js' {
  declare module.exports: $Exports<'@testing-library/react-native/cleanup-after-each'>;
}
declare module '@testing-library/react-native/dist/act-compat.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/act-compat'>;
}
declare module '@testing-library/react-native/dist/cleanup-async.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/cleanup-async'>;
}
declare module '@testing-library/react-native/dist/index' {
  declare module.exports: $Exports<'@testing-library/react-native/dist'>;
}
declare module '@testing-library/react-native/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist'>;
}
declare module '@testing-library/react-native/dist/lib/config.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/config'>;
}
declare module '@testing-library/react-native/dist/lib/events.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/events'>;
}
declare module '@testing-library/react-native/dist/lib/get-node-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/get-node-text'>;
}
declare module '@testing-library/react-native/dist/lib/get-queries-for-element.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/get-queries-for-element'>;
}
declare module '@testing-library/react-native/dist/lib/helpers.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/helpers'>;
}
declare module '@testing-library/react-native/dist/lib/index' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib'>;
}
declare module '@testing-library/react-native/dist/lib/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib'>;
}
declare module '@testing-library/react-native/dist/lib/matches.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/matches'>;
}
declare module '@testing-library/react-native/dist/lib/pretty-print.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/pretty-print'>;
}
declare module '@testing-library/react-native/dist/lib/queries/all-utils.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/all-utils'>;
}
declare module '@testing-library/react-native/dist/lib/queries/display-value.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/display-value'>;
}
declare module '@testing-library/react-native/dist/lib/queries/hint-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/hint-text'>;
}
declare module '@testing-library/react-native/dist/lib/queries/index' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries'>;
}
declare module '@testing-library/react-native/dist/lib/queries/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries'>;
}
declare module '@testing-library/react-native/dist/lib/queries/label-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/label-text'>;
}
declare module '@testing-library/react-native/dist/lib/queries/placeholder-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/placeholder-text'>;
}
declare module '@testing-library/react-native/dist/lib/queries/role.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/role'>;
}
declare module '@testing-library/react-native/dist/lib/queries/test-id.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/test-id'>;
}
declare module '@testing-library/react-native/dist/lib/queries/text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/text'>;
}
declare module '@testing-library/react-native/dist/lib/queries/title.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/queries/title'>;
}
declare module '@testing-library/react-native/dist/lib/query-helpers.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/query-helpers'>;
}
declare module '@testing-library/react-native/dist/lib/to-json.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/to-json'>;
}
declare module '@testing-library/react-native/dist/lib/wait-for-element-to-be-removed.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/wait-for-element-to-be-removed'>;
}
declare module '@testing-library/react-native/dist/lib/wait-for-element.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/wait-for-element'>;
}
declare module '@testing-library/react-native/dist/lib/wait.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/lib/wait'>;
}
declare module '@testing-library/react-native/dist/preset/configure.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/preset/configure'>;
}
declare module '@testing-library/react-native/dist/preset/mock-component.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/preset/mock-component'>;
}
declare module '@testing-library/react-native/dist/preset/mock-modules.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/preset/mock-modules'>;
}
declare module '@testing-library/react-native/dist/preset/mock-native-methods.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/preset/mock-native-methods'>;
}
declare module '@testing-library/react-native/dist/preset/serializer.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/preset/serializer'>;
}
declare module '@testing-library/react-native/dist/preset/setup.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dist/preset/setup'>;
}
declare module '@testing-library/react-native/jest-preset.js' {
  declare module.exports: $Exports<'@testing-library/react-native/jest-preset'>;
}
declare module '@testing-library/react-native/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-native/pure'>;
}
