# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# Currently now used as we use the `metadata` folder for most stuff and set settings manually in the deliver action
