fastlane_version "2.67.0"

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Create a simulator build"
  lane :build do
    scan(
        workspace: "Integreat.xcworkspace",
        device: "iPhone 6s"
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
