fastlane_version "2.143.0"

before_all do
  setup_circle_ci
end

desc "Download and setup certificates"
lane :certificates do
  ensure_env_vars(
      env_vars: ['FASTLANE_USER']
  )

  # https://docs.fastlane.tools/actions/match/
  sync_code_signing(type: "appstore", username: ENV['FASTLANE_USER'])
end



# version_name: The version name the build should use
# version_code: The version code the build should use
desc "Create a release build"
lane :build do |options|
  version_code = options[:version_code]
  version_name = options[:version_name]
  ensure_env_vars(
      env_vars: ['FASTLANE_USER']
  )

  ENV["BUNDLE_CONFIG"] = "./metro.config.ci.js"
  ENV["EXTRA_PACKAGER_ARGS"] = "--sourcemap-output /Users/distiller/project/ios/index.ios.bundle.map"

  # https://docs.fastlane.tools/actions/match/
  sync_code_signing(type: "development", username: ENV['FASTLANE_USER'])
  sync_code_signing(type: "appstore", username: ENV['FASTLANE_USER'])

  increment_build_number(
      build_number: version_code
  )

  increment_version_number(
      version_number: version_name
  )

  build_app(
      workspace: "Integreat.xcworkspace",
      scheme: "Integreat",
      output_name: "Integreat.ipa",
      export_method: "app-store",
      include_bitcode: false # Uploading to BrowserStack does not work when including Bitcode
  )
end

