export const initSentry = jest.fn()
export const log = jest.fn()
export const reportError = jest.fn()
export const deleteIfExists = jest.fn()
export const determineApiUrl = jest.fn(() => 'https://example.com')
export const forEachTreeNode = jest.fn()
export const generateRouteKey = jest.fn(() => 'my-route-key')
export const getExtension = jest.fn(() => '.png')
