// flow-typed signature: 508e9c49de1ce0c9919a322dc73c133a
// flow-typed version: <<STUB>>/api-client_v0.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'api-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'api-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'api-client/babel.config' {
  declare module.exports: any;
}

declare module 'api-client/jest.config' {
  declare module.exports: any;
}

declare module 'api-client/jest.setup' {
  declare module.exports: any;
}

declare module 'api-client/src/__tests__/Endpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/__tests__/EndpointBuilder.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/__tests__/hashUrl.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/__tests__/Payload.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/__tests__/replaceLinks.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/Endpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/EndpointBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createCategoriesEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createCitiesEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createDisclaimerEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createEventsEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createFeedbackEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createLanguagesEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createLocalNewsElementEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createLocalNewsEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createOffersEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createPOIsEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createSprungbrettJobsEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createTunewsElementEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createTunewsEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createTunewsLanguageEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/__tests__/createWohnenEndpoint.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createCategoriesEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createCitiesEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createDisclaimerEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createEventsEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createFeedbackEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createLanguagesEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createLocalNewsElementEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createLocalNewsEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createOffersEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createPOIsEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createSprungbrettJobsEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createTunewsElementEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createTunewsEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createTunewsLanguagesEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/endpoints/createWohnenEndpoint' {
  declare module.exports: any;
}

declare module 'api-client/src/errors/__tests__/NotFoundError.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/errors/FetchError' {
  declare module.exports: any;
}

declare module 'api-client/src/errors/MappingError' {
  declare module.exports: any;
}

declare module 'api-client/src/errors/NotFoundError' {
  declare module.exports: any;
}

declare module 'api-client/src/errors/ParamMissingError' {
  declare module.exports: any;
}

declare module 'api-client/src/errors/ResponseError' {
  declare module.exports: any;
}

declare module 'api-client/src/hashUrl' {
  declare module.exports: any;
}

declare module 'api-client/src/i18n/DateFormatter' {
  declare module.exports: any;
}

declare module 'api-client/src' {
  declare module.exports: any;
}

declare module 'api-client/src/mapAvailableLanguages' {
  declare module.exports: any;
}

declare module 'api-client/src/MapParamsToBody' {
  declare module.exports: any;
}

declare module 'api-client/src/MapParamsToUrlType' {
  declare module.exports: any;
}

declare module 'api-client/src/MapResponseType' {
  declare module.exports: any;
}

declare module 'api-client/src/models/__tests__/CategoriesMapModel.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/models/__tests__/CategoryModel.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/models/__tests__/CityModel.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/models/__tests__/DateModel.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/models/__tests__/LocationModel.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/models/CategoriesMapModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/CategoryModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/CityModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/DateModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/EventModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/ExtendedPageModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/FeaturedImageModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/LanguageModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/LocalNewsModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/LocationModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/OfferModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/PageModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/PoiModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/SprungbrettJobModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/TunewsModel' {
  declare module.exports: any;
}

declare module 'api-client/src/models/WohnenFormData' {
  declare module.exports: any;
}

declare module 'api-client/src/models/WohnenOfferModel' {
  declare module.exports: any;
}

declare module 'api-client/src/normalizePath' {
  declare module.exports: any;
}

declare module 'api-client/src/Payload' {
  declare module.exports: any;
}

declare module 'api-client/src/replaceLinks' {
  declare module.exports: any;
}

declare module 'api-client/src/routes/__tests__/InternalPathnameParser.spec' {
  declare module.exports: any;
}

declare module 'api-client/src/routes' {
  declare module.exports: any;
}

declare module 'api-client/src/routes/InternalPathnameParser' {
  declare module.exports: any;
}

declare module 'api-client/src/routes/RouteInformationTypes' {
  declare module.exports: any;
}

declare module 'api-client/src/stringifyFormData' {
  declare module.exports: any;
}

declare module 'api-client/src/testing/CategoriesMapModelBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/testing/CityModelBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/testing/EventModelBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/testing/LanguageModelBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/testing/NewsModelBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/testing/OffersModelBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/testing/PoiModelBuilder' {
  declare module.exports: any;
}

declare module 'api-client/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'api-client/babel.config.js' {
  declare module.exports: $Exports<'api-client/babel.config'>;
}
declare module 'api-client/jest.config.js' {
  declare module.exports: $Exports<'api-client/jest.config'>;
}
declare module 'api-client/jest.setup.js' {
  declare module.exports: $Exports<'api-client/jest.setup'>;
}
declare module 'api-client/src/__tests__/Endpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/__tests__/Endpoint.spec'>;
}
declare module 'api-client/src/__tests__/EndpointBuilder.spec.js' {
  declare module.exports: $Exports<'api-client/src/__tests__/EndpointBuilder.spec'>;
}
declare module 'api-client/src/__tests__/hashUrl.spec.js' {
  declare module.exports: $Exports<'api-client/src/__tests__/hashUrl.spec'>;
}
declare module 'api-client/src/__tests__/Payload.spec.js' {
  declare module.exports: $Exports<'api-client/src/__tests__/Payload.spec'>;
}
declare module 'api-client/src/__tests__/replaceLinks.spec.js' {
  declare module.exports: $Exports<'api-client/src/__tests__/replaceLinks.spec'>;
}
declare module 'api-client/src/Endpoint.js' {
  declare module.exports: $Exports<'api-client/src/Endpoint'>;
}
declare module 'api-client/src/EndpointBuilder.js' {
  declare module.exports: $Exports<'api-client/src/EndpointBuilder'>;
}
declare module 'api-client/src/endpoints/__tests__/createCategoriesEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createCategoriesEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createCitiesEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createCitiesEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createDisclaimerEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createDisclaimerEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createEventsEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createEventsEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createFeedbackEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createFeedbackEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createLanguagesEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createLanguagesEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createLocalNewsElementEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createLocalNewsElementEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createLocalNewsEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createLocalNewsEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createOffersEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createOffersEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createPOIsEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createPOIsEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createSprungbrettJobsEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createSprungbrettJobsEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createTunewsElementEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createTunewsElementEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createTunewsEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createTunewsEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createTunewsLanguageEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createTunewsLanguageEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/__tests__/createWohnenEndpoint.spec.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/__tests__/createWohnenEndpoint.spec'>;
}
declare module 'api-client/src/endpoints/createCategoriesEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createCategoriesEndpoint'>;
}
declare module 'api-client/src/endpoints/createCitiesEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createCitiesEndpoint'>;
}
declare module 'api-client/src/endpoints/createDisclaimerEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createDisclaimerEndpoint'>;
}
declare module 'api-client/src/endpoints/createEventsEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createEventsEndpoint'>;
}
declare module 'api-client/src/endpoints/createFeedbackEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createFeedbackEndpoint'>;
}
declare module 'api-client/src/endpoints/createLanguagesEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createLanguagesEndpoint'>;
}
declare module 'api-client/src/endpoints/createLocalNewsElementEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createLocalNewsElementEndpoint'>;
}
declare module 'api-client/src/endpoints/createLocalNewsEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createLocalNewsEndpoint'>;
}
declare module 'api-client/src/endpoints/createOffersEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createOffersEndpoint'>;
}
declare module 'api-client/src/endpoints/createPOIsEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createPOIsEndpoint'>;
}
declare module 'api-client/src/endpoints/createSprungbrettJobsEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createSprungbrettJobsEndpoint'>;
}
declare module 'api-client/src/endpoints/createTunewsElementEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createTunewsElementEndpoint'>;
}
declare module 'api-client/src/endpoints/createTunewsEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createTunewsEndpoint'>;
}
declare module 'api-client/src/endpoints/createTunewsLanguagesEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createTunewsLanguagesEndpoint'>;
}
declare module 'api-client/src/endpoints/createWohnenEndpoint.js' {
  declare module.exports: $Exports<'api-client/src/endpoints/createWohnenEndpoint'>;
}
declare module 'api-client/src/errors/__tests__/NotFoundError.spec.js' {
  declare module.exports: $Exports<'api-client/src/errors/__tests__/NotFoundError.spec'>;
}
declare module 'api-client/src/errors/FetchError.js' {
  declare module.exports: $Exports<'api-client/src/errors/FetchError'>;
}
declare module 'api-client/src/errors/MappingError.js' {
  declare module.exports: $Exports<'api-client/src/errors/MappingError'>;
}
declare module 'api-client/src/errors/NotFoundError.js' {
  declare module.exports: $Exports<'api-client/src/errors/NotFoundError'>;
}
declare module 'api-client/src/errors/ParamMissingError.js' {
  declare module.exports: $Exports<'api-client/src/errors/ParamMissingError'>;
}
declare module 'api-client/src/errors/ResponseError.js' {
  declare module.exports: $Exports<'api-client/src/errors/ResponseError'>;
}
declare module 'api-client/src/hashUrl.js' {
  declare module.exports: $Exports<'api-client/src/hashUrl'>;
}
declare module 'api-client/src/i18n/DateFormatter.js' {
  declare module.exports: $Exports<'api-client/src/i18n/DateFormatter'>;
}
declare module 'api-client/src/index' {
  declare module.exports: $Exports<'api-client/src'>;
}
declare module 'api-client/src/index.js' {
  declare module.exports: $Exports<'api-client/src'>;
}
declare module 'api-client/src/mapAvailableLanguages.js' {
  declare module.exports: $Exports<'api-client/src/mapAvailableLanguages'>;
}
declare module 'api-client/src/MapParamsToBody.js' {
  declare module.exports: $Exports<'api-client/src/MapParamsToBody'>;
}
declare module 'api-client/src/MapParamsToUrlType.js' {
  declare module.exports: $Exports<'api-client/src/MapParamsToUrlType'>;
}
declare module 'api-client/src/MapResponseType.js' {
  declare module.exports: $Exports<'api-client/src/MapResponseType'>;
}
declare module 'api-client/src/models/__tests__/CategoriesMapModel.spec.js' {
  declare module.exports: $Exports<'api-client/src/models/__tests__/CategoriesMapModel.spec'>;
}
declare module 'api-client/src/models/__tests__/CategoryModel.spec.js' {
  declare module.exports: $Exports<'api-client/src/models/__tests__/CategoryModel.spec'>;
}
declare module 'api-client/src/models/__tests__/CityModel.spec.js' {
  declare module.exports: $Exports<'api-client/src/models/__tests__/CityModel.spec'>;
}
declare module 'api-client/src/models/__tests__/DateModel.spec.js' {
  declare module.exports: $Exports<'api-client/src/models/__tests__/DateModel.spec'>;
}
declare module 'api-client/src/models/__tests__/LocationModel.spec.js' {
  declare module.exports: $Exports<'api-client/src/models/__tests__/LocationModel.spec'>;
}
declare module 'api-client/src/models/CategoriesMapModel.js' {
  declare module.exports: $Exports<'api-client/src/models/CategoriesMapModel'>;
}
declare module 'api-client/src/models/CategoryModel.js' {
  declare module.exports: $Exports<'api-client/src/models/CategoryModel'>;
}
declare module 'api-client/src/models/CityModel.js' {
  declare module.exports: $Exports<'api-client/src/models/CityModel'>;
}
declare module 'api-client/src/models/DateModel.js' {
  declare module.exports: $Exports<'api-client/src/models/DateModel'>;
}
declare module 'api-client/src/models/EventModel.js' {
  declare module.exports: $Exports<'api-client/src/models/EventModel'>;
}
declare module 'api-client/src/models/ExtendedPageModel.js' {
  declare module.exports: $Exports<'api-client/src/models/ExtendedPageModel'>;
}
declare module 'api-client/src/models/FeaturedImageModel.js' {
  declare module.exports: $Exports<'api-client/src/models/FeaturedImageModel'>;
}
declare module 'api-client/src/models/LanguageModel.js' {
  declare module.exports: $Exports<'api-client/src/models/LanguageModel'>;
}
declare module 'api-client/src/models/LocalNewsModel.js' {
  declare module.exports: $Exports<'api-client/src/models/LocalNewsModel'>;
}
declare module 'api-client/src/models/LocationModel.js' {
  declare module.exports: $Exports<'api-client/src/models/LocationModel'>;
}
declare module 'api-client/src/models/OfferModel.js' {
  declare module.exports: $Exports<'api-client/src/models/OfferModel'>;
}
declare module 'api-client/src/models/PageModel.js' {
  declare module.exports: $Exports<'api-client/src/models/PageModel'>;
}
declare module 'api-client/src/models/PoiModel.js' {
  declare module.exports: $Exports<'api-client/src/models/PoiModel'>;
}
declare module 'api-client/src/models/SprungbrettJobModel.js' {
  declare module.exports: $Exports<'api-client/src/models/SprungbrettJobModel'>;
}
declare module 'api-client/src/models/TunewsModel.js' {
  declare module.exports: $Exports<'api-client/src/models/TunewsModel'>;
}
declare module 'api-client/src/models/WohnenFormData.js' {
  declare module.exports: $Exports<'api-client/src/models/WohnenFormData'>;
}
declare module 'api-client/src/models/WohnenOfferModel.js' {
  declare module.exports: $Exports<'api-client/src/models/WohnenOfferModel'>;
}
declare module 'api-client/src/normalizePath.js' {
  declare module.exports: $Exports<'api-client/src/normalizePath'>;
}
declare module 'api-client/src/Payload.js' {
  declare module.exports: $Exports<'api-client/src/Payload'>;
}
declare module 'api-client/src/replaceLinks.js' {
  declare module.exports: $Exports<'api-client/src/replaceLinks'>;
}
declare module 'api-client/src/routes/__tests__/InternalPathnameParser.spec.js' {
  declare module.exports: $Exports<'api-client/src/routes/__tests__/InternalPathnameParser.spec'>;
}
declare module 'api-client/src/routes/index' {
  declare module.exports: $Exports<'api-client/src/routes'>;
}
declare module 'api-client/src/routes/index.js' {
  declare module.exports: $Exports<'api-client/src/routes'>;
}
declare module 'api-client/src/routes/InternalPathnameParser.js' {
  declare module.exports: $Exports<'api-client/src/routes/InternalPathnameParser'>;
}
declare module 'api-client/src/routes/RouteInformationTypes.js' {
  declare module.exports: $Exports<'api-client/src/routes/RouteInformationTypes'>;
}
declare module 'api-client/src/stringifyFormData.js' {
  declare module.exports: $Exports<'api-client/src/stringifyFormData'>;
}
declare module 'api-client/src/testing/CategoriesMapModelBuilder.js' {
  declare module.exports: $Exports<'api-client/src/testing/CategoriesMapModelBuilder'>;
}
declare module 'api-client/src/testing/CityModelBuilder.js' {
  declare module.exports: $Exports<'api-client/src/testing/CityModelBuilder'>;
}
declare module 'api-client/src/testing/EventModelBuilder.js' {
  declare module.exports: $Exports<'api-client/src/testing/EventModelBuilder'>;
}
declare module 'api-client/src/testing/LanguageModelBuilder.js' {
  declare module.exports: $Exports<'api-client/src/testing/LanguageModelBuilder'>;
}
declare module 'api-client/src/testing/NewsModelBuilder.js' {
  declare module.exports: $Exports<'api-client/src/testing/NewsModelBuilder'>;
}
declare module 'api-client/src/testing/OffersModelBuilder.js' {
  declare module.exports: $Exports<'api-client/src/testing/OffersModelBuilder'>;
}
declare module 'api-client/src/testing/PoiModelBuilder.js' {
  declare module.exports: $Exports<'api-client/src/testing/PoiModelBuilder'>;
}
declare module 'api-client/src/types.js' {
  declare module.exports: $Exports<'api-client/src/types'>;
}
