// flow-typed signature: 430c6538828383c1a9bfd3b5daf8ac85
// flow-typed version: <<STUB>>/build-configs_v0.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'build-configs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'build-configs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'build-configs/aschaffenburg' {
  declare module.exports: any;
}

declare module 'build-configs/aschaffenburg/mainImprint' {
  declare module.exports: any;
}

declare module 'build-configs/aschaffenburg/theme/colors' {
  declare module.exports: any;
}

declare module 'build-configs/aschaffenburg/theme/fonts' {
  declare module.exports: any;
}

declare module 'build-configs/aschaffenburg/theme' {
  declare module.exports: any;
}

declare module 'build-configs/AssetsType' {
  declare module.exports: any;
}

declare module 'build-configs/babel.config' {
  declare module.exports: any;
}

declare module 'build-configs/BuildConfigType' {
  declare module.exports: any;
}

declare module 'build-configs/common/theme/colors' {
  declare module.exports: any;
}

declare module 'build-configs/common/theme/fonts' {
  declare module.exports: any;
}

declare module 'build-configs/integreat-e2e' {
  declare module.exports: any;
}

declare module 'build-configs/integreat-test-cms' {
  declare module.exports: any;
}

declare module 'build-configs/integreat' {
  declare module.exports: any;
}

declare module 'build-configs/integreat/mainImprint' {
  declare module.exports: any;
}

declare module 'build-configs/integreat/theme/colors' {
  declare module.exports: any;
}

declare module 'build-configs/integreat/theme/fonts' {
  declare module.exports: any;
}

declare module 'build-configs/integreat/theme' {
  declare module.exports: any;
}

declare module 'build-configs/malte' {
  declare module.exports: any;
}

declare module 'build-configs/malte/mainImprint' {
  declare module.exports: any;
}

declare module 'build-configs/malte/theme/colors' {
  declare module.exports: any;
}

declare module 'build-configs/malte/theme/fonts' {
  declare module.exports: any;
}

declare module 'build-configs/malte/theme' {
  declare module.exports: any;
}

declare module 'build-configs/ThemeType' {
  declare module.exports: any;
}

declare module 'build-configs/tools/manage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'build-configs/aschaffenburg/index' {
  declare module.exports: $Exports<'build-configs/aschaffenburg'>;
}
declare module 'build-configs/aschaffenburg/index.js' {
  declare module.exports: $Exports<'build-configs/aschaffenburg'>;
}
declare module 'build-configs/aschaffenburg/mainImprint.js' {
  declare module.exports: $Exports<'build-configs/aschaffenburg/mainImprint'>;
}
declare module 'build-configs/aschaffenburg/theme/colors.js' {
  declare module.exports: $Exports<'build-configs/aschaffenburg/theme/colors'>;
}
declare module 'build-configs/aschaffenburg/theme/fonts.js' {
  declare module.exports: $Exports<'build-configs/aschaffenburg/theme/fonts'>;
}
declare module 'build-configs/aschaffenburg/theme/index' {
  declare module.exports: $Exports<'build-configs/aschaffenburg/theme'>;
}
declare module 'build-configs/aschaffenburg/theme/index.js' {
  declare module.exports: $Exports<'build-configs/aschaffenburg/theme'>;
}
declare module 'build-configs/AssetsType.js' {
  declare module.exports: $Exports<'build-configs/AssetsType'>;
}
declare module 'build-configs/babel.config.js' {
  declare module.exports: $Exports<'build-configs/babel.config'>;
}
declare module 'build-configs/BuildConfigType.js' {
  declare module.exports: $Exports<'build-configs/BuildConfigType'>;
}
declare module 'build-configs/common/theme/colors.js' {
  declare module.exports: $Exports<'build-configs/common/theme/colors'>;
}
declare module 'build-configs/common/theme/fonts.js' {
  declare module.exports: $Exports<'build-configs/common/theme/fonts'>;
}
declare module 'build-configs/index' {
  declare module.exports: $Exports<'build-configs'>;
}
declare module 'build-configs/index.js' {
  declare module.exports: $Exports<'build-configs'>;
}
declare module 'build-configs/integreat-e2e/index' {
  declare module.exports: $Exports<'build-configs/integreat-e2e'>;
}
declare module 'build-configs/integreat-e2e/index.js' {
  declare module.exports: $Exports<'build-configs/integreat-e2e'>;
}
declare module 'build-configs/integreat-test-cms/index' {
  declare module.exports: $Exports<'build-configs/integreat-test-cms'>;
}
declare module 'build-configs/integreat-test-cms/index.js' {
  declare module.exports: $Exports<'build-configs/integreat-test-cms'>;
}
declare module 'build-configs/integreat/index' {
  declare module.exports: $Exports<'build-configs/integreat'>;
}
declare module 'build-configs/integreat/index.js' {
  declare module.exports: $Exports<'build-configs/integreat'>;
}
declare module 'build-configs/integreat/mainImprint.js' {
  declare module.exports: $Exports<'build-configs/integreat/mainImprint'>;
}
declare module 'build-configs/integreat/theme/colors.js' {
  declare module.exports: $Exports<'build-configs/integreat/theme/colors'>;
}
declare module 'build-configs/integreat/theme/fonts.js' {
  declare module.exports: $Exports<'build-configs/integreat/theme/fonts'>;
}
declare module 'build-configs/integreat/theme/index' {
  declare module.exports: $Exports<'build-configs/integreat/theme'>;
}
declare module 'build-configs/integreat/theme/index.js' {
  declare module.exports: $Exports<'build-configs/integreat/theme'>;
}
declare module 'build-configs/malte/index' {
  declare module.exports: $Exports<'build-configs/malte'>;
}
declare module 'build-configs/malte/index.js' {
  declare module.exports: $Exports<'build-configs/malte'>;
}
declare module 'build-configs/malte/mainImprint.js' {
  declare module.exports: $Exports<'build-configs/malte/mainImprint'>;
}
declare module 'build-configs/malte/theme/colors.js' {
  declare module.exports: $Exports<'build-configs/malte/theme/colors'>;
}
declare module 'build-configs/malte/theme/fonts.js' {
  declare module.exports: $Exports<'build-configs/malte/theme/fonts'>;
}
declare module 'build-configs/malte/theme/index' {
  declare module.exports: $Exports<'build-configs/malte/theme'>;
}
declare module 'build-configs/malte/theme/index.js' {
  declare module.exports: $Exports<'build-configs/malte/theme'>;
}
declare module 'build-configs/ThemeType.js' {
  declare module.exports: $Exports<'build-configs/ThemeType'>;
}
declare module 'build-configs/tools/manage.js' {
  declare module.exports: $Exports<'build-configs/tools/manage'>;
}
