// flow-typed signature: 245feb9620c219f03de1c55cff8f71db
// flow-typed version: <<STUB>>/generator-rn-toolbox_v^3.14.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generator-rn-toolbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generator-rn-toolbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generator-rn-toolbox/analytics' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/App' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/__tests__/Button.test' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/Button' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/ButtonCard' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/Page' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/ProfileHeader' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/SecondaryFlatButton' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/TextInput' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/Touchable' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/lib/i18n' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Account' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Home' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Landing' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Login' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Signup' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/Scenes' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/theme' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/advanced-base/templates/translations' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/app' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/assets/getPixelColor' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/assets/imageGenerator' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/assets' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/App' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/components' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/components/Page' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/modules/App' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/modules/App/module' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/modules/Nav' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/modules/Nav/module' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/modules/rootEnhancer' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/modules/rootReducer' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/modules/store' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.component' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.container' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.style' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/pages' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/RootNavigation' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/base/templates/src/theme' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/bitrise' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/checkversion/checkUpdate' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/checkversion' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/circleci' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/fastlane-env' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/fastlane-env/templates/environment' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/fastlane-setup' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/fastlane-setup/templates/environment' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/jest' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/jest/templates/Button.test' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/jest/templates/FileStub' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/jest/templates/firstTest' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/lint' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/travisci' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/generators/vscode' {
  declare module.exports: any;
}

declare module 'generator-rn-toolbox/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generator-rn-toolbox/analytics.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/analytics'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/App.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/App'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/__tests__/Button.test.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/__tests__/Button.test'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/Button.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/Button'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/ButtonCard.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/ButtonCard'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/Page.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/Page'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/ProfileHeader.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/ProfileHeader'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/SecondaryFlatButton.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/SecondaryFlatButton'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/TextInput.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/TextInput'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/components/Touchable.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/components/Touchable'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/lib/i18n.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/lib/i18n'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Account.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Account'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Home.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Home'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/pages'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/pages'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Landing.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Landing'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Login.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Login'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Signup.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/pages/Signup'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/Scenes.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/Scenes'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/theme/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/theme'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/src/theme/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/src/theme'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/translations/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/translations'>;
}
declare module 'generator-rn-toolbox/generators/advanced-base/templates/translations/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/advanced-base/templates/translations'>;
}
declare module 'generator-rn-toolbox/generators/app/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/app'>;
}
declare module 'generator-rn-toolbox/generators/app/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/app'>;
}
declare module 'generator-rn-toolbox/generators/assets/getPixelColor.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/assets/getPixelColor'>;
}
declare module 'generator-rn-toolbox/generators/assets/imageGenerator.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/assets/imageGenerator'>;
}
declare module 'generator-rn-toolbox/generators/assets/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/assets'>;
}
declare module 'generator-rn-toolbox/generators/assets/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/assets'>;
}
declare module 'generator-rn-toolbox/generators/base/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base'>;
}
declare module 'generator-rn-toolbox/generators/base/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/App.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/App'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/components/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/components'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/components/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/components'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/components/Page.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/components/Page'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/App/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/App'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/App/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/App'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/App/module.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/App/module'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/Nav/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/Nav'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/Nav/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/Nav'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/Nav/module.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/Nav/module'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/rootEnhancer.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/rootEnhancer'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/rootReducer.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/rootReducer'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/modules/store.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/modules/store'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.component.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.component'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.container.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.container'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.style.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/pages/Home/Home.style'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/pages/Home'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/pages/Home/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/pages/Home'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/pages/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/pages'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/pages/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/pages'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/RootNavigation.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/RootNavigation'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/theme/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/theme'>;
}
declare module 'generator-rn-toolbox/generators/base/templates/src/theme/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/base/templates/src/theme'>;
}
declare module 'generator-rn-toolbox/generators/bitrise/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/bitrise'>;
}
declare module 'generator-rn-toolbox/generators/bitrise/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/bitrise'>;
}
declare module 'generator-rn-toolbox/generators/checkversion/checkUpdate.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/checkversion/checkUpdate'>;
}
declare module 'generator-rn-toolbox/generators/checkversion/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/checkversion'>;
}
declare module 'generator-rn-toolbox/generators/checkversion/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/checkversion'>;
}
declare module 'generator-rn-toolbox/generators/circleci/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/circleci'>;
}
declare module 'generator-rn-toolbox/generators/circleci/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/circleci'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-env/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-env'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-env/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-env'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-env/templates/environment/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-env/templates/environment'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-env/templates/environment/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-env/templates/environment'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-setup/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-setup'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-setup/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-setup'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-setup/templates/environment/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-setup/templates/environment'>;
}
declare module 'generator-rn-toolbox/generators/fastlane-setup/templates/environment/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/fastlane-setup/templates/environment'>;
}
declare module 'generator-rn-toolbox/generators/jest/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/jest'>;
}
declare module 'generator-rn-toolbox/generators/jest/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/jest'>;
}
declare module 'generator-rn-toolbox/generators/jest/templates/Button.test.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/jest/templates/Button.test'>;
}
declare module 'generator-rn-toolbox/generators/jest/templates/FileStub.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/jest/templates/FileStub'>;
}
declare module 'generator-rn-toolbox/generators/jest/templates/firstTest.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/jest/templates/firstTest'>;
}
declare module 'generator-rn-toolbox/generators/lint/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/lint'>;
}
declare module 'generator-rn-toolbox/generators/lint/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/lint'>;
}
declare module 'generator-rn-toolbox/generators/travisci/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/travisci'>;
}
declare module 'generator-rn-toolbox/generators/travisci/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/travisci'>;
}
declare module 'generator-rn-toolbox/generators/vscode/index' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/vscode'>;
}
declare module 'generator-rn-toolbox/generators/vscode/index.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/generators/vscode'>;
}
declare module 'generator-rn-toolbox/test.js' {
  declare module.exports: $Exports<'generator-rn-toolbox/test'>;
}
