// flow-typed signature: 687774148ae4711cc225de5e836d5456
// flow-typed version: <<STUB>>/get-dev-paths_v^0.1.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-dev-paths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-dev-paths' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'get-dev-paths/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'get-dev-paths/lib/index' {
  declare module.exports: $Exports<'get-dev-paths/lib'>;
}
declare module 'get-dev-paths/lib/index.js' {
  declare module.exports: $Exports<'get-dev-paths/lib'>;
}
