// flow-typed signature: 0363a39b1401e1e6bf9b51fbb26de1ed
// flow-typed version: <<STUB>>/metro-react-native-babel-preset_v^0.65.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metro-react-native-babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metro-react-native-babel-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'metro-react-native-babel-preset/src/configs/hmr' {
  declare module.exports: any;
}

declare module 'metro-react-native-babel-preset/src/configs/lazy-imports' {
  declare module.exports: any;
}

declare module 'metro-react-native-babel-preset/src/configs/main' {
  declare module.exports: any;
}

declare module 'metro-react-native-babel-preset/src' {
  declare module.exports: any;
}

declare module 'metro-react-native-babel-preset/src/passthrough-syntax-plugins' {
  declare module.exports: any;
}

// Filename aliases
declare module 'metro-react-native-babel-preset/src/configs/hmr.js' {
  declare module.exports: $Exports<'metro-react-native-babel-preset/src/configs/hmr'>;
}
declare module 'metro-react-native-babel-preset/src/configs/lazy-imports.js' {
  declare module.exports: $Exports<'metro-react-native-babel-preset/src/configs/lazy-imports'>;
}
declare module 'metro-react-native-babel-preset/src/configs/main.js' {
  declare module.exports: $Exports<'metro-react-native-babel-preset/src/configs/main'>;
}
declare module 'metro-react-native-babel-preset/src/index' {
  declare module.exports: $Exports<'metro-react-native-babel-preset/src'>;
}
declare module 'metro-react-native-babel-preset/src/index.js' {
  declare module.exports: $Exports<'metro-react-native-babel-preset/src'>;
}
declare module 'metro-react-native-babel-preset/src/passthrough-syntax-plugins.js' {
  declare module.exports: $Exports<'metro-react-native-babel-preset/src/passthrough-syntax-plugins'>;
}
