// flow-typed signature: d063d6703e9ede520f5ee8cefdae7f7d
// flow-typed version: <<STUB>>/normalize-strings_v^1.1.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-strings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-strings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'normalize-strings/normalize' {
  declare module.exports: any;
}

declare module 'normalize-strings/normalize.min' {
  declare module.exports: any;
}

declare module 'normalize-strings/supported' {
  declare module.exports: any;
}

declare module 'normalize-strings/test/normalize.test' {
  declare module.exports: any;
}

declare module 'normalize-strings/util/getCharMap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'normalize-strings/index' {
  declare module.exports: $Exports<'normalize-strings'>;
}
declare module 'normalize-strings/index.js' {
  declare module.exports: $Exports<'normalize-strings'>;
}
declare module 'normalize-strings/normalize.js' {
  declare module.exports: $Exports<'normalize-strings/normalize'>;
}
declare module 'normalize-strings/normalize.min.js' {
  declare module.exports: $Exports<'normalize-strings/normalize.min'>;
}
declare module 'normalize-strings/supported.js' {
  declare module.exports: $Exports<'normalize-strings/supported'>;
}
declare module 'normalize-strings/test/normalize.test.js' {
  declare module.exports: $Exports<'normalize-strings/test/normalize.test'>;
}
declare module 'normalize-strings/util/getCharMap.js' {
  declare module.exports: $Exports<'normalize-strings/util/getCharMap'>;
}
