// flow-typed signature: 01c46acce4241713ef49803a1dc445a6
// flow-typed version: <<STUB>>/react-native-webview_v10.8.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-webview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-webview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-webview/lib/WebView.android' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView.ios' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView.macos' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView.styles' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebView.windows' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebViewShared' {
  declare module.exports: any;
}

declare module 'react-native-webview/lib/WebViewTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-webview/index' {
  declare module.exports: $Exports<'react-native-webview'>;
}
declare module 'react-native-webview/index.js' {
  declare module.exports: $Exports<'react-native-webview'>;
}
declare module 'react-native-webview/lib/WebView.android.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.android'>;
}
declare module 'react-native-webview/lib/WebView.ios.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.ios'>;
}
declare module 'react-native-webview/lib/WebView.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView'>;
}
declare module 'react-native-webview/lib/WebView.macos.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.macos'>;
}
declare module 'react-native-webview/lib/WebView.styles.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.styles'>;
}
declare module 'react-native-webview/lib/WebView.windows.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebView.windows'>;
}
declare module 'react-native-webview/lib/WebViewShared.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebViewShared'>;
}
declare module 'react-native-webview/lib/WebViewTypes.js' {
  declare module.exports: $Exports<'react-native-webview/lib/WebViewTypes'>;
}
