// flow-typed signature: fd2e7a069c037877888ca51292bd38fd
// flow-typed version: <<STUB>>/react-native-inappbrowser-reborn_v^3.5.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-inappbrowser-reborn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-inappbrowser-reborn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-inappbrowser-reborn/types' {
  declare module.exports: any;
}

declare module 'react-native-inappbrowser-reborn/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-inappbrowser-reborn/index' {
  declare module.exports: $Exports<'react-native-inappbrowser-reborn'>;
}
declare module 'react-native-inappbrowser-reborn/index.js' {
  declare module.exports: $Exports<'react-native-inappbrowser-reborn'>;
}
declare module 'react-native-inappbrowser-reborn/types.js' {
  declare module.exports: $Exports<'react-native-inappbrowser-reborn/types'>;
}
declare module 'react-native-inappbrowser-reborn/utils.js' {
  declare module.exports: $Exports<'react-native-inappbrowser-reborn/utils'>;
}
