// flow-typed signature: 16fb100d903c6a619c8a79e524a5dd11
// flow-typed version: <<STUB>>/react-native-safe-area-view_v2.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area-view/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/lib/commonjs/index.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/lib/commonjs/shallowEquals' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/lib/module/index.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/lib/module/shallowEquals' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/src/index.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area-view/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/commonjs'>;
}
declare module 'react-native-safe-area-view/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/commonjs'>;
}
declare module 'react-native-safe-area-view/lib/commonjs/index.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/commonjs/index.web'>;
}
declare module 'react-native-safe-area-view/lib/commonjs/shallowEquals.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/commonjs/shallowEquals'>;
}
declare module 'react-native-safe-area-view/lib/module/index' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/module'>;
}
declare module 'react-native-safe-area-view/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/module'>;
}
declare module 'react-native-safe-area-view/lib/module/index.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/module/index.web'>;
}
declare module 'react-native-safe-area-view/lib/module/shallowEquals.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/lib/module/shallowEquals'>;
}
declare module 'react-native-safe-area-view/src/index.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/src/index.web'>;
}
