// flow-typed signature: 95888c488b496706268d68b93db0edaf
// flow-typed version: <<STUB>>/react-native-image-zoom-viewer_v^3.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-zoom-viewer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-zoom-viewer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-image-zoom-viewer/built/image-viewer.component' {
  declare module.exports: any;
}

declare module 'react-native-image-zoom-viewer/built/image-viewer.style' {
  declare module.exports: any;
}

declare module 'react-native-image-zoom-viewer/built/image-viewer.type' {
  declare module.exports: any;
}

declare module 'react-native-image-zoom-viewer/built' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-image-zoom-viewer/built/image-viewer.component.js' {
  declare module.exports: $Exports<'react-native-image-zoom-viewer/built/image-viewer.component'>;
}
declare module 'react-native-image-zoom-viewer/built/image-viewer.style.js' {
  declare module.exports: $Exports<'react-native-image-zoom-viewer/built/image-viewer.style'>;
}
declare module 'react-native-image-zoom-viewer/built/image-viewer.type.js' {
  declare module.exports: $Exports<'react-native-image-zoom-viewer/built/image-viewer.type'>;
}
declare module 'react-native-image-zoom-viewer/built/index' {
  declare module.exports: $Exports<'react-native-image-zoom-viewer/built'>;
}
declare module 'react-native-image-zoom-viewer/built/index.js' {
  declare module.exports: $Exports<'react-native-image-zoom-viewer/built'>;
}
