// flow-typed signature: 59d73be13ad2d8a593176b09ce0bc6c5
// flow-typed version: <<STUB>>/react-native-svg-asset-plugin_v^0.5.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg-asset-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg-asset-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg-asset-plugin/lib/cache' {
  declare module.exports: any;
}

declare module 'react-native-svg-asset-plugin/lib/config' {
  declare module.exports: any;
}

declare module 'react-native-svg-asset-plugin/lib' {
  declare module.exports: any;
}

declare module 'react-native-svg-asset-plugin/lib/sharp' {
  declare module.exports: any;
}

declare module 'react-native-svg-asset-plugin/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'react-native-svg-asset-plugin/lib/utils/func' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg-asset-plugin/lib/cache.js' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib/cache'>;
}
declare module 'react-native-svg-asset-plugin/lib/config.js' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib/config'>;
}
declare module 'react-native-svg-asset-plugin/lib/index' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib'>;
}
declare module 'react-native-svg-asset-plugin/lib/index.js' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib'>;
}
declare module 'react-native-svg-asset-plugin/lib/sharp.js' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib/sharp'>;
}
declare module 'react-native-svg-asset-plugin/lib/utils/fs.js' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib/utils/fs'>;
}
declare module 'react-native-svg-asset-plugin/lib/utils/func.js' {
  declare module.exports: $Exports<'react-native-svg-asset-plugin/lib/utils/func'>;
}
