// flow-typed signature: 2e0eb953e5f8846c9c2cd2917ba8c887
// flow-typed version: <<STUB>>/react-native-elements_v2.3.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-elements/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/avatar/__tests__/Accessory' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/avatar/__tests__/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/avatar/Accessory' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/avatar/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/badge/__tests__/Badge' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/badge/__tests__/withBadge' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/badge/Badge' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/badge/withBadge' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/bottomSheet/__tests__/BottomSheet' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/bottomSheet/BottomSheet' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/__tests__/Button' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/__tests__/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/Button' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/__tests__/Card' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/Card' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/CardDivider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/CardFeaturedSubtitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/CardFeaturedTitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/CardImage' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/CardTitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/checkbox/__tests__/CheckBox' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/checkbox/CheckBox' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/checkbox/CheckBoxIcon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/__tests__/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/__tests__/withTheme' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/BackgroundImage' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/colors' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/colorsDark' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/fonts' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/theme' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/withTheme' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/divider/__tests__/Divider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/divider/Divider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/__tests__/Header' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/Header' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/getIconStyle' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/getIconType' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/nodeType' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/normalizeText' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/renderNode' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/types' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/icons/__tests__/Icon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/icons/Icon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/image/__tests__/Image' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/image/Image' {
  declare module.exports: any;
}

declare module 'react-native-elements/src' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/input/__tests__/Input' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/input/Input' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/__tests__/ListItem' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItem' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItemButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItemCheckBox' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItemChevron' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItemContent' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItemInput' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItemSubtitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItemTitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/overlay/__tests__/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/overlay/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/pricing/__tests__/PricingCard' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/pricing/PricingCard' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/__tests__/common' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/__tests__/SearchBar-android' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/__tests__/SearchBar-default' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/__tests__/SearchBar-ios' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/__tests__/SearchBar' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/SearchBar-android' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/SearchBar-default' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/SearchBar-ios' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/searchbar/SearchBar' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/slider/__tests__/Slider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/slider/Slider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/social/__tests__/SocialIcon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/social/SocialIcon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/text/__tests__/Text' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/text/Text' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/__tests__/FeaturedTile' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/__tests__/Tile' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/FeaturedTile' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/Tile' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tooltip/__tests__/Tooltip.android' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tooltip/__tests__/Tooltip' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tooltip/getTooltipCoordinate' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tooltip/Triangle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-elements/babel.config.js' {
  declare module.exports: $Exports<'react-native-elements/babel.config'>;
}
declare module 'react-native-elements/src/avatar/__tests__/Accessory.js' {
  declare module.exports: $Exports<'react-native-elements/src/avatar/__tests__/Accessory'>;
}
declare module 'react-native-elements/src/avatar/__tests__/Avatar.js' {
  declare module.exports: $Exports<'react-native-elements/src/avatar/__tests__/Avatar'>;
}
declare module 'react-native-elements/src/avatar/Accessory.js' {
  declare module.exports: $Exports<'react-native-elements/src/avatar/Accessory'>;
}
declare module 'react-native-elements/src/avatar/Avatar.js' {
  declare module.exports: $Exports<'react-native-elements/src/avatar/Avatar'>;
}
declare module 'react-native-elements/src/badge/__tests__/Badge.js' {
  declare module.exports: $Exports<'react-native-elements/src/badge/__tests__/Badge'>;
}
declare module 'react-native-elements/src/badge/__tests__/withBadge.js' {
  declare module.exports: $Exports<'react-native-elements/src/badge/__tests__/withBadge'>;
}
declare module 'react-native-elements/src/badge/Badge.js' {
  declare module.exports: $Exports<'react-native-elements/src/badge/Badge'>;
}
declare module 'react-native-elements/src/badge/withBadge.js' {
  declare module.exports: $Exports<'react-native-elements/src/badge/withBadge'>;
}
declare module 'react-native-elements/src/bottomSheet/__tests__/BottomSheet.js' {
  declare module.exports: $Exports<'react-native-elements/src/bottomSheet/__tests__/BottomSheet'>;
}
declare module 'react-native-elements/src/bottomSheet/BottomSheet.js' {
  declare module.exports: $Exports<'react-native-elements/src/bottomSheet/BottomSheet'>;
}
declare module 'react-native-elements/src/buttons/__tests__/Button.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/__tests__/Button'>;
}
declare module 'react-native-elements/src/buttons/__tests__/ButtonGroup.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/__tests__/ButtonGroup'>;
}
declare module 'react-native-elements/src/buttons/Button.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/Button'>;
}
declare module 'react-native-elements/src/buttons/ButtonGroup.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/ButtonGroup'>;
}
declare module 'react-native-elements/src/card/__tests__/Card.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/__tests__/Card'>;
}
declare module 'react-native-elements/src/card/Card.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/Card'>;
}
declare module 'react-native-elements/src/card/CardDivider.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/CardDivider'>;
}
declare module 'react-native-elements/src/card/CardFeaturedSubtitle.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/CardFeaturedSubtitle'>;
}
declare module 'react-native-elements/src/card/CardFeaturedTitle.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/CardFeaturedTitle'>;
}
declare module 'react-native-elements/src/card/CardImage.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/CardImage'>;
}
declare module 'react-native-elements/src/card/CardTitle.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/CardTitle'>;
}
declare module 'react-native-elements/src/checkbox/__tests__/CheckBox.js' {
  declare module.exports: $Exports<'react-native-elements/src/checkbox/__tests__/CheckBox'>;
}
declare module 'react-native-elements/src/checkbox/CheckBox.js' {
  declare module.exports: $Exports<'react-native-elements/src/checkbox/CheckBox'>;
}
declare module 'react-native-elements/src/checkbox/CheckBoxIcon.js' {
  declare module.exports: $Exports<'react-native-elements/src/checkbox/CheckBoxIcon'>;
}
declare module 'react-native-elements/src/config/__tests__/ThemeProvider.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/__tests__/ThemeProvider'>;
}
declare module 'react-native-elements/src/config/__tests__/withTheme.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/__tests__/withTheme'>;
}
declare module 'react-native-elements/src/config/BackgroundImage.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/BackgroundImage'>;
}
declare module 'react-native-elements/src/config/colors.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/colors'>;
}
declare module 'react-native-elements/src/config/colorsDark.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/colorsDark'>;
}
declare module 'react-native-elements/src/config/fonts.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/fonts'>;
}
declare module 'react-native-elements/src/config/index' {
  declare module.exports: $Exports<'react-native-elements/src/config'>;
}
declare module 'react-native-elements/src/config/index.js' {
  declare module.exports: $Exports<'react-native-elements/src/config'>;
}
declare module 'react-native-elements/src/config/theme.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/theme'>;
}
declare module 'react-native-elements/src/config/ThemeProvider.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/ThemeProvider'>;
}
declare module 'react-native-elements/src/config/withTheme.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/withTheme'>;
}
declare module 'react-native-elements/src/divider/__tests__/Divider.js' {
  declare module.exports: $Exports<'react-native-elements/src/divider/__tests__/Divider'>;
}
declare module 'react-native-elements/src/divider/Divider.js' {
  declare module.exports: $Exports<'react-native-elements/src/divider/Divider'>;
}
declare module 'react-native-elements/src/header/__tests__/Header.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/__tests__/Header'>;
}
declare module 'react-native-elements/src/header/Header.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/Header'>;
}
declare module 'react-native-elements/src/helpers/getIconStyle.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/getIconStyle'>;
}
declare module 'react-native-elements/src/helpers/getIconType.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/getIconType'>;
}
declare module 'react-native-elements/src/helpers/index' {
  declare module.exports: $Exports<'react-native-elements/src/helpers'>;
}
declare module 'react-native-elements/src/helpers/index.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers'>;
}
declare module 'react-native-elements/src/helpers/nodeType.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/nodeType'>;
}
declare module 'react-native-elements/src/helpers/normalizeText.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/normalizeText'>;
}
declare module 'react-native-elements/src/helpers/renderNode.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/renderNode'>;
}
declare module 'react-native-elements/src/helpers/types.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/types'>;
}
declare module 'react-native-elements/src/icons/__tests__/Icon.js' {
  declare module.exports: $Exports<'react-native-elements/src/icons/__tests__/Icon'>;
}
declare module 'react-native-elements/src/icons/Icon.js' {
  declare module.exports: $Exports<'react-native-elements/src/icons/Icon'>;
}
declare module 'react-native-elements/src/image/__tests__/Image.js' {
  declare module.exports: $Exports<'react-native-elements/src/image/__tests__/Image'>;
}
declare module 'react-native-elements/src/image/Image.js' {
  declare module.exports: $Exports<'react-native-elements/src/image/Image'>;
}
declare module 'react-native-elements/src/index' {
  declare module.exports: $Exports<'react-native-elements/src'>;
}
declare module 'react-native-elements/src/index.js' {
  declare module.exports: $Exports<'react-native-elements/src'>;
}
declare module 'react-native-elements/src/input/__tests__/Input.js' {
  declare module.exports: $Exports<'react-native-elements/src/input/__tests__/Input'>;
}
declare module 'react-native-elements/src/input/Input.js' {
  declare module.exports: $Exports<'react-native-elements/src/input/Input'>;
}
declare module 'react-native-elements/src/list/__tests__/ListItem.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/__tests__/ListItem'>;
}
declare module 'react-native-elements/src/list/ListItem.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItem'>;
}
declare module 'react-native-elements/src/list/ListItemButtonGroup.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItemButtonGroup'>;
}
declare module 'react-native-elements/src/list/ListItemCheckBox.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItemCheckBox'>;
}
declare module 'react-native-elements/src/list/ListItemChevron.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItemChevron'>;
}
declare module 'react-native-elements/src/list/ListItemContent.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItemContent'>;
}
declare module 'react-native-elements/src/list/ListItemInput.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItemInput'>;
}
declare module 'react-native-elements/src/list/ListItemSubtitle.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItemSubtitle'>;
}
declare module 'react-native-elements/src/list/ListItemTitle.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItemTitle'>;
}
declare module 'react-native-elements/src/overlay/__tests__/Overlay.js' {
  declare module.exports: $Exports<'react-native-elements/src/overlay/__tests__/Overlay'>;
}
declare module 'react-native-elements/src/overlay/Overlay.js' {
  declare module.exports: $Exports<'react-native-elements/src/overlay/Overlay'>;
}
declare module 'react-native-elements/src/pricing/__tests__/PricingCard.js' {
  declare module.exports: $Exports<'react-native-elements/src/pricing/__tests__/PricingCard'>;
}
declare module 'react-native-elements/src/pricing/PricingCard.js' {
  declare module.exports: $Exports<'react-native-elements/src/pricing/PricingCard'>;
}
declare module 'react-native-elements/src/searchbar/__tests__/common.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/__tests__/common'>;
}
declare module 'react-native-elements/src/searchbar/__tests__/SearchBar-android.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/__tests__/SearchBar-android'>;
}
declare module 'react-native-elements/src/searchbar/__tests__/SearchBar-default.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/__tests__/SearchBar-default'>;
}
declare module 'react-native-elements/src/searchbar/__tests__/SearchBar-ios.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/__tests__/SearchBar-ios'>;
}
declare module 'react-native-elements/src/searchbar/__tests__/SearchBar.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/__tests__/SearchBar'>;
}
declare module 'react-native-elements/src/searchbar/SearchBar-android.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/SearchBar-android'>;
}
declare module 'react-native-elements/src/searchbar/SearchBar-default.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/SearchBar-default'>;
}
declare module 'react-native-elements/src/searchbar/SearchBar-ios.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/SearchBar-ios'>;
}
declare module 'react-native-elements/src/searchbar/SearchBar.js' {
  declare module.exports: $Exports<'react-native-elements/src/searchbar/SearchBar'>;
}
declare module 'react-native-elements/src/slider/__tests__/Slider.js' {
  declare module.exports: $Exports<'react-native-elements/src/slider/__tests__/Slider'>;
}
declare module 'react-native-elements/src/slider/Slider.js' {
  declare module.exports: $Exports<'react-native-elements/src/slider/Slider'>;
}
declare module 'react-native-elements/src/social/__tests__/SocialIcon.js' {
  declare module.exports: $Exports<'react-native-elements/src/social/__tests__/SocialIcon'>;
}
declare module 'react-native-elements/src/social/SocialIcon.js' {
  declare module.exports: $Exports<'react-native-elements/src/social/SocialIcon'>;
}
declare module 'react-native-elements/src/text/__tests__/Text.js' {
  declare module.exports: $Exports<'react-native-elements/src/text/__tests__/Text'>;
}
declare module 'react-native-elements/src/text/Text.js' {
  declare module.exports: $Exports<'react-native-elements/src/text/Text'>;
}
declare module 'react-native-elements/src/tile/__tests__/FeaturedTile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/__tests__/FeaturedTile'>;
}
declare module 'react-native-elements/src/tile/__tests__/Tile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/__tests__/Tile'>;
}
declare module 'react-native-elements/src/tile/FeaturedTile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/FeaturedTile'>;
}
declare module 'react-native-elements/src/tile/Tile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/Tile'>;
}
declare module 'react-native-elements/src/tooltip/__tests__/Tooltip.android.js' {
  declare module.exports: $Exports<'react-native-elements/src/tooltip/__tests__/Tooltip.android'>;
}
declare module 'react-native-elements/src/tooltip/__tests__/Tooltip.js' {
  declare module.exports: $Exports<'react-native-elements/src/tooltip/__tests__/Tooltip'>;
}
declare module 'react-native-elements/src/tooltip/getTooltipCoordinate.js' {
  declare module.exports: $Exports<'react-native-elements/src/tooltip/getTooltipCoordinate'>;
}
declare module 'react-native-elements/src/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'react-native-elements/src/tooltip/Tooltip'>;
}
declare module 'react-native-elements/src/tooltip/Triangle.js' {
  declare module.exports: $Exports<'react-native-elements/src/tooltip/Triangle'>;
}
