// flow-typed signature: 09d20f26395f4e6d49bc8bb9d8f65980
// flow-typed version: <<STUB>>/react-native-permissions_v3.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-permissions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-permissions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-permissions/dist/commonjs/contract' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/methods.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/methods.ios' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/methods' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/methods.windows' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/permissions.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/permissions.ios' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/permissions' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/permissions.windows' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/results' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/unsupportedPlatformMethods' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/contract' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/methods.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/methods.ios' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/methods' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/methods.windows' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/permissions.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/permissions.ios' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/permissions' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/permissions.windows' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/results' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/types' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/unsupportedPlatformMethods' {
  declare module.exports: any;
}

declare module 'react-native-permissions/dist/module/utils' {
  declare module.exports: any;
}

declare module 'react-native-permissions/mock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-permissions/dist/commonjs/contract.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/contract'>;
}
declare module 'react-native-permissions/dist/commonjs/index' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs'>;
}
declare module 'react-native-permissions/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs'>;
}
declare module 'react-native-permissions/dist/commonjs/methods.android.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/methods.android'>;
}
declare module 'react-native-permissions/dist/commonjs/methods.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/methods.ios'>;
}
declare module 'react-native-permissions/dist/commonjs/methods.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/methods'>;
}
declare module 'react-native-permissions/dist/commonjs/methods.windows.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/methods.windows'>;
}
declare module 'react-native-permissions/dist/commonjs/permissions.android.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/permissions.android'>;
}
declare module 'react-native-permissions/dist/commonjs/permissions.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/permissions.ios'>;
}
declare module 'react-native-permissions/dist/commonjs/permissions.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/permissions'>;
}
declare module 'react-native-permissions/dist/commonjs/permissions.windows.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/permissions.windows'>;
}
declare module 'react-native-permissions/dist/commonjs/results.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/results'>;
}
declare module 'react-native-permissions/dist/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/types'>;
}
declare module 'react-native-permissions/dist/commonjs/unsupportedPlatformMethods.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/unsupportedPlatformMethods'>;
}
declare module 'react-native-permissions/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/commonjs/utils'>;
}
declare module 'react-native-permissions/dist/module/contract.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/contract'>;
}
declare module 'react-native-permissions/dist/module/index' {
  declare module.exports: $Exports<'react-native-permissions/dist/module'>;
}
declare module 'react-native-permissions/dist/module/index.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module'>;
}
declare module 'react-native-permissions/dist/module/methods.android.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/methods.android'>;
}
declare module 'react-native-permissions/dist/module/methods.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/methods.ios'>;
}
declare module 'react-native-permissions/dist/module/methods.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/methods'>;
}
declare module 'react-native-permissions/dist/module/methods.windows.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/methods.windows'>;
}
declare module 'react-native-permissions/dist/module/permissions.android.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/permissions.android'>;
}
declare module 'react-native-permissions/dist/module/permissions.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/permissions.ios'>;
}
declare module 'react-native-permissions/dist/module/permissions.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/permissions'>;
}
declare module 'react-native-permissions/dist/module/permissions.windows.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/permissions.windows'>;
}
declare module 'react-native-permissions/dist/module/results.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/results'>;
}
declare module 'react-native-permissions/dist/module/types.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/types'>;
}
declare module 'react-native-permissions/dist/module/unsupportedPlatformMethods.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/unsupportedPlatformMethods'>;
}
declare module 'react-native-permissions/dist/module/utils.js' {
  declare module.exports: $Exports<'react-native-permissions/dist/module/utils'>;
}
declare module 'react-native-permissions/mock.js' {
  declare module.exports: $Exports<'react-native-permissions/mock'>;
}
