// flow-typed signature: 317b1603bf8d67e682d93bbe924ad47b
// flow-typed version: <<STUB>>/react-native-localize_v^2.0.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-localize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-localize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-localize/dist/commonjs/constants' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/commonjs/module' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/commonjs/module.web' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/module/constants' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/module' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/module/module' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/module/module.web' {
  declare module.exports: any;
}

declare module 'react-native-localize/dist/module/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-localize/dist/commonjs/constants.js' {
  declare module.exports: $Exports<'react-native-localize/dist/commonjs/constants'>;
}
declare module 'react-native-localize/dist/commonjs/index' {
  declare module.exports: $Exports<'react-native-localize/dist/commonjs'>;
}
declare module 'react-native-localize/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-localize/dist/commonjs'>;
}
declare module 'react-native-localize/dist/commonjs/module.js' {
  declare module.exports: $Exports<'react-native-localize/dist/commonjs/module'>;
}
declare module 'react-native-localize/dist/commonjs/module.web.js' {
  declare module.exports: $Exports<'react-native-localize/dist/commonjs/module.web'>;
}
declare module 'react-native-localize/dist/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-localize/dist/commonjs/types'>;
}
declare module 'react-native-localize/dist/module/constants.js' {
  declare module.exports: $Exports<'react-native-localize/dist/module/constants'>;
}
declare module 'react-native-localize/dist/module/index' {
  declare module.exports: $Exports<'react-native-localize/dist/module'>;
}
declare module 'react-native-localize/dist/module/index.js' {
  declare module.exports: $Exports<'react-native-localize/dist/module'>;
}
declare module 'react-native-localize/dist/module/module.js' {
  declare module.exports: $Exports<'react-native-localize/dist/module/module'>;
}
declare module 'react-native-localize/dist/module/module.web.js' {
  declare module.exports: $Exports<'react-native-localize/dist/module/module.web'>;
}
declare module 'react-native-localize/dist/module/types.js' {
  declare module.exports: $Exports<'react-native-localize/dist/module/types'>;
}
