// flow-typed signature: 2ffb7a0f655ac137a2e0083cb5a61339
// flow-typed version: <<STUB>>/react-native-static-server_v^0.5.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-static-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-static-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-static-server/index' {
  declare module.exports: $Exports<'react-native-static-server'>;
}
declare module 'react-native-static-server/index.js' {
  declare module.exports: $Exports<'react-native-static-server'>;
}
