// flow-typed signature: ae05d0b0d4f92e2dcf76ef7a4b3b3bc1
// flow-typed version: <<STUB>>/react-native-elements_v^3.3.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-elements/dist/avatar/Accessory' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/avatar/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/badge/Badge' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/badge/withBadge' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/bottomSheet/BottomSheet' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/buttons/Button' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/buttons/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/card/Card' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/card/CardDivider' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/card/CardFeaturedSubtitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/card/CardFeaturedTitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/card/CardImage' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/card/CardTitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/checkbox/CheckBox' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/checkbox/CheckBoxIcon' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/BackgroundImage' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/colors' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/colorsDark' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/fonts' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/makeStyles' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/theme' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/config/withTheme' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/divider/Divider' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/header/Header' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/helpers/getIconStyle' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/helpers/getIconType' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/helpers' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/helpers/normalizeText' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/helpers/renderNode' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/icons/Icon' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/image/Image' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/input/Input' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItem' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItemButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItemCheckBox' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItemChevron' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItemContent' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItemInput' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItemSubtitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/list/ListItemTitle' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/overlay/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/pricing/PricingCard' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/searchbar/SearchBar-android' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/searchbar/SearchBar-default' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/searchbar/SearchBar-ios' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/searchbar/SearchBar' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/slider/Slider' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/social/SocialIcon' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/text/Text' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/tile/FeaturedTile' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/tile/Tile' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/tooltip/getTooltipCoordinate' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'react-native-elements/dist/tooltip/Triangle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-elements/dist/avatar/Accessory.js' {
  declare module.exports: $Exports<'react-native-elements/dist/avatar/Accessory'>;
}
declare module 'react-native-elements/dist/avatar/Avatar.js' {
  declare module.exports: $Exports<'react-native-elements/dist/avatar/Avatar'>;
}
declare module 'react-native-elements/dist/badge/Badge.js' {
  declare module.exports: $Exports<'react-native-elements/dist/badge/Badge'>;
}
declare module 'react-native-elements/dist/badge/withBadge.js' {
  declare module.exports: $Exports<'react-native-elements/dist/badge/withBadge'>;
}
declare module 'react-native-elements/dist/bottomSheet/BottomSheet.js' {
  declare module.exports: $Exports<'react-native-elements/dist/bottomSheet/BottomSheet'>;
}
declare module 'react-native-elements/dist/buttons/Button.js' {
  declare module.exports: $Exports<'react-native-elements/dist/buttons/Button'>;
}
declare module 'react-native-elements/dist/buttons/ButtonGroup.js' {
  declare module.exports: $Exports<'react-native-elements/dist/buttons/ButtonGroup'>;
}
declare module 'react-native-elements/dist/card/Card.js' {
  declare module.exports: $Exports<'react-native-elements/dist/card/Card'>;
}
declare module 'react-native-elements/dist/card/CardDivider.js' {
  declare module.exports: $Exports<'react-native-elements/dist/card/CardDivider'>;
}
declare module 'react-native-elements/dist/card/CardFeaturedSubtitle.js' {
  declare module.exports: $Exports<'react-native-elements/dist/card/CardFeaturedSubtitle'>;
}
declare module 'react-native-elements/dist/card/CardFeaturedTitle.js' {
  declare module.exports: $Exports<'react-native-elements/dist/card/CardFeaturedTitle'>;
}
declare module 'react-native-elements/dist/card/CardImage.js' {
  declare module.exports: $Exports<'react-native-elements/dist/card/CardImage'>;
}
declare module 'react-native-elements/dist/card/CardTitle.js' {
  declare module.exports: $Exports<'react-native-elements/dist/card/CardTitle'>;
}
declare module 'react-native-elements/dist/checkbox/CheckBox.js' {
  declare module.exports: $Exports<'react-native-elements/dist/checkbox/CheckBox'>;
}
declare module 'react-native-elements/dist/checkbox/CheckBoxIcon.js' {
  declare module.exports: $Exports<'react-native-elements/dist/checkbox/CheckBoxIcon'>;
}
declare module 'react-native-elements/dist/config/BackgroundImage.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/BackgroundImage'>;
}
declare module 'react-native-elements/dist/config/colors.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/colors'>;
}
declare module 'react-native-elements/dist/config/colorsDark.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/colorsDark'>;
}
declare module 'react-native-elements/dist/config/fonts.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/fonts'>;
}
declare module 'react-native-elements/dist/config/index' {
  declare module.exports: $Exports<'react-native-elements/dist/config'>;
}
declare module 'react-native-elements/dist/config/index.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config'>;
}
declare module 'react-native-elements/dist/config/makeStyles.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/makeStyles'>;
}
declare module 'react-native-elements/dist/config/theme.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/theme'>;
}
declare module 'react-native-elements/dist/config/ThemeProvider.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/ThemeProvider'>;
}
declare module 'react-native-elements/dist/config/withTheme.js' {
  declare module.exports: $Exports<'react-native-elements/dist/config/withTheme'>;
}
declare module 'react-native-elements/dist/divider/Divider.js' {
  declare module.exports: $Exports<'react-native-elements/dist/divider/Divider'>;
}
declare module 'react-native-elements/dist/header/Header.js' {
  declare module.exports: $Exports<'react-native-elements/dist/header/Header'>;
}
declare module 'react-native-elements/dist/helpers/getIconStyle.js' {
  declare module.exports: $Exports<'react-native-elements/dist/helpers/getIconStyle'>;
}
declare module 'react-native-elements/dist/helpers/getIconType.js' {
  declare module.exports: $Exports<'react-native-elements/dist/helpers/getIconType'>;
}
declare module 'react-native-elements/dist/helpers/index' {
  declare module.exports: $Exports<'react-native-elements/dist/helpers'>;
}
declare module 'react-native-elements/dist/helpers/index.js' {
  declare module.exports: $Exports<'react-native-elements/dist/helpers'>;
}
declare module 'react-native-elements/dist/helpers/normalizeText.js' {
  declare module.exports: $Exports<'react-native-elements/dist/helpers/normalizeText'>;
}
declare module 'react-native-elements/dist/helpers/renderNode.js' {
  declare module.exports: $Exports<'react-native-elements/dist/helpers/renderNode'>;
}
declare module 'react-native-elements/dist/icons/Icon.js' {
  declare module.exports: $Exports<'react-native-elements/dist/icons/Icon'>;
}
declare module 'react-native-elements/dist/image/Image.js' {
  declare module.exports: $Exports<'react-native-elements/dist/image/Image'>;
}
declare module 'react-native-elements/dist/index' {
  declare module.exports: $Exports<'react-native-elements/dist'>;
}
declare module 'react-native-elements/dist/index.js' {
  declare module.exports: $Exports<'react-native-elements/dist'>;
}
declare module 'react-native-elements/dist/input/Input.js' {
  declare module.exports: $Exports<'react-native-elements/dist/input/Input'>;
}
declare module 'react-native-elements/dist/list/ListItem.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItem'>;
}
declare module 'react-native-elements/dist/list/ListItemButtonGroup.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItemButtonGroup'>;
}
declare module 'react-native-elements/dist/list/ListItemCheckBox.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItemCheckBox'>;
}
declare module 'react-native-elements/dist/list/ListItemChevron.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItemChevron'>;
}
declare module 'react-native-elements/dist/list/ListItemContent.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItemContent'>;
}
declare module 'react-native-elements/dist/list/ListItemInput.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItemInput'>;
}
declare module 'react-native-elements/dist/list/ListItemSubtitle.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItemSubtitle'>;
}
declare module 'react-native-elements/dist/list/ListItemTitle.js' {
  declare module.exports: $Exports<'react-native-elements/dist/list/ListItemTitle'>;
}
declare module 'react-native-elements/dist/overlay/Overlay.js' {
  declare module.exports: $Exports<'react-native-elements/dist/overlay/Overlay'>;
}
declare module 'react-native-elements/dist/pricing/PricingCard.js' {
  declare module.exports: $Exports<'react-native-elements/dist/pricing/PricingCard'>;
}
declare module 'react-native-elements/dist/searchbar/SearchBar-android.js' {
  declare module.exports: $Exports<'react-native-elements/dist/searchbar/SearchBar-android'>;
}
declare module 'react-native-elements/dist/searchbar/SearchBar-default.js' {
  declare module.exports: $Exports<'react-native-elements/dist/searchbar/SearchBar-default'>;
}
declare module 'react-native-elements/dist/searchbar/SearchBar-ios.js' {
  declare module.exports: $Exports<'react-native-elements/dist/searchbar/SearchBar-ios'>;
}
declare module 'react-native-elements/dist/searchbar/SearchBar.js' {
  declare module.exports: $Exports<'react-native-elements/dist/searchbar/SearchBar'>;
}
declare module 'react-native-elements/dist/slider/Slider.js' {
  declare module.exports: $Exports<'react-native-elements/dist/slider/Slider'>;
}
declare module 'react-native-elements/dist/social/SocialIcon.js' {
  declare module.exports: $Exports<'react-native-elements/dist/social/SocialIcon'>;
}
declare module 'react-native-elements/dist/text/Text.js' {
  declare module.exports: $Exports<'react-native-elements/dist/text/Text'>;
}
declare module 'react-native-elements/dist/tile/FeaturedTile.js' {
  declare module.exports: $Exports<'react-native-elements/dist/tile/FeaturedTile'>;
}
declare module 'react-native-elements/dist/tile/Tile.js' {
  declare module.exports: $Exports<'react-native-elements/dist/tile/Tile'>;
}
declare module 'react-native-elements/dist/tooltip/getTooltipCoordinate.js' {
  declare module.exports: $Exports<'react-native-elements/dist/tooltip/getTooltipCoordinate'>;
}
declare module 'react-native-elements/dist/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'react-native-elements/dist/tooltip/Tooltip'>;
}
declare module 'react-native-elements/dist/tooltip/Triangle.js' {
  declare module.exports: $Exports<'react-native-elements/dist/tooltip/Triangle'>;
}
