// flow-typed signature: bdc31a12c597173b932d6bd30953e9a7
// flow-typed version: <<STUB>>/react-native-highlight-words_v^1.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-highlight-words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-highlight-words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-highlight-words/index' {
  declare module.exports: $Exports<'react-native-highlight-words'>;
}
declare module 'react-native-highlight-words/index.js' {
  declare module.exports: $Exports<'react-native-highlight-words'>;
}
