// flow-typed signature: edcda26a7261f152c05ee4c12b7858f3
// flow-typed version: <<STUB>>/react-native-render-html_v^5.1.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-render-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-render-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-render-html/lib/domNodeToHTMLString' {
  declare module.exports: any;
}

declare module 'react-native-render-html/lib/HTML' {
  declare module.exports: any;
}

declare module 'react-native-render-html/lib/HTMLDefaultStyles' {
  declare module.exports: any;
}

declare module 'react-native-render-html/lib/HTMLImage' {
  declare module.exports: any;
}

declare module 'react-native-render-html/lib/HTMLRenderers' {
  declare module.exports: any;
}

declare module 'react-native-render-html/lib/HTMLStyles' {
  declare module.exports: any;
}

declare module 'react-native-render-html/lib/HTMLUtils' {
  declare module.exports: any;
}

declare module 'react-native-render-html/lib' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__mocks__/react-native' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/component.html.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/component.image.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/domNodeToHTMLString.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.118.white-space-handling.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.141.custom-blur-image.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.172.custom-image-resize-mode.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.193.text-selectable-prop.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.252.css-text-align-rule.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.257.css-display-rule.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.266.css-regex.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.276.cusom-renderer-wrapper.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.319.css-border-rule.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.343.tags-styles-re-render.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.344.css-inline-inheritance-override.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.361.css-margin-rule.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.377.classes-styles-re-render.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.383.html-bloated-anchor.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.384.html-bloated-image.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/regression.408.embedded-url-two-forward-slashes.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/utils' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/w3c.css.box-model.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/w3c.css.inline.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/w3c.css.white-space.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/__tests__/w3c.html.pre.test' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/domNodeToHTMLString' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTML' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLDefaultStyles' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLImage' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLRenderers' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLStyles' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLUtils' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-render-html/lib/domNodeToHTMLString.js' {
  declare module.exports: $Exports<'react-native-render-html/lib/domNodeToHTMLString'>;
}
declare module 'react-native-render-html/lib/HTML.js' {
  declare module.exports: $Exports<'react-native-render-html/lib/HTML'>;
}
declare module 'react-native-render-html/lib/HTMLDefaultStyles.js' {
  declare module.exports: $Exports<'react-native-render-html/lib/HTMLDefaultStyles'>;
}
declare module 'react-native-render-html/lib/HTMLImage.js' {
  declare module.exports: $Exports<'react-native-render-html/lib/HTMLImage'>;
}
declare module 'react-native-render-html/lib/HTMLRenderers.js' {
  declare module.exports: $Exports<'react-native-render-html/lib/HTMLRenderers'>;
}
declare module 'react-native-render-html/lib/HTMLStyles.js' {
  declare module.exports: $Exports<'react-native-render-html/lib/HTMLStyles'>;
}
declare module 'react-native-render-html/lib/HTMLUtils.js' {
  declare module.exports: $Exports<'react-native-render-html/lib/HTMLUtils'>;
}
declare module 'react-native-render-html/lib/index' {
  declare module.exports: $Exports<'react-native-render-html/lib'>;
}
declare module 'react-native-render-html/lib/index.js' {
  declare module.exports: $Exports<'react-native-render-html/lib'>;
}
declare module 'react-native-render-html/src/__mocks__/react-native.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__mocks__/react-native'>;
}
declare module 'react-native-render-html/src/__tests__/component.html.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/component.html.test'>;
}
declare module 'react-native-render-html/src/__tests__/component.image.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/component.image.test'>;
}
declare module 'react-native-render-html/src/__tests__/domNodeToHTMLString.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/domNodeToHTMLString.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.118.white-space-handling.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.118.white-space-handling.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.141.custom-blur-image.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.141.custom-blur-image.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.172.custom-image-resize-mode.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.172.custom-image-resize-mode.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.193.text-selectable-prop.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.193.text-selectable-prop.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.252.css-text-align-rule.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.252.css-text-align-rule.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.257.css-display-rule.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.257.css-display-rule.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.266.css-regex.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.266.css-regex.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.276.cusom-renderer-wrapper.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.276.cusom-renderer-wrapper.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.319.css-border-rule.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.319.css-border-rule.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.343.tags-styles-re-render.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.343.tags-styles-re-render.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.344.css-inline-inheritance-override.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.344.css-inline-inheritance-override.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.361.css-margin-rule.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.361.css-margin-rule.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.377.classes-styles-re-render.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.377.classes-styles-re-render.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.383.html-bloated-anchor.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.383.html-bloated-anchor.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.384.html-bloated-image.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.384.html-bloated-image.test'>;
}
declare module 'react-native-render-html/src/__tests__/regression.408.embedded-url-two-forward-slashes.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/regression.408.embedded-url-two-forward-slashes.test'>;
}
declare module 'react-native-render-html/src/__tests__/utils.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/utils'>;
}
declare module 'react-native-render-html/src/__tests__/w3c.css.box-model.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/w3c.css.box-model.test'>;
}
declare module 'react-native-render-html/src/__tests__/w3c.css.inline.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/w3c.css.inline.test'>;
}
declare module 'react-native-render-html/src/__tests__/w3c.css.white-space.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/w3c.css.white-space.test'>;
}
declare module 'react-native-render-html/src/__tests__/w3c.html.pre.test.js' {
  declare module.exports: $Exports<'react-native-render-html/src/__tests__/w3c.html.pre.test'>;
}
declare module 'react-native-render-html/src/domNodeToHTMLString.js' {
  declare module.exports: $Exports<'react-native-render-html/src/domNodeToHTMLString'>;
}
declare module 'react-native-render-html/src/HTML.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTML'>;
}
declare module 'react-native-render-html/src/HTMLDefaultStyles.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLDefaultStyles'>;
}
declare module 'react-native-render-html/src/HTMLImage.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLImage'>;
}
declare module 'react-native-render-html/src/HTMLRenderers.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLRenderers'>;
}
declare module 'react-native-render-html/src/HTMLStyles.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLStyles'>;
}
declare module 'react-native-render-html/src/HTMLUtils.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLUtils'>;
}
declare module 'react-native-render-html/src/index' {
  declare module.exports: $Exports<'react-native-render-html/src'>;
}
declare module 'react-native-render-html/src/index.js' {
  declare module.exports: $Exports<'react-native-render-html/src'>;
}
