// flow-typed signature: a1c50175a7c0a718983fb45a6d9ab27a
// flow-typed version: <<STUB>>/redux-flipper_v^1.4.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-flipper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-flipper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-flipper/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-flipper/lib/index' {
  declare module.exports: $Exports<'redux-flipper/lib'>;
}
declare module 'redux-flipper/lib/index.js' {
  declare module.exports: $Exports<'redux-flipper/lib'>;
}
