// flow-typed signature: 6a7d8c5551a4866829eec52a2e9c92ae
// flow-typed version: <<STUB>>/translations_v0.0.1/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'translations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'translations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'translations/babel.config' {
  declare module.exports: any;
}

declare module 'translations/jest.config' {
  declare module.exports: any;
}

declare module 'translations/jest.setup' {
  declare module.exports: any;
}

declare module 'translations/src/__mocks__/loadTranslations' {
  declare module.exports: any;
}

declare module 'translations/src/__tests__/config.spec' {
  declare module.exports: any;
}

declare module 'translations/src/__tests__/loadTranslations.spec' {
  declare module.exports: any;
}

declare module 'translations/src/config' {
  declare module.exports: any;
}

declare module 'translations/src' {
  declare module.exports: any;
}

declare module 'translations/src/loadTranslations' {
  declare module.exports: any;
}

declare module 'translations/src/transformTranslations' {
  declare module.exports: any;
}

declare module 'translations/src/types' {
  declare module.exports: any;
}

declare module 'translations/src/utils/object' {
  declare module.exports: any;
}

declare module 'translations/tools/manage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'translations/babel.config.js' {
  declare module.exports: $Exports<'translations/babel.config'>;
}
declare module 'translations/jest.config.js' {
  declare module.exports: $Exports<'translations/jest.config'>;
}
declare module 'translations/jest.setup.js' {
  declare module.exports: $Exports<'translations/jest.setup'>;
}
declare module 'translations/src/__mocks__/loadTranslations.js' {
  declare module.exports: $Exports<'translations/src/__mocks__/loadTranslations'>;
}
declare module 'translations/src/__tests__/config.spec.js' {
  declare module.exports: $Exports<'translations/src/__tests__/config.spec'>;
}
declare module 'translations/src/__tests__/loadTranslations.spec.js' {
  declare module.exports: $Exports<'translations/src/__tests__/loadTranslations.spec'>;
}
declare module 'translations/src/config.js' {
  declare module.exports: $Exports<'translations/src/config'>;
}
declare module 'translations/src/index' {
  declare module.exports: $Exports<'translations/src'>;
}
declare module 'translations/src/index.js' {
  declare module.exports: $Exports<'translations/src'>;
}
declare module 'translations/src/loadTranslations.js' {
  declare module.exports: $Exports<'translations/src/loadTranslations'>;
}
declare module 'translations/src/transformTranslations.js' {
  declare module.exports: $Exports<'translations/src/transformTranslations'>;
}
declare module 'translations/src/types.js' {
  declare module.exports: $Exports<'translations/src/types'>;
}
declare module 'translations/src/utils/object.js' {
  declare module.exports: $Exports<'translations/src/utils/object'>;
}
declare module 'translations/tools/manage.js' {
  declare module.exports: $Exports<'translations/tools/manage'>;
}
