// flow-typed signature: 99f064b08985ae975bb23a1d3004df7f
// flow-typed version: <<STUB>>/url-parse_v^1.4.7/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-parse/dist/url-parse' {
  declare module.exports: any;
}

declare module 'url-parse/dist/url-parse.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-parse/dist/url-parse.js' {
  declare module.exports: $Exports<'url-parse/dist/url-parse'>;
}
declare module 'url-parse/dist/url-parse.min.js' {
  declare module.exports: $Exports<'url-parse/dist/url-parse.min'>;
}
declare module 'url-parse/index' {
  declare module.exports: $Exports<'url-parse'>;
}
declare module 'url-parse/index.js' {
  declare module.exports: $Exports<'url-parse'>;
}
