// flow-typed signature: 58b0b86f578ef6f8c0705c38d2d0f794
// flow-typed version: <<STUB>>/wait-for-expect_v^3.0.2/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-for-expect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait-for-expect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait-for-expect/lib/helpers' {
  declare module.exports: any;
}

declare module 'wait-for-expect/lib/index.d' {
  declare module.exports: any;
}

declare module 'wait-for-expect/lib' {
  declare module.exports: any;
}

declare module 'wait-for-expect/lib/toBeInRangeMatcher.d' {
  declare module.exports: any;
}

declare module 'wait-for-expect/lib/toBeInRangeMatcher' {
  declare module.exports: any;
}

declare module 'wait-for-expect/lib/waitForExpect.spec.d' {
  declare module.exports: any;
}

declare module 'wait-for-expect/lib/waitForExpect.spec' {
  declare module.exports: any;
}

declare module 'wait-for-expect/lib/withFakeTimers.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait-for-expect/lib/helpers.js' {
  declare module.exports: $Exports<'wait-for-expect/lib/helpers'>;
}
declare module 'wait-for-expect/lib/index.d.js' {
  declare module.exports: $Exports<'wait-for-expect/lib/index.d'>;
}
declare module 'wait-for-expect/lib/index' {
  declare module.exports: $Exports<'wait-for-expect/lib'>;
}
declare module 'wait-for-expect/lib/index.js' {
  declare module.exports: $Exports<'wait-for-expect/lib'>;
}
declare module 'wait-for-expect/lib/toBeInRangeMatcher.d.js' {
  declare module.exports: $Exports<'wait-for-expect/lib/toBeInRangeMatcher.d'>;
}
declare module 'wait-for-expect/lib/toBeInRangeMatcher.js' {
  declare module.exports: $Exports<'wait-for-expect/lib/toBeInRangeMatcher'>;
}
declare module 'wait-for-expect/lib/waitForExpect.spec.d.js' {
  declare module.exports: $Exports<'wait-for-expect/lib/waitForExpect.spec.d'>;
}
declare module 'wait-for-expect/lib/waitForExpect.spec.js' {
  declare module.exports: $Exports<'wait-for-expect/lib/waitForExpect.spec'>;
}
declare module 'wait-for-expect/lib/withFakeTimers.spec.js' {
  declare module.exports: $Exports<'wait-for-expect/lib/withFakeTimers.spec'>;
}
