// flow-typed signature: 61892f8e02ffb8cf805d775b48d7289a
// flow-typed version: <<STUB>>/@testing-library/jest-native_v^3.4.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/jest-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/jest-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/jest-native/dist/extend-expect' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-be-disabled' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-be-empty' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-contain-element' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-prop' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-style' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-text-content' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/utils' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/extend-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/jest-native/dist/extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/extend-expect'>;
}
declare module '@testing-library/jest-native/dist/index' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist'>;
}
declare module '@testing-library/jest-native/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist'>;
}
declare module '@testing-library/jest-native/dist/to-be-disabled.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-be-disabled'>;
}
declare module '@testing-library/jest-native/dist/to-be-empty.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-be-empty'>;
}
declare module '@testing-library/jest-native/dist/to-contain-element.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-contain-element'>;
}
declare module '@testing-library/jest-native/dist/to-have-prop.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-prop'>;
}
declare module '@testing-library/jest-native/dist/to-have-style.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-style'>;
}
declare module '@testing-library/jest-native/dist/to-have-text-content.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-text-content'>;
}
declare module '@testing-library/jest-native/dist/utils.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/utils'>;
}
declare module '@testing-library/jest-native/extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/extend-expect'>;
}
