import { PreparePlacesReturn as ImportedPreparePlacesReturn } from './utils/places.js'

export type PreparePlacesReturn = ImportedPreparePlacesReturn
export type { Chunk, FindAll, FindChunks } from 'highlight-words-core'
export { findAll, findChunks } from 'highlight-words-core'
export { default as useSearch, prepareSearchDocuments } from './hooks/useSearch.js'
export { default as useDebounce } from './hooks/useDebounce.js'
export { default as useDateFilter } from './hooks/useDateFilter.js'
export { default as InternalPathnameParser } from './routes/InternalPathnameParser.js'
export * from './routes/index.js'
export * from './routes/RouteInformationTypes.js'
export * from './routes/query.js'
export * from './routes/pathname.js'
export * from './utils/search.js'
export * from './utils/licences.js'
export * from './utils/places.js'
export * from './utils/replaceLinks.js'
export * from './utils/normalizeString.js'
export { default as findNormalizedMatches, findAllMatches } from './utils/findNormalizedMatches.js'
export * from './utils/index.js'
export { getCategoryTiles } from './utils/categories.js'
export * from './constants/map.js'
export * from './constants/news.js'
export * from './utils/dateFilterUtils.js'
export * from './utils/getExcerpt.js'
export { default as getNearbyRegions } from './utils/getNearbyRegions.js'
export { default as getExternalMapsLink } from './utils/getExternalMapsLink.js'
export { default as normalizePath } from './utils/normalizePath.js'
export { default as parseHTML } from './utils/parseHTML.js'
export { default as encodeQR } from 'qr'
export { embedInCollection } from './utils/geoJson.js'
export { prepareMapFeatures, prepareMapFeature, MIN_DISTANCE_THRESHOLD } from './utils/geoJson.js'
export { default as getExcerpt } from './utils/getExcerpt.js'
export { default as isCurrentlyOpen } from './utils/isCurrentlyOpen.js'
export * from './constants/index.js'
export { default as TileModel } from './models/TileModel.js'
export type ExternalSourcePermissions = Record<string, boolean>
