import { PreparePlacesReturn as ImportedPreparePlacesReturn } from './utils/places.ts'

export type PreparePlacesReturn = ImportedPreparePlacesReturn
export type { Chunk, FindAll, FindChunks } from 'highlight-words-core'
export { findAll, findChunks } from 'highlight-words-core'
export { default as useSearch, prepareSearchDocuments } from './hooks/useSearch.ts'
export { default as useDebounce } from './hooks/useDebounce.ts'
export { default as useDateFilter } from './hooks/useDateFilter.ts'
export { default as InternalPathnameParser } from './routes/InternalPathnameParser.ts'
export * from './routes/index.ts'
export * from './routes/RouteInformationTypes.ts'
export * from './routes/query.ts'
export * from './routes/pathname.ts'
export * from './utils/search.ts'
export * from './utils/licences.ts'
export * from './utils/places.ts'
export * from './utils/replaceLinks.ts'
export * from './utils/normalizeString.ts'
export { default as findNormalizedMatches, findAllMatches } from './utils/findNormalizedMatches.ts'
export * from './utils/index.ts'
export { getCategoryTiles } from './utils/categories.ts'
export * from './constants/map.ts'
export * from './constants/news.ts'
export * from './utils/dateFilterUtils.ts'
export * from './utils/getExcerpt.ts'
export { default as getNearbyRegions } from './utils/getNearbyRegions.ts'
export { default as getExternalMapsLink } from './utils/getExternalMapsLink.ts'
export { default as normalizePath } from './utils/normalizePath.ts'
export { default as parseHTML } from './utils/parseHTML.ts'
export { default as encodeQR } from 'qr'
export { embedInCollection } from './utils/geoJson.ts'
export { prepareMapFeatures, prepareMapFeature, MIN_DISTANCE_THRESHOLD } from './utils/geoJson.ts'
export { default as getExcerpt } from './utils/getExcerpt.ts'
export { default as isCurrentlyOpen } from './utils/isCurrentlyOpen.ts'
export * from './constants/index.ts'
export { default as TileModel } from './models/TileModel.ts'
export type ExternalSourcePermissions = Record<string, boolean>
