#!/usr/bin/env node

const loadBuildConfig = require('../build-configs').default
const { program } = require('commander')
const fs = require('fs')

program
  .option('-d, --debug', 'enable extreme logging')

const createXcconfigs = async buildConfigName => {
  const { iosBuildOptions } = loadBuildConfig(buildConfigName)
  const content = Object.keys(iosBuildOptions).map(key => `${key} = ${iosBuildOptions[key]}`).join('\n')
  fs.writeFileSync('ios/buildConfig.tmp.xcconfig', content)
}

program
  .command('config <build_config_name>')
  .description('create and write a new .xcconfig from the iosBuildOptions of the specified build config')
  .action(async buildConfigName => {
    try {
      await createXcconfigs(buildConfigName)
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  })

program.parse(process.argv)
