#!/usr/bin/env node

const { program } = require('commander')
const loadBuildConfig = require('../build-configs')
const fs = require('fs')

program
  .option('-d, --debug', 'enable extreme logging')

const createXcconfig = async buildConfigName => {
  const { iosBuildOptions } = loadBuildConfig(buildConfigName)
  const content = Object.keys(iosBuildOptions).map(key => `${key} = ${iosBuildOptions[key]}`).join('\n')
  fs.writeFileSync('ios/buildConfig.xcconfig', content)
}

program
  .command('from <build-config-name>')
  .description('commits the supplied version name and code to github and tags the commit')
  .action(async buildConfigName => {
    try {
      await createXcconfig(buildConfigName)
    } catch (e) {
      console.error(e)
      process.exit(1)
    }
  })

program.parse(process.argv)
