#!/usr/bin/env node

const loadBuildConfig = require('../build-configs').default
const { program } = require('commander')

program
  .requiredOption('--directory <directory>', 'the directory to put the created xcconfig file in')

program
  .command('dump <build_config_name>')
  .description('outputs the specified build config as JSON')
  .action(async buildConfigName => {
    const buildConfig = loadBuildConfig(buildConfigName)
    console.log(JSON.stringify(buildConfig))
  })

program.parse(process.argv)
