// flow-typed signature: 190518e0dbe39703c4c0cd43431363eb
// flow-typed version: <<STUB>>/@octokit/plugin-paginate-rest_v^2.4.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/plugin-paginate-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/plugin-paginate-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/plugin-paginate-rest/dist-node' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/compose-paginate' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/generated/paginating-endpoints' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/iterator' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/normalize-paginated-list-response' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/paginate' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/paginating-endpoints' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/types' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-src/version' {
  declare module.exports: any;
}

declare module '@octokit/plugin-paginate-rest/dist-web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@octokit/plugin-paginate-rest/dist-node/index' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-node'>;
}
declare module '@octokit/plugin-paginate-rest/dist-node/index.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-node'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/compose-paginate.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/compose-paginate'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/generated/paginating-endpoints.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/generated/paginating-endpoints'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/index' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/index.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/iterator.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/iterator'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/normalize-paginated-list-response.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/normalize-paginated-list-response'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/paginate.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/paginate'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/paginating-endpoints.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/paginating-endpoints'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/types.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/types'>;
}
declare module '@octokit/plugin-paginate-rest/dist-src/version.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-src/version'>;
}
declare module '@octokit/plugin-paginate-rest/dist-web/index' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-web'>;
}
declare module '@octokit/plugin-paginate-rest/dist-web/index.js' {
  declare module.exports: $Exports<'@octokit/plugin-paginate-rest/dist-web'>;
}
