fastlane_version "2.143.0"

default_platform :android

platform :android do
  CREDENTIALS_GIT_REPOSITORY_URL = ENV['CREDENTIALS_GIT_REPOSITORY_URL']
  CREDENTIALS_DIRECTORY_PATH = ENV['CREDENTIALS_DIRECTORY_PATH']
  CREDENTIALS_KEYSTORE_PATH = ENV['CREDENTIALS_KEYSTORE_PATH']


  KEYSTORE_PATH = ENV['KEYSTORE_PATH'] || 'test.keystore'
  KEYSTORE_KEY_ALIAS = ENV['KEYSTORE_KEY_ALIAS'] || 'test'
  KEYSTORE_PASSWORD = ENV['KEYSTORE_PASSWORD'] || '123456'
  KEYSTORE_KEY_PASSWORD = ENV['KEYSTORE_KEY_PASSWORD'] || '123456'

  desc "Prepare the keystore"
  lane :keystore do
    ensure_env_vars(
        env_vars: ['CREDENTIALS_GIT_REPOSITORY_URL']
    )

    puts("Cloning repository with keystore")

    unless File.exists? File.expand_path(CREDENTIALS_DIRECTORY_PATH)
      sh("git clone #{CREDENTIALS_GIT_REPOSITORY_URL} #{CREDENTIALS_DIRECTORY_PATH}")
    end

    puts("Decrypting keystore")

    sh("openssl enc -d -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt \\
          -in #{CREDENTIALS_KEYSTORE_PATH} -out #{KEYSTORE_PATH} \\
          -pass pass:$CREDENTIALS_KEYSTORE_PASSWORD")
  end

  desc "Create a release build"
  lane :dependencies do
    gradle(task: "androidDependencies")
  end

  desc "Create a release build"
  lane :build do
    ENV["E2E_TEST_IDS"] = "1"
    ENV["BUNDLE_CONFIG"] = "./metro.config.ci.js"

    gradle(
        task: "build",
        properties: {
            :VERSION_CODE => 100008,
            :VERSION_NAME => "2020.3.2",
            :KEYSTORE_PATH => KEYSTORE_PATH,
            :KEYSTORE_KEY_ALIAS => KEYSTORE_KEY_ALIAS,
            :KEYSTORE_PASSWORD => KEYSTORE_PASSWORD,
            :KEYSTORE_KEY_PASSWORD => KEYSTORE_KEY_PASSWORD
        },
        print_command: true
    )
  end


  desc "Upload to Browserstack Live"
  lane :browserstack_upload_live do
    ensure_env_vars(
        env_vars: ['BROWSERSTACK_USERNAME', 'BROWSERSTACK_ACCESS_KEY']
    )

    upload_to_browserstack_app_live(
        browserstack_username: ENV["BROWSERSTACK_USERNAME"],
        browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
        file_path: "app/build/outputs/apk/release/app-release.apk"
    )
  end

  desc "Run E2E tests on BrowserStack"
  lane :browserstack_e2e_tests do
    ensure_env_vars(
        env_vars: ['BROWSERSTACK_USERNAME', 'BROWSERSTACK_ACCESS_KEY']
    )

    upload_to_browserstack_app_automate(
        browserstack_username: ENV["BROWSERSTACK_USERNAME"],
        browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
        file_path: "app/build/outputs/apk/release/app-release.apk"
    )

    ENV["E2E_CAPS"] = 'ci_browserstack'
    ENV["E2E_PLATFORM"] = 'android'
    ENV["E2E_SERVER"] = 'browserstack'
    ENV["E2E_BROWSERSTACK_USER"] = ENV["BROWSERSTACK_USERNAME"]
    ENV["E2E_BROWSERSTACK_KEY"] = ENV["BROWSERSTACK_ACCESS_KEY"]
    ENV["E2E_BROWSERSTACK_APP"] = lane_context[SharedValues::BROWSERSTACK_APP_ID]

    yarn(
        command: "test:e2e",
        package_path: "../package.json"
    )
  end

  desc "experiment"
  lane :experiment do
    ENV["E2E_CAPS"] = 'ci_browserstack'
    sh("echo $E2E_CAPS")
  end

  desc "Upload to Play Store"
  lane :playstore_upload do
    ensure_env_vars(
        env_vars: ['GOOGLE_SERVICE_ACCOUNT_JSON']
    )

    upload_to_play_store(
        version_code: 100008,
        version_name: "2020.3.2",
        track: 'alpha',
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_metadata: true,
        release_status: "draft",
        apk: 'app/build/outputs/apk/release/app-release.apk',
        json_key_data: GOOGLE_SERVICE_ACCOUNT_JSON
    )
  end

  before_all do
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
