fastlane_version "2.143.0"

default_platform :android

platform :android do
  CREDENTIALS_GIT_REPOSITORY_URL = ENV['CREDENTIALS_GIT_REPOSITORY_URL']
  CREDENTIALS_DIRECTORY_PATH = ENV['CREDENTIALS_DIRECTORY_PATH']
  CREDENTIALS_KEYSTORE_PATH = ENV['CREDENTIALS_KEYSTORE_PATH']
  KEYSTORE_PATH = ENV['KEYSTORE_PATH']

  desc "Prepare the keystore"
  lane :keystore do
    puts("Cloning repository with keystore")

    unless File.exists? File.expand_path(CREDENTIALS_DIRECTORY_PATH)
      sh("git clone #{CREDENTIALS_GIT_REPOSITORY_URL} #{CREDENTIALS_DIRECTORY_PATH}")
    end

    puts("Decrypting keystore")

    sh("openssl enc -d -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt \\
          -in #{CREDENTIALS_KEYSTORE_PATH} -out #{KEYSTORE_PATH} \\
          -pass pass:$CREDENTIALS_KEYSTORE_PASSWORD")
  end

  desc "Create a release build"
  lane :build do
    gradle(
        task: "build",
        properties: {
            :versionCode => 100,
            :versionName => "1.0.0",
            :MYAPP_RELEASE_STORE_FILE => KEYSTORE_PATH,
            :MYAPP_RELEASE_KEY_ALIAS => ENV['KEYSTORE_KEY_ALIAS'],
            :MYAPP_RELEASE_STORE_PASSWORD => ENV['KEYSTORE_PASSWORD'],
            :MYAPP_RELEASE_KEY_PASSWORD => ENV['KEYSTORE_KEY_PASSWORD']
        },
        print_command: false
    )
  end

  before_all do
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
