require_relative '../../fastlane/version'

fastlane_version "2.143.0"

CREDENTIALS_GIT_REPOSITORY_URL = ENV['CREDENTIALS_GIT_REPOSITORY_URL']
CREDENTIALS_DIRECTORY_PATH = ENV['CREDENTIALS_DIRECTORY_PATH']
CREDENTIALS_KEYSTORE_PATH = ENV['CREDENTIALS_KEYSTORE_PATH']

KEYSTORE_PATH = ENV['KEYSTORE_PATH'] || 'test.keystore'
KEYSTORE_KEY_ALIAS = ENV['KEYSTORE_KEY_ALIAS'] || 'test'
KEYSTORE_PASSWORD = ENV['KEYSTORE_PASSWORD'] || '123456'
KEYSTORE_KEY_PASSWORD = ENV['KEYSTORE_KEY_PASSWORD'] || '123456'

desc "Prepare the keystore"
lane :keystore do
  ensure_env_vars(
      env_vars: ['CREDENTIALS_GIT_REPOSITORY_URL']
  )

  puts("Cloning repository with keystore")

  unless File.exists? File.expand_path(CREDENTIALS_DIRECTORY_PATH)
    sh("git clone #{CREDENTIALS_GIT_REPOSITORY_URL} #{CREDENTIALS_DIRECTORY_PATH}")
  end

  puts("Decrypting keystore")

  sh("openssl enc -d -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt \\
          -in #{CREDENTIALS_KEYSTORE_PATH} -out #{KEYSTORE_PATH} \\
          -pass pass:$CREDENTIALS_KEYSTORE_PASSWORD")
end

desc "Download Gradle Dependencies"
lane :dependencies do
  gradle(task: "androidDependencies")
end

desc "Create a build"
lane :build do
  next_version = next_version()

  puts(next_version)

  ENV["BUNDLE_CONFIG"] = "./metro.config.ci.js"

  gradle_system_properties = {
      :"org.gradle.jvmargs" => "-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError",
      :"org.gradle.daemon" => false,
      :"org.gradle.parallel" => false,
      :"org.gradle.configureondemand" => true
  }

  if ENV['TOTAL_CPUS']
    # Gradle uses the wrong cpu count from the host (e.g. 36)
    gradle_system_properties["org.gradle.workers.max"] = ENV['TOTAL_CPUS']
  end

  gradle(
      task: "assembleRelease",
      properties: {
          :VERSION_CODE => next_version[:new_version_code],
          :VERSION_NAME => next_version[:new_version_name],
          :KEYSTORE_PATH => KEYSTORE_PATH,
          :KEYSTORE_KEY_ALIAS => KEYSTORE_KEY_ALIAS,
          :KEYSTORE_PASSWORD => KEYSTORE_PASSWORD,
          :KEYSTORE_KEY_PASSWORD => KEYSTORE_KEY_PASSWORD
      },
      system_properties: gradle_system_properties,
      print_command: true
  )
end

