import { TypographyType } from '../../TypographyType'
import { FontsType } from './fonts'

export const commonTypography = (fonts: FontsType): TypographyType => ({
  display1: {
    fontSize: 57,
    lineHeight: 64,
    letterSpacing: -0.25,
    fontWeight: 500,
    fontFamily: fonts.web.decorativeFont,
  },
  display2: {
    fontSize: 45,
    lineHeight: 52,
    letterSpacing: 0,
    fontWeight: 500,
    fontFamily: fonts.web.decorativeFont,
  },
  display3: {
    fontSize: 32,
    lineHeight: 44,
    letterSpacing: 0,
    fontWeight: 500,
    fontFamily: fonts.web.decorativeFont,
  },
  h1: {
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: 0,
    fontWeight: 600,
    fontFamily: fonts.web.decorativeFont,
  },
  h2: {
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: 0,
    fontWeight: 600,
    fontFamily: fonts.web.decorativeFont,
  },
  h3: {
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0,
    fontWeight: 600,
    fontFamily: fonts.web.decorativeFont,
  },
  title1: {
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: 0,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
  title2: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
    fontWeight: 500,
    fontFamily: fonts.web.contentFont,
  },
  title3: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
    fontWeight: 500,
    fontFamily: fonts.web.contentFont,
  },
  label1: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
    fontWeight: 500,
    fontFamily: fonts.web.contentFont,
  },
  label2: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.5,
    fontWeight: 500,
    fontFamily: fonts.web.contentFont,
  },
  label3: {
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.5,
    fontWeight: 500,
    fontFamily: fonts.web.contentFont,
  },
  body1: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
  body2: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.25,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
  body3: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
  chip1: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
  chip2: {
    fontSize: 12,
    lineHeight: 20,
    letterSpacing: 0,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
  chip3: {
    fontSize: 10,
    lineHeight: 20,
    letterSpacing: 0,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
  button: {
    fontSize: 14,
    lineHeight: 36,
    letterSpacing: 1.25,
    fontWeight: 600,
    textTransform: 'capitalize',
    fontFamily: fonts.web.contentFont,
  },
  textLink: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
    fontWeight: 400,
    fontFamily: fonts.web.contentFont,
  },
})
